/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiProviderConfigsIdPatchMutationResponse, ApiProviderConfigsIdPatchPathParams, ApiProviderConfigsIdPatchMutationRequest } from "../../models";

function getApiProviderConfigsIdPatchUrl(params: ApiProviderConfigsIdPatchPathParams) {
  return `/api/v1/provider_configs/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Updates the ProviderConfig resource.
 * @description Updates the ProviderConfig resource.
 * {@link /api/v1/provider_configs/{id}}
 */
export const apiProviderConfigsIdPatch = (
  args: {
    params: ApiProviderConfigsIdPatchPathParams;
    body: ApiProviderConfigsIdPatchMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiProviderConfigsIdPatchMutationResponse> => {
  return http.patch(getApiProviderConfigsIdPatchUrl(args.params), {
    ...options,
    json: args.body,
  }).json<ApiProviderConfigsIdPatchMutationResponse>();
};