/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiProviderConfigsGetCollectionQueryResponse, ApiProviderConfigsGetCollectionQueryParams } from "../../models";

function getApiProviderConfigsGetCollectionUrl() {
  return "/api/v1/provider_configs" as const;
}
/**
 * @summary Retrieves the collection of ProviderConfig resources.
 * @description Retrieves the collection of ProviderConfig resources.
 * {@link /api/v1/provider_configs}
 */
export const apiProviderConfigsGetCollection = (
  args: {
    query: ApiProviderConfigsGetCollectionQueryParams;
  },
  options?: RequestOptions,
): Promise<ApiProviderConfigsGetCollectionQueryResponse> => {
  return http.get(getApiProviderConfigsGetCollectionUrl(), {
    ...options,
    searchParams: args.query,
  }).json<ApiProviderConfigsGetCollectionQueryResponse>();
};