/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiProviderConfigsIdGetQueryResponse, ApiProviderConfigsIdGetPathParams } from "../../models";

function getApiProviderConfigsIdGetUrl(params: ApiProviderConfigsIdGetPathParams) {
  return `/api/v1/provider_configs/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Получение конфигурации провайдера
 * @description Возвращает детальную информацию о конфигурации провайдера по её ID.
 * {@link /api/v1/provider_configs/{id}}
 */
export const apiProviderConfigsIdGet = (
  args: {
    params: ApiProviderConfigsIdGetPathParams;
  },
  options?: RequestOptions,
): Promise<ApiProviderConfigsIdGetQueryResponse> => {
  return http.get(getApiProviderConfigsIdGetUrl(args.params), {
    ...options,
  }).json<ApiProviderConfigsIdGetQueryResponse>();
};