/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiProviderConfigsPostMutationResponse, ApiProviderConfigsPostMutationRequest } from "../../models";

function getApiProviderConfigsPostUrl() {
  return "/api/v1/provider_configs" as const;
}
/**
 * @summary Создание конфигурации провайдера
 * @description Создает новую конфигурацию для провайдера с указанными значениями свойств.
 * {@link /api/v1/provider_configs}
 */
export const apiProviderConfigsPost = (
  args: {
    body: ApiProviderConfigsPostMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiProviderConfigsPostMutationResponse> => {
  return http.post(getApiProviderConfigsPostUrl(), {
    ...options,
    json: args.body,
  }).json<ApiProviderConfigsPostMutationResponse>();
};