/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../../../../hydra-item-base-schema-schema";

export const PropertyJsonldStorageItemReadGetIdPropertyReadSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "name": z.optional(z.string()),
"slug": z.string().nullish(),
"type": z.enum(["string", "number", "bool"]).default("string").nullish(),
"forEntity": z.enum(["provider", "recorder", "storage"]).nullish(),
"isRequired": z.optional(z.boolean()),
"id": z.optional(z.union([z.string(), z.string()]))
    }))