/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiCurrentSubscriptionGetQueryResponse, ApiCurrentSubscriptionGet403, ApiCurrentSubscriptionGet404 } from "../../models/subscription/api-current-subscription-get";
import { http } from "msw";

export function ApiCurrentSubscriptionGetHandlerResponse200(data: ApiCurrentSubscriptionGetQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiCurrentSubscriptionGetHandlerResponse403(data: ApiCurrentSubscriptionGet403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiCurrentSubscriptionGetHandlerResponse404(data: ApiCurrentSubscriptionGet404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiCurrentSubscriptionGetHandler(data?: ApiCurrentSubscriptionGetQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/v1/current_subscription`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}