/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { ProviderConfigProviderConfigItemWriteSchema } from "../provider-config-provider-config-item-write-schema";
import { ProviderConfigJsonldProviderConfigItemReadSchema } from "./jsonld-provider-config-item-read-schema";

/**
 * @description ProviderConfig resource created
 */
export const ApiProviderConfigsPost201Schema = z.lazy(() => ProviderConfigJsonldProviderConfigItemReadSchema)

/**
 * @description Invalid input
 */
export const ApiProviderConfigsPost400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiProviderConfigsPost403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiProviderConfigsPost422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new ProviderConfig resource
 */
export const ApiProviderConfigsPostMutationRequestSchema = z.lazy(() => ProviderConfigProviderConfigItemWriteSchema)

export const ApiProviderConfigsPostMutationResponseSchema = z.lazy(() => ApiProviderConfigsPost201Schema)