/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { ProviderConfigJsonldProviderConfigItemReadSchema } from "./jsonld-provider-config-item-read-schema";

export const ApiProviderConfigsIdGetPathParamsSchema = z.object({
    "id": z.string().describe("ProviderConfig identifier")
    })

/**
 * @description ProviderConfig resource
 */
export const ApiProviderConfigsIdGet200Schema = z.lazy(() => ProviderConfigJsonldProviderConfigItemReadSchema)

/**
 * @description Forbidden
 */
export const ApiProviderConfigsIdGet403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiProviderConfigsIdGet404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiProviderConfigsIdGetQueryResponseSchema = z.lazy(() => ApiProviderConfigsIdGet200Schema)