/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";

export const ApiProviderConfigsIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("ProviderConfig identifier")
    })

/**
 * @description ProviderConfig resource deleted
 */
export const ApiProviderConfigsIdDelete204Schema = z.any()

/**
 * @description Forbidden
 */
export const ApiProviderConfigsIdDelete403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiProviderConfigsIdDelete404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiProviderConfigsIdDeleteMutationResponseSchema = z.lazy(() => ApiProviderConfigsIdDelete204Schema)