/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { ProviderConfigProviderConfigItemUpdateJsonMergePatchSchema } from "../provider-config-provider-config-item-update/json-merge-patch-schema";
import { ProviderConfigJsonldProviderConfigItemReadSchema } from "./jsonld-provider-config-item-read-schema";

export const ApiProviderConfigsIdPatchPathParamsSchema = z.object({
    "id": z.string().describe("ProviderConfig identifier")
    })

/**
 * @description ProviderConfig resource updated
 */
export const ApiProviderConfigsIdPatch200Schema = z.lazy(() => ProviderConfigJsonldProviderConfigItemReadSchema)

/**
 * @description Invalid input
 */
export const ApiProviderConfigsIdPatch400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiProviderConfigsIdPatch403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiProviderConfigsIdPatch404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiProviderConfigsIdPatch422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated ProviderConfig resource
 */
export const ApiProviderConfigsIdPatchMutationRequestSchema = z.lazy(() => ProviderConfigProviderConfigItemUpdateJsonMergePatchSchema)

export const ApiProviderConfigsIdPatchMutationResponseSchema = z.lazy(() => ApiProviderConfigsIdPatch200Schema)