/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ProviderConfigErrorFormDataSchema } from "../provider-config-error/form-data-schema";

export const ProviderConfigFormDataSchema = z.object({
    "name": z.string(),
"isActive": z.optional(z.boolean().default(true)),
"provider": z.string(),
"propertyValues": z.array(z.string()),
"errors": z.optional(z.array(z.lazy(() => ProviderConfigErrorFormDataSchema))),
"id": z.optional(z.union([z.string(), z.string()])),
"dateCreate": z.optional(z.string().datetime()),
"dateUpdate": z.string().datetime().nullish()
    })