/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ProviderFormDataMeetReadItemSchema } from "../provider/form-data-meet-read-item-schema";

export const ProviderConfigFormDataMeetReadItemSchema = z.object({
    "name": z.string(),
"provider": z.lazy(() => ProviderFormDataMeetReadItemSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })