/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const ProviderConfigFormDataMeetCreateReadSchema = z.object({
    "name": z.string(),
"id": z.optional(z.union([z.string(), z.string()]))
    })