/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ProviderHtmlMeetReadItemSchema } from "../provider/html-meet-read-item-schema";

export const ProviderConfigHtmlMeetReadItemSchema = z.object({
    "name": z.string(),
"provider": z.lazy(() => ProviderHtmlMeetReadItemSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })