/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ProviderHtmlGetObjIntegrationSchema } from "../provider/html-get-obj-integration-schema";

export const ProviderConfigHtmlGetObjIntegrationSchema = z.object({
    "name": z.string(),
"provider": z.lazy(() => ProviderHtmlGetObjIntegrationSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })