/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";
import { PropertyValueJsonldProviderConfigCollectionReadSchema } from "../property-value/jsonld-provider-config-collection-read-schema";
import { ProviderJsonldProviderConfigCollectionReadSchema } from "../provider/jsonld-provider-config-collection-read-schema";

export const ProviderConfigJsonldProviderConfigCollectionReadSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "name": z.string(),
"isActive": z.optional(z.boolean().default(true)),
"provider": z.lazy(() => ProviderJsonldProviderConfigCollectionReadSchema),
"propertyValues": z.array(z.lazy(() => PropertyValueJsonldProviderConfigCollectionReadSchema)),
"id": z.optional(z.union([z.string(), z.string()]))
    }))