/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";
import { ProviderJsonldGetCollectionIntegrationSchema } from "../provider/jsonld-get-collection-integration-schema";

export const ProviderConfigJsonldGetCollectionIntegrationSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "name": z.string(),
"provider": z.lazy(() => ProviderJsonldGetCollectionIntegrationSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    }))