/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";
import { ProviderJsonldMeetReadItemSchema } from "../provider/jsonld-meet-read-item-schema";

export const ProviderConfigJsonldMeetReadItemSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "name": z.string(),
"provider": z.lazy(() => ProviderJsonldMeetReadItemSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    }))