/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiQuestionsGetCollectionQueryResponse, ApiQuestionsGetCollection403 } from "../../models/question/api-questions-get-collection";
import { http } from "msw";

export function ApiQuestionsGetCollectionHandlerResponse200(data: ApiQuestionsGetCollectionQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiQuestionsGetCollectionHandlerResponse403(data: ApiQuestionsGetCollection403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiQuestionsGetCollectionHandler(data?: ApiQuestionsGetCollectionQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/v1/questions`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}