/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiQuestionsIdGetQueryResponse, ApiQuestionsIdGet403, ApiQuestionsIdGet404 } from "../../models/question/api-questions-id-get";
import { http } from "msw";

export function ApiQuestionsIdGetHandlerResponse200(data: ApiQuestionsIdGetQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiQuestionsIdGetHandlerResponse403(data: ApiQuestionsIdGet403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiQuestionsIdGetHandlerResponse404(data: ApiQuestionsIdGet404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiQuestionsIdGetHandler(data?: ApiQuestionsIdGetQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/v1/questions/:id`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}