/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { MediaTaskJsonldGetItemMediaTaskSchema } from "./jsonld-get-item-media-task-schema";

export const ApiMediaTasksIdGetPathParamsSchema = z.object({
    "id": z.string().describe("MediaTask identifier")
    })

/**
 * @description MediaTask resource
 */
export const ApiMediaTasksIdGet200Schema = z.lazy(() => MediaTaskJsonldGetItemMediaTaskSchema)

/**
 * @description Forbidden
 */
export const ApiMediaTasksIdGet403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiMediaTasksIdGet404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiMediaTasksIdGetQueryResponseSchema = z.lazy(() => ApiMediaTasksIdGet200Schema)