/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { MediaTaskJsonMergePatchSchema } from "./json-merge-patch-schema";
import { MediaTaskJsonldGetItemMediaTaskSchema } from "./jsonld-get-item-media-task-schema";

export const ApiMediaTasksIdtranscribePatchPathParamsSchema = z.object({
    "id": z.string().describe("MediaTask identifier")
    })

/**
 * @description MediaTask resource updated
 */
export const ApiMediaTasksIdtranscribePatch200Schema = z.lazy(() => MediaTaskJsonldGetItemMediaTaskSchema)

/**
 * @description Invalid input
 */
export const ApiMediaTasksIdtranscribePatch400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiMediaTasksIdtranscribePatch403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiMediaTasksIdtranscribePatch404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiMediaTasksIdtranscribePatch422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated MediaTask resource
 */
export const ApiMediaTasksIdtranscribePatchMutationRequestSchema = z.lazy(() => MediaTaskJsonMergePatchSchema).schema.omit({ 'dateCreate': true,'dateUpdate': true,'roles': true,'userIdentifier': true })

export const ApiMediaTasksIdtranscribePatchMutationResponseSchema = z.lazy(() => ApiMediaTasksIdtranscribePatch200Schema)