/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { MediaTaskJsonldSchema } from "./jsonld-schema";
import { MediaTaskMediaTaskBulkRequestDtoSchema } from "./media-task-bulk-request-dto-schema";

/**
 * @description MediaTask resource created
 */
export const ApiMediaTasksmassDeletePost201Schema = z.lazy(() => MediaTaskJsonldSchema)

/**
 * @description Invalid input
 */
export const ApiMediaTasksmassDeletePost400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiMediaTasksmassDeletePost403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiMediaTasksmassDeletePost422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new MediaTask resource
 */
export const ApiMediaTasksmassDeletePostMutationRequestSchema = z.lazy(() => MediaTaskMediaTaskBulkRequestDtoSchema)

export const ApiMediaTasksmassDeletePostMutationResponseSchema = z.lazy(() => ApiMediaTasksmassDeletePost201Schema)