/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { FileFormDataGetCollectionMediaTasksSchema } from "../file/form-data-get-collection-media-tasks-schema";

export const MediaTaskFormDataGetCollectionMediaTasksSchema = z.object({
    "file": z.optional(z.union([z.lazy(() => FileFormDataGetCollectionMediaTasksSchema), z.null()])),
"status": z.optional(z.enum(["CREATED", "TRANSCRIBE", "TRANSCRIBE_COMPLETED", "TRANSCRIBE_ERROR", "SUMMARY", "SUMMARY_COMPLETED", "SUMMARY_ERROR"]).default("CREATED")),
"id": z.optional(z.union([z.string(), z.string()])),
"dateCreate": z.optional(z.string().datetime())
    })