/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const MediaTaskHtmlMediaTaskCreateSchema = z.object({
    "file": z.string().nullish()
    })