/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { FileJsonldMediaTaskUpdateReadSchema } from "../file/jsonld-media-task-update-read-schema";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";

export const MediaTaskJsonldMediaTaskUpdateReadSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "file": z.optional(z.union([z.lazy(() => FileJsonldMediaTaskUpdateReadSchema), z.null()])),
"user": z.string().nullish(),
"transcriptionResult": z.string().nullish(),
"summaryResult": z.string().nullish(),
"status": z.optional(z.enum(["CREATED", "TRANSCRIBE", "TRANSCRIBE_COMPLETED", "TRANSCRIBE_ERROR", "SUMMARY", "SUMMARY_COMPLETED", "SUMMARY_ERROR"]).default("CREATED")),
"traceId": z.string().nullish(),
"duration": z.number().int().nullish(),
"dateCreate": z.optional(z.string().datetime())
    }))