/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";

export const MediaTaskJsonldMediaTaskUpdateSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "transcriptionResult": z.string().nullish(),
"summaryResult": z.string().nullish(),
"status": z.optional(z.enum(["CREATED", "TRANSCRIBE", "TRANSCRIBE_COMPLETED", "TRANSCRIBE_ERROR", "SUMMARY", "SUMMARY_COMPLETED", "SUMMARY_ERROR"]).default("CREATED"))
    }))