/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { FileJsonldGetItemMediaTaskSchema } from "../file/jsonld-get-item-media-task-schema";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";
import { UserJsonldGetItemMediaTaskSchema } from "../user/jsonld-get-item-media-task-schema";

export const MediaTaskJsonldGetItemMediaTaskSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "file": z.optional(z.union([z.lazy(() => FileJsonldGetItemMediaTaskSchema), z.null()])),
"user": z.optional(z.union([z.lazy(() => UserJsonldGetItemMediaTaskSchema), z.null()])),
"transcriptionResult": z.string().nullish(),
"summaryResult": z.string().nullish(),
"status": z.optional(z.enum(["CREATED", "TRANSCRIBE", "TRANSCRIBE_COMPLETED", "TRANSCRIBE_ERROR", "SUMMARY", "SUMMARY_COMPLETED", "SUMMARY_ERROR"]).default("CREATED")),
"traceId": z.string().nullish(),
"duration": z.number().int().nullish(),
"id": z.optional(z.union([z.string(), z.string()])),
"dateCreate": z.optional(z.string().datetime())
    }))