/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const TokenApiTokenResponseDtoFormDataSchema = z.object({
    "accessToken": z.optional(z.string())
    })