/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type StorageConfigStorageConfigUpdateJsonMergePatch = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined, iri-reference
    */
    storage?: string;
};