/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const SubscriptionPlanSubscriptionPlanResponseDtoFormDataSchema = z.object({
    "paymentUrl": z.optional(z.string())
    })