/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../../hydra-item-base-schema-schema";

export const SubscriptionPlanSubscriptionPlanResponseDtoJsonldSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "paymentUrl": z.optional(z.string())
    }))