/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const multipartUploadFormDataStatusEnum = {
    PENDING: "PENDING",
    UPLOADING: "UPLOADING",
    VERIFYING: "VERIFYING",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED",
    EXPIRED: "EXPIRED"
} as const;

export type MultipartUploadFormDataStatusEnumKey = (typeof multipartUploadFormDataStatusEnum)[keyof typeof multipartUploadFormDataStatusEnum];

export const multipartUploadFormDataChunkSizeEnum = {
    "1048576": 1048576,
    "5242880": 5242880,
    "10485760": 10485760
} as const;

export type MultipartUploadFormDataChunkSizeEnumKey = (typeof multipartUploadFormDataChunkSizeEnum)[keyof typeof multipartUploadFormDataChunkSizeEnum];

export type MultipartUploadFormData = {
    /**
     * @default "PENDING"
     * @type string,null
    */
    status?: MultipartUploadFormDataStatusEnumKey | null;
    /**
     * @type string
    */
    filename: string;
    /**
     * @type string
    */
    fileSize: string;
    /**
     * @type string,null
    */
    mimeType?: string | null;
    /**
     * @type integer
    */
    chunkSize: MultipartUploadFormDataChunkSizeEnumKey;
    /**
     * @type integer | undefined
    */
    totalChunks?: number;
    /**
     * @type array | undefined
    */
    uploadedChunks?: number[];
    /**
     * @type string,null
    */
    checksum?: string | null;
    /**
     * @minLength 0
     * @maxLength 100
     * @default 0
     * @type integer | undefined
    */
    progress?: number;
    /**
     * @type string | undefined, date-time
    */
    startedAt?: string;
    /**
     * @type string,null, date-time
    */
    completedAt?: string | null;
    /**
     * @type string | undefined, date-time
    */
    expiresAt?: string;
    /**
     * @type string | undefined
    */
    tempPath?: string;
    /**
     * @type string,null
    */
    finalPath?: string | null;
    /**
     * @type string,null, iri-reference
    */
    owner: string | null;
    /**
     * @type string,null, iri-reference
    */
    media?: string | null;
    /**
     * @type array | undefined
    */
    chunks?: string[];
    /**
     * @default 0
     * @type integer | undefined
    */
    totalBytesUploaded?: number;
    /**
     * @type string | undefined, date-time
    */
    lastActivityAt?: string;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined, date-time
    */
    readonly dateCreate?: string;
    /**
     * @type string,null, date-time
    */
    readonly dateUpdate?: string | null;
    /**
     * @type array | undefined
    */
    readonly missingChunks?: string[];
    /**
     * @type boolean | undefined
    */
    readonly expired?: boolean;
    /**
     * @type boolean | undefined
    */
    readonly beResumed?: boolean;
    /**
     * @type boolean | undefined
    */
    readonly uploadComplete?: boolean;
};