/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MultipartUploadMultipartCompleteResponseDtoSet = {
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string,null
    */
    error?: string | null;
    /**
     * @type string | undefined
    */
    jobId?: string;
};