/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MultipartUploadMultipartInitRequestDtoSet = {
    /**
     * @default ""
     * @type string | undefined
    */
    filename?: string;
    /**
     * @default 0
     * @type integer | undefined
    */
    fileSize?: number;
    /**
     * @default ""
     * @type string | undefined
    */
    checksum?: string;
    /**
     * @default ""
     * @type string | undefined
    */
    mimeType?: string;
    /**
     * @default 0
     * @type integer | undefined
    */
    chunkSize?: number;
};