/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiMediaTasksIddownloadtranscribePatchMutationResponse, ApiMediaTasksIddownloadtranscribePatch400, ApiMediaTasksIddownloadtranscribePatch403, ApiMediaTasksIddownloadtranscribePatch404, ApiMediaTasksIddownloadtranscribePatch422 } from "../../models/media-task/api-media-tasks-iddownloadtranscribe-patch";
import { http } from "msw";

export function ApiMediaTasksIddownloadtranscribePatchHandlerResponse200(data: ApiMediaTasksIddownloadtranscribePatchMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIddownloadtranscribePatchHandlerResponse400(data: ApiMediaTasksIddownloadtranscribePatch400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIddownloadtranscribePatchHandlerResponse403(data: ApiMediaTasksIddownloadtranscribePatch403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIddownloadtranscribePatchHandlerResponse404(data: ApiMediaTasksIddownloadtranscribePatch404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIddownloadtranscribePatchHandlerResponse422(data: ApiMediaTasksIddownloadtranscribePatch422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIddownloadtranscribePatchHandler(data?: ApiMediaTasksIddownloadtranscribePatchMutationResponse | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.patch(`/api/v1/media_tasks/:id/download/transcribe`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}