/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiMediaTasksIdDeleteMutationResponse, ApiMediaTasksIdDelete403, ApiMediaTasksIdDelete404 } from "../../models/media-task/api-media-tasks-id-delete";
import { http } from "msw";

export function ApiMediaTasksIdDeleteHandlerResponse204(data?: ApiMediaTasksIdDeleteMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
}

export function ApiMediaTasksIdDeleteHandlerResponse403(data: ApiMediaTasksIdDelete403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIdDeleteHandlerResponse404(data: ApiMediaTasksIdDelete404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIdDeleteHandler(data?: string | number | boolean | null | object | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.delete(`/api/v1/media_tasks/:id`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
    })
}