/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiMediaTasksIdtranscribePatchMutationResponse, ApiMediaTasksIdtranscribePatch400, ApiMediaTasksIdtranscribePatch403, ApiMediaTasksIdtranscribePatch404, ApiMediaTasksIdtranscribePatch422 } from "../../models/media-task/api-media-tasks-idtranscribe-patch";
import { http } from "msw";

export function ApiMediaTasksIdtranscribePatchHandlerResponse200(data: ApiMediaTasksIdtranscribePatchMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIdtranscribePatchHandlerResponse400(data: ApiMediaTasksIdtranscribePatch400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIdtranscribePatchHandlerResponse403(data: ApiMediaTasksIdtranscribePatch403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIdtranscribePatchHandlerResponse404(data: ApiMediaTasksIdtranscribePatch404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIdtranscribePatchHandlerResponse422(data: ApiMediaTasksIdtranscribePatch422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIdtranscribePatchHandler(data?: ApiMediaTasksIdtranscribePatchMutationResponse | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.patch(`/api/v1/media_tasks/:id/transcribe`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}