/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiMediaTasksIddownloadsummaryPatchMutationResponse, ApiMediaTasksIddownloadsummaryPatch400, ApiMediaTasksIddownloadsummaryPatch403, ApiMediaTasksIddownloadsummaryPatch404, ApiMediaTasksIddownloadsummaryPatch422 } from "../../models/media-task/api-media-tasks-iddownloadsummary-patch";
import { http } from "msw";

export function ApiMediaTasksIddownloadsummaryPatchHandlerResponse200(data: ApiMediaTasksIddownloadsummaryPatchMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIddownloadsummaryPatchHandlerResponse400(data: ApiMediaTasksIddownloadsummaryPatch400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIddownloadsummaryPatchHandlerResponse403(data: ApiMediaTasksIddownloadsummaryPatch403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIddownloadsummaryPatchHandlerResponse404(data: ApiMediaTasksIddownloadsummaryPatch404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIddownloadsummaryPatchHandlerResponse422(data: ApiMediaTasksIddownloadsummaryPatch422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksIddownloadsummaryPatchHandler(data?: ApiMediaTasksIddownloadsummaryPatchMutationResponse | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.patch(`/api/v1/media_tasks/:id/download/summary`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}