/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiMediaTasksPostMutationResponse, ApiMediaTasksPost400, ApiMediaTasksPost403, ApiMediaTasksPost422 } from "../../models/media-task/api-media-tasks-post";
import { http } from "msw";

export function ApiMediaTasksPostHandlerResponse201(data: ApiMediaTasksPostMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksPostHandlerResponse400(data: ApiMediaTasksPost400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksPostHandlerResponse403(data: ApiMediaTasksPost403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksPostHandlerResponse422(data: ApiMediaTasksPost422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMediaTasksPostHandler(data?: ApiMediaTasksPostMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.post(`/api/v1/media_tasks`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}