/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetUserQueryResponse } from "../../models/users/get-user";
import { http } from "msw";

export function GetUserHandlerResponse200(data: GetUserQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function GetUserHandler(data?: GetUserQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/users/:id`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}