/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const TeamTeamWriteJsonMergePatchSchema = z.object({
    "name": z.string().nullish(),
"billingEmail": z.optional(z.string())
    })