/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { MultipartChunkChunkWriteSchema } from "../multipart-chunk-chunk/write-schema";
import { MultipartChunkMultipartUploadResponseDtoJsonldSchema } from "./multipart-upload-response-dto/jsonld-schema";

/**
 * @description MultipartChunk resource created
 */
export const ApiMultipartchunkPost201Schema = z.lazy(() => MultipartChunkMultipartUploadResponseDtoJsonldSchema)

/**
 * @description Invalid input
 */
export const ApiMultipartchunkPost400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiMultipartchunkPost403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiMultipartchunkPost422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new MultipartChunk resource
 */
export const ApiMultipartchunkPostMutationRequestSchema = z.lazy(() => MultipartChunkChunkWriteSchema)

export const ApiMultipartchunkPostMutationResponseSchema = z.lazy(() => ApiMultipartchunkPost201Schema)