/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { PriceJsonldGetCollectionTokenConsummation } from "./jsonld-get-collection-token-consummation";

export type ApiPricesIdGetPathParams = {
    /**
     * @description Price identifier
     * @type string
    */
    id: string;
};

/**
 * @description Price resource
*/
export type ApiPricesIdGet200 = PriceJsonldGetCollectionTokenConsummation;

/**
 * @description Forbidden
*/
export type ApiPricesIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiPricesIdGet404 = ErrorJsonld;

export type ApiPricesIdGetQueryResponse = ApiPricesIdGet200;

export type ApiPricesIdGetQuery = {
    Response: ApiPricesIdGet200;
    PathParams: ApiPricesIdGetPathParams;
    Errors: ApiPricesIdGet403 | ApiPricesIdGet404;
};