/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PriceFormDataGetCollectionSubscriptionPlan = {
    /**
     * @default 0
     * @type integer | undefined
    */
    period?: number;
    readonly id?: any;
    /**
     * @type integer,null
    */
    amount?: number | null;
    /**
     * @type string,null
    */
    schedule?: string | null;
};