/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyValueRecorderConfigWriteJsonMergePatch } from "../property-value-recorder-config-write/json-merge-patch";

export type RecorderConfigRecorderConfigWriteJsonMergePatch = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @default true
     * @type boolean | undefined
    */
    isActive?: boolean;
    /**
     * @type string,null, iri-reference
    */
    recorder?: string | null;
    /**
     * @type array | undefined
    */
    propertyValues?: PropertyValueRecorderConfigWriteJsonMergePatch[];
};