/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { ProductJsonldSchema } from "./jsonld-schema";

export const ApiProductsIdbuyPatchPathParamsSchema = z.object({
    "id": z.string().describe("Product identifier")
    })

/**
 * @description Product resource updated
 */
export const ApiProductsIdbuyPatch200Schema = z.lazy(() => ProductJsonldSchema)

/**
 * @description Invalid input
 */
export const ApiProductsIdbuyPatch400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiProductsIdbuyPatch403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiProductsIdbuyPatch404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiProductsIdbuyPatch422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

export const ApiProductsIdbuyPatchMutationResponseSchema = z.lazy(() => ApiProductsIdbuyPatch200Schema)