/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const ProductFormDataGetCollectionSubscriptionPlanSchema = z.object({
    "tokens": z.optional(z.number().default(0))
    })