/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const ProductFormDataGetItemPaymentSchema = z.object({
    "tokens": z.optional(z.number().default(0)),
"displayName": z.string().nullish()
    })