/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const ProductHtmlSchema = z.object({
    "tokens": z.optional(z.number().default(0)),
"amount": z.optional(z.number().int().default(0)),
"currency": z.optional(z.string().default("")),
"displayName": z.string().nullish(),
"paymentProviderDetailsUrl": z.string().nullish(),
"name": z.optional(z.string()),
"id": z.optional(z.any()),
"externalReference": z.string().nullish()
    })