/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";

export const ProductJsonldGetCollectionPaymentSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "tokens": z.optional(z.number().default(0)),
"displayName": z.string().nullish()
    }))