/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";

export const ProductJsonldGetItemProductSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "tokens": z.optional(z.number().default(0)),
"amount": z.optional(z.number().int().default(0)),
"currency": z.optional(z.string().default("")),
"displayName": z.string().nullish(),
"name": z.optional(z.string())
    }))