/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiMultipartIdcompletePostMutationResponse, ApiMultipartIdcompletePost400, ApiMultipartIdcompletePost403, ApiMultipartIdcompletePost422 } from "../../models/multipart-upload/api-multipart-idcomplete-post";
import { http } from "msw";

export function ApiMultipartIdcompletePostHandlerResponse201(data: ApiMultipartIdcompletePostMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMultipartIdcompletePostHandlerResponse400(data: ApiMultipartIdcompletePost400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMultipartIdcompletePostHandlerResponse403(data: ApiMultipartIdcompletePost403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMultipartIdcompletePostHandlerResponse422(data: ApiMultipartIdcompletePost422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMultipartIdcompletePostHandler(data?: ApiMultipartIdcompletePostMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.post(`/api/v1/multipart/:id/complete`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}