/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiMultipartinitPostMutationResponse, ApiMultipartinitPost400, ApiMultipartinitPost403, ApiMultipartinitPost422 } from "../../models/multipart-upload/api-multipartinit-post";
import { http } from "msw";

export function ApiMultipartinitPostHandlerResponse201(data: ApiMultipartinitPostMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMultipartinitPostHandlerResponse400(data: ApiMultipartinitPost400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMultipartinitPostHandlerResponse403(data: ApiMultipartinitPost403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMultipartinitPostHandlerResponse422(data: ApiMultipartinitPost422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMultipartinitPostHandler(data?: ApiMultipartinitPostMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.post(`/api/v1/multipart/init`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}