/** Generated by scripts/sync-package-versions.mjs — do not edit manually. */
export const ECOSYSTEM_VERSION = "0.0.0";

export const packageVersions = {
  "@echojs/architect": "0.0.0",
  "@echojs/bench": "0.0.0",
  "@echojs/core": "0.0.0",
  "@echojs/devtools-core": "0.0.0",
  "@echojs/form": "0.0.0",
  "@echojs/framework": "0.0.0",
  "@echojs/hyperdom": "0.0.0",
  "@echojs/i18n": "0.0.0",
  "@echojs/oxc-config": "0.1.0",
  "@echojs/persist": "0.0.0",
  "@echojs/query": "0.0.0",
  "@echojs/reactivity": "0.0.0",
  "@echojs/router": "0.0.0",
  "@echojs/store": "0.0.0",
  "@echojs/ui": "0.0.0",
  "@echojs/url-state": "0.0.0",
} as const;

export type PackageName = keyof typeof packageVersions;

export const getPackageVersion = (name: string): string | undefined =>
  name in packageVersions ? packageVersions[name as PackageName] : undefined;
