/** Generated by tools/scripts/sync-package-versions.mjs — do not edit manually. */
export const ECOSYSTEM_VERSION = "0.8.0";

export const packageVersions = {
  "@echojs-ecosystem/architect": "0.8.0",
  "@echojs-ecosystem/async": "0.8.0",
  "@echojs-ecosystem/core": "0.8.0",
  "@echojs-ecosystem/devtools": "0.8.0",
  "@echojs-ecosystem/form": "0.8.0",
  "@echojs-ecosystem/framework": "0.8.0",
  "@echojs-ecosystem/generator": "0.8.0",
  "@echojs-ecosystem/hyperdom": "0.8.0",
  "@echojs-ecosystem/i18n": "0.8.0",
  "@echojs-ecosystem/network": "0.8.0",
  "@echojs-ecosystem/oxc-config": "0.1.0",
  "@echojs-ecosystem/permission": "0.8.0",
  "@echojs-ecosystem/persist": "0.8.0",
  "@echojs-ecosystem/reactivity": "0.8.0",
  "@echojs-ecosystem/router": "0.8.0",
  "@echojs-ecosystem/store": "0.8.0",
  "@echojs-ecosystem/ui": "0.8.0",
  "@echojs-ecosystem/url-state": "0.8.0",
  "@echojs-ecosystem/utils": "0.8.0",
} as const;

export type PackageName = keyof typeof packageVersions;

export const getPackageVersion = (name: string): string | undefined =>
  name in packageVersions ? packageVersions[name as PackageName] : undefined;
