/** Nav page lists for modern package docs (reactivity-style layout). */

export type PackageDocPage = { slug: string; title: string }

export type ModernPackageDocConfig = {
  id: string
  title: string
  npmPackage: string
  /** Pin to top of Packages sidebar with highlight styling. */
  featured?: boolean
  frameworkSubpath?: string
  guides: PackageDocPage[]
  api: PackageDocPage[]
  examples: PackageDocPage[]
}

export const modernPackageDocConfigs: ModernPackageDocConfig[] = [
  {
    id: 'reactivity',
    title: 'Reactivity',
    npmPackage: '@echojs-ecosystem/reactivity',
    frameworkSubpath: 'reactivity',
    guides: [
      { slug: 'important-defaults', title: 'Important Defaults' },
      { slug: 'signals', title: 'Signals' },
      { slug: 'computed', title: 'Computed Values' },
      { slug: 'effects', title: 'Effects' },
      { slug: 'batching', title: 'Batching' },
      { slug: 'scopes-and-cleanup', title: 'Scopes & Cleanup' },
      { slug: 'readonly-signals', title: 'Readonly Signals' },
      { slug: 'immutable-updates', title: 'Immutable Updates' },
      { slug: 'hyperdom-integration', title: 'HyperDOM Integration' },
    ],
    api: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'signal', title: 'signal' },
      { slug: 'computed', title: 'computed' },
      { slug: 'effect', title: 'effect' },
      { slug: 'batch', title: 'batch' },
      { slug: 'scope', title: 'scope' },
      { slug: 'cleanup', title: 'cleanup' },
      { slug: 'readonly', title: 'readonly' },
      { slug: 'type-guards', title: 'Type Guards' },
      { slug: 'types', title: 'Types' },
    ],
    examples: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'counter', title: 'Counter' },
      { slug: 'derived-greeting', title: 'Derived Greeting' },
      { slug: 'batch-updates', title: 'Batch Updates' },
      { slug: 'todo-list', title: 'Todo List' },
      { slug: 'scope-timer', title: 'Scope & Timer' },
      { slug: 'shopping-cart', title: 'Shopping Cart' },
    ],
  },
  {
    id: 'hyperdom',
    title: 'HyperDOM',
    npmPackage: '@echojs-ecosystem/hyperdom',
    frameworkSubpath: 'hyperdom',
    guides: [
      { slug: 'important-defaults', title: 'Important Defaults' },
      { slug: 'views-and-dsl', title: 'Views & DSL' },
      { slug: 'reactive-children', title: 'Reactive Children' },
      { slug: 'reactive-props', title: 'Reactive Props' },
      { slug: 'events-and-handlers', title: 'Events & Handlers' },
      { slug: 'show-and-list', title: 'Show & List' },
      { slug: 'models-and-components', title: 'Models & Components' },
      { slug: 'rendering-and-teardown', title: 'Rendering & Teardown' },
      { slug: 'refs-and-dom-access', title: 'Refs & DOM Access' },
      { slug: 'styling-and-classes', title: 'Styling & Classes' },
      { slug: 'lifecycle-mount', title: 'Lifecycle Mount' },
      { slug: 'trusted-html', title: 'Trusted HTML' },
    ],
    api: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'h', title: 'h' },
      { slug: 'render', title: 'render' },
      { slug: 'mount', title: 'mount' },
      { slug: 'lifecycle-mount', title: 'lifecycle/mount' },
      { slug: 'create-view', title: 'createView' },
      { slug: 'create-model', title: 'createModel' },
      { slug: 'create-component', title: 'createComponent' },
      { slug: 'show', title: 'Show' },
      { slug: 'list', title: 'List' },
      { slug: 'strict-context', title: 'Strict Context' },
      { slug: 'dsl', title: 'DSL Tags' },
      { slug: 'cx', title: 'cx' },
      { slug: 'types', title: 'Types' },
    ],
    examples: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'counter', title: 'Counter' },
      { slug: 'model-view-counter', title: 'Model + View Counter' },
      { slug: 'conditional-ui', title: 'Conditional UI' },
      { slug: 'todo-list', title: 'Todo List' },
      { slug: 'doc-article', title: 'Doc Article' },
      { slug: 'lifecycle-resize', title: 'Lifecycle Mount' },
    ],
  },
  {
    id: 'framework',
    title: 'Framework',
    npmPackage: '@echojs-ecosystem/framework',
    featured: true,
    guides: [
      { slug: 'important-defaults', title: 'Important Defaults' },
      { slug: 'create-echo-app', title: 'createEchoApp' },
      { slug: 'providers', title: 'Providers' },
      { slug: 'dependency-injection', title: 'Dependency Injection' },
      { slug: 'subpath-imports', title: 'Subpath Imports' },
    ],
    api: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'create-echo-app', title: 'createEchoApp' },
      { slug: 'create-provider', title: 'createProvider' },
      { slug: 'provide-inject', title: 'provide / inject' },
      { slug: 'app-exports', title: 'App Exports' },
    ],
    examples: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'minimal-app', title: 'Minimal App' },
      { slug: 'with-router', title: 'With Router' },
      { slug: 'with-query', title: 'With Query' },
      { slug: 'with-i18n', title: 'With i18n' },
    ],
  },
  {
    id: 'router',
    title: 'Router',
    npmPackage: '@echojs-ecosystem/router',
    frameworkSubpath: 'router',
    guides: [
      { slug: 'route-trees', title: 'Route Trees & Layouts' },
      { slug: 'router-lifecycle', title: 'Router Lifecycle' },
      { slug: 'navigation', title: 'Navigation & NavLink' },
      { slug: 'before-load', title: 'beforeLoad & Route Data' },
      { slug: 'lazy-routes', title: 'Lazy Routes' },
      { slug: 'guards-and-redirects', title: 'Guards & Redirects' },
    ],
    api: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'route-views', title: 'Route Views' },
      { slug: 'create-router', title: 'createRoutes & createRouter' },
      { slug: 'hyperdom', title: 'HyperDOM Integration' },
      { slug: 'operators', title: 'Operators' },
      { slug: 'path-query-history', title: 'Path, Query & History' },
    ],
    examples: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'docs-routes', title: 'Docs Dynamic Routes' },
      { slug: 'nested-routes', title: 'Nested Routes' },
      { slug: 'page-and-layout', title: 'Page + Layout' },
      { slug: 'nav-link', title: 'NavLink Sidebar' },
      { slug: 'imperative-nav', title: 'Imperative Navigation' },
    ],
  },
  {
    id: 'store',
    title: 'Store',
    npmPackage: '@echojs-ecosystem/store',
    frameworkSubpath: 'store',
    guides: [
      { slug: 'creating-stores', title: 'Creating Stores' },
      { slug: 'actions', title: 'Actions with withActions' },
      { slug: 'derived-state', title: 'Derived State' },
      { slug: 'events', title: 'Events & Subscriptions' },
      { slug: 'readonly', title: 'Readonly Stores' },
      { slug: 'hyperdom-integration', title: 'HyperDOM Integration' },
    ],
    api: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'create-store', title: 'createStore' },
      { slug: 'select', title: 'select' },
      { slug: 'combine', title: 'combine' },
      { slug: 'extensions', title: 'Extensions' },
      { slug: 'readonly', title: 'readonly' },
    ],
    examples: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'theme-and-counter', title: 'Theme & Counter' },
      { slug: 'view-integration', title: 'View Reads Store' },
      { slug: 'combine-names', title: 'combine Full Name' },
      { slug: 'session-stores', title: 'Session Stores' },
    ],
  },
  {
    id: 'network-http',
    title: 'Network / HTTP',
    npmPackage: '@echojs-ecosystem/network',
    frameworkSubpath: 'network/http',
    guides: [
      { slug: 'important-defaults', title: 'Important Defaults' },
      { slug: 'client-composition', title: 'Client Composition' },
      {
        slug: 'retries-timeouts-redirects',
        title: 'Retries, Timeouts & Redirects',
      },
      { slug: 'hooks-and-middleware', title: 'Hooks & Middleware' },
      { slug: 'query-integration', title: 'Query Integration' },
    ],
    api: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'create-http-client', title: 'createHttpClient' },
      { slug: 'request-options', title: 'RequestOptions' },
      { slug: 'hooks', title: 'Hooks' },
      { slug: 'errors', title: 'Errors' },
      { slug: 'types', title: 'Types' },
    ],
    examples: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'rest-api', title: 'REST API Client' },
      { slug: 'auth-and-headers', title: 'Auth & Headers' },
      { slug: 'error-handling', title: 'Error Handling' },
    ],
  },
  {
    id: 'query',
    title: 'Query',
    npmPackage: '@echojs-ecosystem/query',
    frameworkSubpath: 'query',
    guides: [
      { slug: 'query-definitions', title: 'Query Definitions' },
      { slug: 'reactive-binding', title: 'Reactive Binding' },
      { slug: 'query-client', title: 'QueryClient & Cache' },
      { slug: 'mutations', title: 'Mutations' },
      { slug: 'infinite-queries', title: 'Infinite Queries' },
      { slug: 'abort-and-cancellation', title: 'Abort & Cancellation' },
    ],
    api: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'create-query', title: 'createQuery' },
      { slug: 'create-infinite-query', title: 'createInfiniteQuery' },
      { slug: 'create-mutation', title: 'createMutation' },
      { slug: 'query-client', title: 'QueryClient & Provider' },
      { slug: 'utilities', title: 'Managers & Utilities' },
    ],
    examples: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'jsonplaceholder', title: 'JSONPlaceholder' },
      { slug: 'query-demo-model', title: 'Query Demo Model' },
      { slug: 'status-helpers', title: 'View Status Helpers' },
      { slug: 'doc-content', title: 'Docs Markdown Loader' },
      { slug: 'provider-defaults', title: 'Provider Defaults' },
    ],
  },
  {
    id: 'url-state',
    title: 'URL State',
    npmPackage: '@echojs-ecosystem/url-state',
    frameworkSubpath: 'url-state',
    guides: [
      { slug: 'important-defaults', title: 'Important Defaults' },
      { slug: 'parsers', title: 'Parsers' },
      { slug: 'query-params', title: 'createQueryParams' },
      { slug: 'router-adapter', title: 'Router Adapter' },
      { slug: 'history-and-sync', title: 'History & Sync' },
    ],
    api: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'parsers', title: 'parseAs*' },
      { slug: 'create-query-params', title: 'createQueryParams' },
      { slug: 'adapters', title: 'Adapters' },
      { slug: 'types', title: 'Types' },
    ],
    examples: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'catalog-filters', title: 'Catalog Filters' },
      { slug: 'pagination', title: 'Pagination' },
      { slug: 'memory-url', title: 'Memory URL' },
    ],
  },
  {
    id: 'persist',
    title: 'Persist',
    npmPackage: '@echojs-ecosystem/persist',
    frameworkSubpath: 'persist',
    guides: [
      { slug: 'important-defaults', title: 'Important Defaults' },
      { slug: 'storage-adapters', title: 'Storage Adapters' },
      { slug: 'hydrate-and-save', title: 'Hydrate & Save' },
      { slug: 'slicing-and-merge', title: 'Slicing & Merge' },
      { slug: 'migration-and-ttl', title: 'Migration & TTL' },
    ],
    api: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'with-storage', title: 'withStorage' },
      { slug: 'adapters', title: 'Adapters' },
      { slug: 'serializers', title: 'Serializers' },
      { slug: 'persist-controller', title: 'Persist Controller' },
    ],
    examples: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'theme-store', title: 'Theme Store' },
      { slug: 'auth-session', title: 'Auth Session' },
    ],
  },
  {
    id: 'ui',
    title: 'UI',
    npmPackage: '@echojs-ecosystem/ui',
    frameworkSubpath: 'ui',
    guides: [
      { slug: 'important-defaults', title: 'Important Defaults' },
      { slug: 'ui-provider', title: 'UIProvider & Theme' },
      { slug: 'button-and-field', title: 'Button & Field' },
      { slug: 'forms', title: 'Form Controls' },
    ],
    api: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'button', title: 'Button' },
      { slug: 'field', title: 'Field' },
      { slug: 'provider', title: 'UIProvider' },
    ],
    examples: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'button-demo', title: 'Button Demo' },
      { slug: 'form-row', title: 'Form Row' },
    ],
  },
  {
    id: 'i18n',
    title: 'i18n',
    npmPackage: '@echojs-ecosystem/i18n',
    frameworkSubpath: 'i18n',
    guides: [
      { slug: 'important-defaults', title: 'Important Defaults' },
      { slug: 'messages-and-keys', title: 'Messages & Keys' },
      { slug: 'locales', title: 'Locales' },
      { slug: 'interpolation-and-plural', title: 'Interpolation & Plural' },
      { slug: 'intl-helpers', title: 'Intl Helpers' },
    ],
    api: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'create-i18n', title: 'createI18n' },
      { slug: 'create-i18n-provider', title: 'createI18nProvider' },
      { slug: 'detect-locale', title: 'detectLocale' },
      { slug: 'types', title: 'Types' },
    ],
    examples: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'locale-switcher', title: 'Locale Switcher' },
      { slug: 'docs-locales', title: 'Docs Locales' },
      { slug: 'plural-messages', title: 'Plural Messages' },
    ],
  },
  {
    id: 'devtools',
    title: 'DevTools',
    npmPackage: '@echojs-ecosystem/devtools',
    frameworkSubpath: 'devtools',
    guides: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'registry', title: 'Registry & Timeline' },
      { slug: 'integration', title: 'Package Integration' },
    ],
    api: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'register-node', title: 'registerDevtoolsNode' },
      { slug: 'bridge', title: 'Bridge' },
    ],
    examples: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'local-debug', title: 'Local Debug' },
    ],
  },
  {
    id: 'cli',
    title: 'CLI',
    npmPackage: '@echojs-ecosystem/cli',
    guides: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'planned-commands', title: 'Planned Commands' },
    ],
    api: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'create', title: 'create (planned)' },
      { slug: 'generate', title: 'generate (planned)' },
    ],
    examples: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'scaffold-app', title: 'Scaffold App (planned)' },
    ],
  },
  {
    id: 'architect',
    title: 'Architect',
    npmPackage: '@echojs-ecosystem/architect',
    guides: [
      { slug: 'important-defaults', title: 'Important Defaults' },
      { slug: 'layers', title: 'Layer Rules' },
      { slug: 'public-api', title: 'Public API' },
      { slug: 'presets', title: 'Presets & Config' },
      { slug: 'ci-integration', title: 'CI Integration' },
    ],
    api: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'lint', title: 'lint' },
      { slug: 'define-config', title: 'defineConfig' },
      { slug: 'presets', title: 'Presets' },
    ],
    examples: [
      { slug: 'overview', title: 'Overview' },
      { slug: 'docs-site-config', title: 'Docs Site Config' },
      { slug: 'feature-slice', title: 'Feature Slice Check' },
    ],
  },
]
