/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { PropertyJsonldPropertyItemRead } from "./jsonld-property-item-read";

export type ApiPropertiesIdGetPathParams = {
    /**
     * @description Property identifier
     * @type string
    */
    id: string;
};

/**
 * @description Property resource
*/
export type ApiPropertiesIdGet200 = PropertyJsonldPropertyItemRead;

/**
 * @description Not found
*/
export type ApiPropertiesIdGet404 = ErrorJsonld;

export type ApiPropertiesIdGetQueryResponse = ApiPropertiesIdGet200;

export type ApiPropertiesIdGetQuery = {
    Response: ApiPropertiesIdGet200;
    PathParams: ApiPropertiesIdGetPathParams;
    Errors: ApiPropertiesIdGet404;
};