/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const propertyFormDataRecorderConfigReadItemTypeEnum = {
    string: "string",
    number: "number",
    bool: "bool"
} as const;

export type PropertyFormDataRecorderConfigReadItemTypeEnumKey = (typeof propertyFormDataRecorderConfigReadItemTypeEnum)[keyof typeof propertyFormDataRecorderConfigReadItemTypeEnum];

export const propertyFormDataRecorderConfigReadItemForEntityEnum = {
    provider: "provider",
    recorder: "recorder",
    storage: "storage"
} as const;

export type PropertyFormDataRecorderConfigReadItemForEntityEnumKey = (typeof propertyFormDataRecorderConfigReadItemForEntityEnum)[keyof typeof propertyFormDataRecorderConfigReadItemForEntityEnum];

export type PropertyFormDataRecorderConfigReadItem = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @default "string"
     * @type string,null
    */
    type?: PropertyFormDataRecorderConfigReadItemTypeEnumKey | null;
    /**
     * @type string,null
    */
    forEntity?: PropertyFormDataRecorderConfigReadItemForEntityEnumKey | null;
    /**
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};