/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const propertyFormDataProviderItemReadTypeEnum = {
    string: "string",
    number: "number",
    bool: "bool"
} as const;

export type PropertyFormDataProviderItemReadTypeEnumKey = (typeof propertyFormDataProviderItemReadTypeEnum)[keyof typeof propertyFormDataProviderItemReadTypeEnum];

export const propertyFormDataProviderItemReadForEntityEnum = {
    provider: "provider",
    recorder: "recorder",
    storage: "storage"
} as const;

export type PropertyFormDataProviderItemReadForEntityEnumKey = (typeof propertyFormDataProviderItemReadForEntityEnum)[keyof typeof propertyFormDataProviderItemReadForEntityEnum];

export type PropertyFormDataProviderItemRead = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @default "string"
     * @type string,null
    */
    type?: PropertyFormDataProviderItemReadTypeEnumKey | null;
    /**
     * @type string,null
    */
    forEntity?: PropertyFormDataProviderItemReadForEntityEnumKey | null;
    /**
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};