/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const propertyHtmlProviderConfigItemReadTypeEnum = {
    string: "string",
    number: "number",
    bool: "bool"
} as const;

export type PropertyHtmlProviderConfigItemReadTypeEnumKey = (typeof propertyHtmlProviderConfigItemReadTypeEnum)[keyof typeof propertyHtmlProviderConfigItemReadTypeEnum];

export const propertyHtmlProviderConfigItemReadForEntityEnum = {
    provider: "provider",
    recorder: "recorder",
    storage: "storage"
} as const;

export type PropertyHtmlProviderConfigItemReadForEntityEnumKey = (typeof propertyHtmlProviderConfigItemReadForEntityEnum)[keyof typeof propertyHtmlProviderConfigItemReadForEntityEnum];

export type PropertyHtmlProviderConfigItemRead = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @default "string"
     * @type string,null
    */
    type?: PropertyHtmlProviderConfigItemReadTypeEnumKey | null;
    /**
     * @type string,null
    */
    forEntity?: PropertyHtmlProviderConfigItemReadForEntityEnumKey | null;
    /**
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};