/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const propertyHtmlPropertyItemReadTypeEnum = {
    string: "string",
    number: "number",
    bool: "bool"
} as const;

export type PropertyHtmlPropertyItemReadTypeEnumKey = (typeof propertyHtmlPropertyItemReadTypeEnum)[keyof typeof propertyHtmlPropertyItemReadTypeEnum];

export const propertyHtmlPropertyItemReadForEntityEnum = {
    provider: "provider",
    recorder: "recorder",
    storage: "storage"
} as const;

export type PropertyHtmlPropertyItemReadForEntityEnumKey = (typeof propertyHtmlPropertyItemReadForEntityEnum)[keyof typeof propertyHtmlPropertyItemReadForEntityEnum];

export type PropertyHtmlPropertyItemRead = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @default "string"
     * @type string,null
    */
    type?: PropertyHtmlPropertyItemReadTypeEnumKey | null;
    /**
     * @type string,null
    */
    forEntity?: PropertyHtmlPropertyItemReadForEntityEnumKey | null;
    /**
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};