/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const propertyHtmlProviderItemReadTypeEnum = {
    string: "string",
    number: "number",
    bool: "bool"
} as const;

export type PropertyHtmlProviderItemReadTypeEnumKey = (typeof propertyHtmlProviderItemReadTypeEnum)[keyof typeof propertyHtmlProviderItemReadTypeEnum];

export const propertyHtmlProviderItemReadForEntityEnum = {
    provider: "provider",
    recorder: "recorder",
    storage: "storage"
} as const;

export type PropertyHtmlProviderItemReadForEntityEnumKey = (typeof propertyHtmlProviderItemReadForEntityEnum)[keyof typeof propertyHtmlProviderItemReadForEntityEnum];

export type PropertyHtmlProviderItemRead = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @default "string"
     * @type string,null
    */
    type?: PropertyHtmlProviderItemReadTypeEnumKey | null;
    /**
     * @type string,null
    */
    forEntity?: PropertyHtmlProviderItemReadForEntityEnumKey | null;
    /**
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};