/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";

export const propertyJsonldProviderConfigItemReadTypeEnum = {
    string: "string",
    number: "number",
    bool: "bool"
} as const;

export type PropertyJsonldProviderConfigItemReadTypeEnumKey = (typeof propertyJsonldProviderConfigItemReadTypeEnum)[keyof typeof propertyJsonldProviderConfigItemReadTypeEnum];

export const propertyJsonldProviderConfigItemReadForEntityEnum = {
    provider: "provider",
    recorder: "recorder",
    storage: "storage"
} as const;

export type PropertyJsonldProviderConfigItemReadForEntityEnumKey = (typeof propertyJsonldProviderConfigItemReadForEntityEnum)[keyof typeof propertyJsonldProviderConfigItemReadForEntityEnum];

export type PropertyJsonldProviderConfigItemRead = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @default "string"
     * @type string,null
    */
    type?: PropertyJsonldProviderConfigItemReadTypeEnumKey | null;
    /**
     * @type string,null
    */
    forEntity?: PropertyJsonldProviderConfigItemReadForEntityEnumKey | null;
    /**
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});