/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";

export const propertyJsonldPropertyItemReadTypeEnum = {
    string: "string",
    number: "number",
    bool: "bool"
} as const;

export type PropertyJsonldPropertyItemReadTypeEnumKey = (typeof propertyJsonldPropertyItemReadTypeEnum)[keyof typeof propertyJsonldPropertyItemReadTypeEnum];

export const propertyJsonldPropertyItemReadForEntityEnum = {
    provider: "provider",
    recorder: "recorder",
    storage: "storage"
} as const;

export type PropertyJsonldPropertyItemReadForEntityEnumKey = (typeof propertyJsonldPropertyItemReadForEntityEnum)[keyof typeof propertyJsonldPropertyItemReadForEntityEnum];

export type PropertyJsonldPropertyItemRead = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @default "string"
     * @type string,null
    */
    type?: PropertyJsonldPropertyItemReadTypeEnumKey | null;
    /**
     * @type string,null
    */
    forEntity?: PropertyJsonldPropertyItemReadForEntityEnumKey | null;
    /**
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});