/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";

export type ApiUsersIddeleteDeletePathParams = {
    /**
     * @description User identifier
     * @type string
    */
    id: string;
};

/**
 * @description User resource deleted
*/
export type ApiUsersIddeleteDelete204 = any;

/**
 * @description Forbidden
*/
export type ApiUsersIddeleteDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiUsersIddeleteDelete404 = ErrorJsonld;

export type ApiUsersIddeleteDeleteMutationResponse = ApiUsersIddeleteDelete204;

export type ApiUsersIddeleteDeleteMutation = {
    Response: ApiUsersIddeleteDelete204;
    PathParams: ApiUsersIddeleteDeletePathParams;
    Errors: ApiUsersIddeleteDelete403 | ApiUsersIddeleteDelete404;
};