/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { UserJsonldUserItemRead } from "./jsonld-user-item-read";

export type ApiUsersIdGetPathParams = {
    /**
     * @description User identifier
     * @type string
    */
    id: string;
};

/**
 * @description User resource
*/
export type ApiUsersIdGet200 = UserJsonldUserItemRead;

/**
 * @description Forbidden
*/
export type ApiUsersIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiUsersIdGet404 = ErrorJsonld;

export type ApiUsersIdGetQueryResponse = ApiUsersIdGet200;

export type ApiUsersIdGetQuery = {
    Response: ApiUsersIdGet200;
    PathParams: ApiUsersIdGetPathParams;
    Errors: ApiUsersIdGet403 | ApiUsersIdGet404;
};