/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UserFormDataGetItemMediaTask = {
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};