/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UserFormDataUserItemRead = {
    /**
     * @type string | undefined, date-time
    */
    createdAt?: string;
    /**
     * @type string
    */
    firstName: string;
    /**
     * @type string
    */
    lastName: string;
    /**
     * @type string, email
    */
    email: string;
    /**
     * @minLength 0
     * @default 0
     * @type number
    */
    personalTokenLimit: number;
    /**
     * @default 0
     * @type number | undefined
    */
    personalTokenLimitUsed?: number;
};