/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "../constraint-violation/jsonld";
import type { ErrorJsonld } from "../error/jsonld";
import type { UserInviteUserDtoJsonMergePatch } from "./invite-user-dto/json-merge-patch";
import type { UserJsonld } from "./jsonld";

/**
 * @description User resource updated
*/
export type InviteUser200 = UserJsonld;

/**
 * @description Invalid input
*/
export type InviteUser400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type InviteUser403 = ErrorJsonld;

/**
 * @description Not found
*/
export type InviteUser404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type InviteUser422 = ConstraintViolationJsonld;

/**
 * @description The updated User resource
*/
export type InviteUserMutationRequest = UserInviteUserDtoJsonMergePatch;

export type InviteUserMutationResponse = InviteUser200;

export type InviteUserMutation = {
    Response: InviteUser200;
    Request: InviteUserMutationRequest;
    Errors: InviteUser400 | InviteUser403 | InviteUser404 | InviteUser422;
};