/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiProductsIdGetQueryResponse, ApiProductsIdGetPathParams } from "../../models";

function getApiProductsIdGetUrl(params: ApiProductsIdGetPathParams) {
  return `/api/v1/products/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Retrieves a Product resource.
 * @description Retrieves a Product resource.
 * {@link /api/v1/products/{id}}
 */
export const apiProductsIdGet = (
  args: {
    params: ApiProductsIdGetPathParams;
  },
  options?: RequestOptions,
): Promise<ApiProductsIdGetQueryResponse> => {
  return http.get(getApiProductsIdGetUrl(args.params), {
    ...options,
  }).json<ApiProductsIdGetQueryResponse>();
};