/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const CoreRunProvidersSuccessDtoRunProvidersSuccessResponseSchema = z.object({
    "message": z.optional(z.string())
    })