/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { HydraCollectionBaseSchema } from "../hydra-collection-base-schema";
import type { SubscriptionPlanJsonldGetCollectionSubscriptionPlan } from "./jsonld-get-collection-subscription-plan";

export type ApiSubscriptionPlansGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 100
     * @default 10
     * @type integer | undefined
    */
    itemsPerPage?: number;
};

/**
 * @description SubscriptionPlan collection
*/
export type ApiSubscriptionPlansGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: SubscriptionPlanJsonldGetCollectionSubscriptionPlan[];
});

/**
 * @description Forbidden
*/
export type ApiSubscriptionPlansGetCollection403 = ErrorJsonld;

export type ApiSubscriptionPlansGetCollectionQueryResponse = ApiSubscriptionPlansGetCollection200;

export type ApiSubscriptionPlansGetCollectionQuery = {
    Response: ApiSubscriptionPlansGetCollection200;
    QueryParams: ApiSubscriptionPlansGetCollectionQueryParams;
    Errors: ApiSubscriptionPlansGetCollection403;
};