/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PriceHtmlGetCollectionSubscriptionPlan } from "../price/html-get-collection-subscription-plan";
import type { ProductHtmlGetCollectionSubscriptionPlan } from "../product/html-get-collection-subscription-plan";
import type { SubscriptionFeatureHtmlGetCollectionSubscriptionPlan } from "../subscription-feature/html-get-collection-subscription-plan";

export type SubscriptionPlanHtmlGetCollectionSubscriptionPlan = {
    /**
     * @type array | undefined
    */
    features?: SubscriptionFeatureHtmlGetCollectionSubscriptionPlan[];
    /**
     * @default false
     * @type boolean | undefined
    */
    public?: boolean;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @default false
     * @type boolean | undefined
    */
    free?: boolean;
    /**
     * @default 1
     * @type integer | undefined
    */
    userCount?: number;
    /**
     * @type array | undefined
    */
    prices?: PriceHtmlGetCollectionSubscriptionPlan[];
    product?: (ProductHtmlGetCollectionSubscriptionPlan | null);
    /**
     * @type string | undefined, ulid
    */
    id?: string;
};