/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type SubscriptionPlanHtmlGetCurrentSubscription = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined, ulid
    */
    id?: string;
};