/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";
import type { PriceJsonldGetCollectionSubscriptionPlan } from "../price/jsonld-get-collection-subscription-plan";
import type { ProductJsonldGetCollectionSubscriptionPlan } from "../product/jsonld-get-collection-subscription-plan";
import type { SubscriptionFeatureJsonldGetCollectionSubscriptionPlan } from "../subscription-feature/jsonld-get-collection-subscription-plan";

export type SubscriptionPlanJsonldGetCollectionSubscriptionPlan = (HydraItemBaseSchema & {
    /**
     * @type array | undefined
    */
    features?: SubscriptionFeatureJsonldGetCollectionSubscriptionPlan[];
    /**
     * @default false
     * @type boolean | undefined
    */
    public?: boolean;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @default false
     * @type boolean | undefined
    */
    free?: boolean;
    /**
     * @default 1
     * @type integer | undefined
    */
    userCount?: number;
    /**
     * @type array | undefined
    */
    prices?: PriceJsonldGetCollectionSubscriptionPlan[];
    product?: (ProductJsonldGetCollectionSubscriptionPlan | null);
    /**
     * @type string | undefined, ulid
    */
    id?: string;
});