/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiMeetsIddownloadsummaryPatchMutationResponse, ApiMeetsIddownloadsummaryPatch400, ApiMeetsIddownloadsummaryPatch403, ApiMeetsIddownloadsummaryPatch404, ApiMeetsIddownloadsummaryPatch422 } from "../../models/meet/api-meets-iddownloadsummary-patch";
import { http } from "msw";

export function ApiMeetsIddownloadsummaryPatchHandlerResponse200(data: ApiMeetsIddownloadsummaryPatchMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMeetsIddownloadsummaryPatchHandlerResponse400(data: ApiMeetsIddownloadsummaryPatch400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMeetsIddownloadsummaryPatchHandlerResponse403(data: ApiMeetsIddownloadsummaryPatch403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMeetsIddownloadsummaryPatchHandlerResponse404(data: ApiMeetsIddownloadsummaryPatch404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMeetsIddownloadsummaryPatchHandlerResponse422(data: ApiMeetsIddownloadsummaryPatch422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMeetsIddownloadsummaryPatchHandler(data?: ApiMeetsIddownloadsummaryPatchMutationResponse | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.patch(`/api/v1/meets/:id/download/summary`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}