/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiMeetsIdsummaryPatchMutationResponse, ApiMeetsIdsummaryPatch400, ApiMeetsIdsummaryPatch403, ApiMeetsIdsummaryPatch404, ApiMeetsIdsummaryPatch422 } from "../../models/meet/api-meets-idsummary-patch";
import { http } from "msw";

export function ApiMeetsIdsummaryPatchHandlerResponse200(data: ApiMeetsIdsummaryPatchMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMeetsIdsummaryPatchHandlerResponse400(data: ApiMeetsIdsummaryPatch400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMeetsIdsummaryPatchHandlerResponse403(data: ApiMeetsIdsummaryPatch403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMeetsIdsummaryPatchHandlerResponse404(data: ApiMeetsIdsummaryPatch404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMeetsIdsummaryPatchHandlerResponse422(data: ApiMeetsIdsummaryPatch422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiMeetsIdsummaryPatchHandler(data?: ApiMeetsIdsummaryPatchMutationResponse | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.patch(`/api/v1/meets/:id/summary`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}