/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateUserRequest } from "./create-user-request";
import type { User } from "./user";

/**
 * @description Created user
*/
export type CreateUser201 = User;

export type CreateUserMutationRequest = CreateUserRequest;

export type CreateUserMutationResponse = CreateUser201;

export type CreateUserMutation = {
    Response: CreateUser201;
    Request: CreateUserMutationRequest;
    Errors: any;
};