/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeleteUserPathParams = {
    /**
     * @type string
    */
    id: string;
};

/**
 * @description Deleted
*/
export type DeleteUser204 = any;

export type DeleteUserMutationResponse = DeleteUser204;

export type DeleteUserMutation = {
    Response: DeleteUser204;
    PathParams: DeleteUserPathParams;
    Errors: any;
};