/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { User } from "./user";

export type GetUserPathParams = {
    /**
     * @type string
    */
    id: string;
};

/**
 * @description User found
*/
export type GetUser200 = User;

export type GetUserQueryResponse = GetUser200;

export type GetUserQuery = {
    Response: GetUser200;
    PathParams: GetUserPathParams;
    Errors: any;
};