/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyStorageConfigDetailGetId } from "../property-storage-config/detail-get-id";

export type PropertyValueStorageConfigDetailGetId = {
    /**
     * @type string,null
    */
    value?: string | null;
    /**
     * @type object
    */
    property: PropertyStorageConfigDetailGetId;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};