/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MultipartChunkChunkWrite = {
    /**
     * @type string,null, iri-reference
    */
    upload: string | null;
    /**
     * @minLength 0
     * @type integer | undefined
    */
    chunkIndex?: number;
    /**
     * @type string | undefined
    */
    checksum?: string;
    /**
     * @type string | undefined, binary
    */
    chunkFile?: Blob;
};