/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";

export type ApiStorageConfigsIdDeletePathParams = {
    /**
     * @description StorageConfig identifier
     * @type string
    */
    id: string;
};

/**
 * @description StorageConfig resource deleted
*/
export type ApiStorageConfigsIdDelete204 = any;

/**
 * @description Forbidden
*/
export type ApiStorageConfigsIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiStorageConfigsIdDelete404 = ErrorJsonld;

export type ApiStorageConfigsIdDeleteMutationResponse = ApiStorageConfigsIdDelete204;

export type ApiStorageConfigsIdDeleteMutation = {
    Response: ApiStorageConfigsIdDelete204;
    PathParams: ApiStorageConfigsIdDeletePathParams;
    Errors: ApiStorageConfigsIdDelete403 | ApiStorageConfigsIdDelete404;
};