/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { StorageConfigJsonldStorageConfigDetailGetId } from "./jsonld-storage-config/detail-get-id";

export type ApiStorageConfigsIdGetPathParams = {
    /**
     * @description StorageConfig identifier
     * @type string
    */
    id: string;
};

/**
 * @description StorageConfig resource
*/
export type ApiStorageConfigsIdGet200 = StorageConfigJsonldStorageConfigDetailGetId;

/**
 * @description Forbidden
*/
export type ApiStorageConfigsIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiStorageConfigsIdGet404 = ErrorJsonld;

export type ApiStorageConfigsIdGetQueryResponse = ApiStorageConfigsIdGet200;

export type ApiStorageConfigsIdGetQuery = {
    Response: ApiStorageConfigsIdGet200;
    PathParams: ApiStorageConfigsIdGetPathParams;
    Errors: ApiStorageConfigsIdGet403 | ApiStorageConfigsIdGet404;
};