/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StorageFormDataMeetReadItem } from "../storage/form-data-meet-read-item";

export type StorageConfigFormDataMeetReadItem = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type object
    */
    storage: StorageFormDataMeetReadItem;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};