/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StorageFormDataMeetCreateRead } from "../storage/form-data-meet-create-read";

export type StorageConfigFormDataMeetCreateRead = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type object
    */
    storage: StorageFormDataMeetCreateRead;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};