/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StorageHtmlMeetReadItem } from "../storage/html-meet-read-item";

export type StorageConfigHtmlMeetReadItem = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type object
    */
    storage: StorageHtmlMeetReadItem;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};