/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StorageHtmlGetObjIntegration } from "../storage/html-get-obj-integration";

export type StorageConfigHtmlGetObjIntegration = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type object
    */
    storage: StorageHtmlGetObjIntegration;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};