/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";
import type { StorageConfigErrorJsonld } from "../storage-config-error/jsonld";

export type StorageConfigJsonld = (HydraItemBaseSchema & {
    /**
     * @type string
    */
    name: string;
    /**
     * @default true
     * @type boolean
    */
    isActive: boolean;
    /**
     * @type string, iri-reference
    */
    storage: string;
    /**
     * @type array
    */
    propertyValues: string[];
    /**
     * @type array | undefined
    */
    errors?: StorageConfigErrorJsonld[];
    /**
     * @default false
     * @type boolean | undefined
    */
    isGlobal?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined, date-time
    */
    readonly dateCreate?: string;
    /**
     * @type string,null, date-time
    */
    readonly dateUpdate?: string | null;
});