/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";
import type { StorageJsonldGetObjIntegration } from "../storage/jsonld-get-obj-integration";

export type StorageConfigJsonldGetObjIntegration = (HydraItemBaseSchema & {
    /**
     * @type string
    */
    name: string;
    storage: StorageJsonldGetObjIntegration;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});