/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";
import type { StorageJsonldMeetReadItem } from "../storage/jsonld-meet-read-item";

export type StorageConfigJsonldMeetReadItem = (HydraItemBaseSchema & {
    /**
     * @type string
    */
    name: string;
    storage: StorageJsonldMeetReadItem;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});