/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";
import type { StorageJsonldGetCollectionIntegration } from "../storage/jsonld-get-collection-integration";

export type StorageConfigJsonldGetCollectionIntegration = (HydraItemBaseSchema & {
    /**
     * @type string
    */
    name: string;
    storage: StorageJsonldGetCollectionIntegration;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});