/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { FileSetSchema } from "../file-set-schema";
import { FileJsonldGetSchema } from "./jsonld-get-schema";

/**
 * @description File resource created
 */
export const ApiFilesPost201Schema = z.lazy(() => FileJsonldGetSchema)

/**
 * @description Invalid input
 */
export const ApiFilesPost400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiFilesPost403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiFilesPost422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new File resource
 */
export const ApiFilesPostMutationRequestSchema = z.lazy(() => FileSetSchema)

export const ApiFilesPostMutationResponseSchema = z.lazy(() => ApiFilesPost201Schema)