/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";

export const FileGetResourcePathParamsSchema = z.object({
    "path": z.optional(z.string().describe("Путь до файла на сервере"))
    }).optional()

/**
 * @description File resource
 */
export const FileGetResource204Schema = z.any()

/**
 * @description Not found
 */
export const FileGetResource404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const FileGetResourceQueryResponseSchema = z.lazy(() => FileGetResource204Schema)