/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const FileFormDataGetSchema = z.object({
    "originalName": z.optional(z.string()),
"path": z.optional(z.string()),
"fullPath": z.optional(z.string()),
"mimeType": z.optional(z.string()),
"id": z.optional(z.union([z.string(), z.string()]))
    })