/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";

export const FileJsonldGetCollectionMediaTasksSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "originalName": z.optional(z.string()),
"duration": z.number().int().nullish(),
"id": z.optional(z.union([z.string(), z.string()])),
"dateCreate": z.optional(z.string().datetime())
    }))