/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { ProductJsonldGetItemProduct } from "./jsonld-get-item-product";

export type ApiProductsIdGetPathParams = {
    /**
     * @description Product identifier
     * @type string
    */
    id: string;
};

/**
 * @description Product resource
*/
export type ApiProductsIdGet200 = ProductJsonldGetItemProduct;

/**
 * @description Forbidden
*/
export type ApiProductsIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiProductsIdGet404 = ErrorJsonld;

export type ApiProductsIdGetQueryResponse = ApiProductsIdGet200;

export type ApiProductsIdGetQuery = {
    Response: ApiProductsIdGet200;
    PathParams: ApiProductsIdGetPathParams;
    Errors: ApiProductsIdGet403 | ApiProductsIdGet404;
};