/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ProductFormDataGetCollectionPayment = {
    /**
     * @default 0
     * @type number | undefined
    */
    tokens?: number;
    /**
     * @type string,null
    */
    displayName?: string | null;
};