/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ProductHtmlGetCollectionSubscriptionPlan = {
    /**
     * @default 0
     * @type number | undefined
    */
    tokens?: number;
};