/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";

export type ProductJsonldGetCollectionPayment = (HydraItemBaseSchema & {
    /**
     * @default 0
     * @type number | undefined
    */
    tokens?: number;
    /**
     * @type string,null
    */
    displayName?: string | null;
});