/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../../../../hydra-item-base-schema";

export const propertyJsonldStorageItemReadGetIdPropertyReadTypeEnum = {
    string: "string",
    number: "number",
    bool: "bool"
} as const;

export type PropertyJsonldStorageItemReadGetIdPropertyReadTypeEnumKey = (typeof propertyJsonldStorageItemReadGetIdPropertyReadTypeEnum)[keyof typeof propertyJsonldStorageItemReadGetIdPropertyReadTypeEnum];

export const propertyJsonldStorageItemReadGetIdPropertyReadForEntityEnum = {
    provider: "provider",
    recorder: "recorder",
    storage: "storage"
} as const;

export type PropertyJsonldStorageItemReadGetIdPropertyReadForEntityEnumKey = (typeof propertyJsonldStorageItemReadGetIdPropertyReadForEntityEnum)[keyof typeof propertyJsonldStorageItemReadGetIdPropertyReadForEntityEnum];

export type PropertyJsonldStorageItemReadGetIdPropertyRead = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @default "string"
     * @type string,null
    */
    type?: PropertyJsonldStorageItemReadGetIdPropertyReadTypeEnumKey | null;
    /**
     * @type string,null
    */
    forEntity?: PropertyJsonldStorageItemReadGetIdPropertyReadForEntityEnumKey | null;
    /**
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});