/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";

export type ApiMeetsIdDeletePathParams = {
    /**
     * @description Meet identifier
     * @type string
    */
    id: string;
};

/**
 * @description Meet resource deleted
*/
export type ApiMeetsIdDelete204 = any;

/**
 * @description Forbidden
*/
export type ApiMeetsIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiMeetsIdDelete404 = ErrorJsonld;

export type ApiMeetsIdDeleteMutationResponse = ApiMeetsIdDelete204;

export type ApiMeetsIdDeleteMutation = {
    Response: ApiMeetsIdDelete204;
    PathParams: ApiMeetsIdDeletePathParams;
    Errors: ApiMeetsIdDelete403 | ApiMeetsIdDelete404;
};