/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { HydraCollectionBaseSchema } from "../hydra-collection-base-schema";
import type { MeetJsonldMeetReadCollection } from "./jsonld-meet-read-collection";

export const apiMeetsGetCollectionQueryParamsOrdernameEnum = {
    asc: "asc",
    desc: "desc"
} as const;

export type ApiMeetsGetCollectionQueryParamsOrdernameEnumKey = (typeof apiMeetsGetCollectionQueryParamsOrdernameEnum)[keyof typeof apiMeetsGetCollectionQueryParamsOrdernameEnum];

export const apiMeetsGetCollectionQueryParamsOrderstatusEnum = {
    asc: "asc",
    desc: "desc"
} as const;

export type ApiMeetsGetCollectionQueryParamsOrderstatusEnumKey = (typeof apiMeetsGetCollectionQueryParamsOrderstatusEnum)[keyof typeof apiMeetsGetCollectionQueryParamsOrderstatusEnum];

export const apiMeetsGetCollectionQueryParamsOrdermeetStartAtEnum = {
    asc: "asc",
    desc: "desc"
} as const;

export type ApiMeetsGetCollectionQueryParamsOrdermeetStartAtEnumKey = (typeof apiMeetsGetCollectionQueryParamsOrdermeetStartAtEnum)[keyof typeof apiMeetsGetCollectionQueryParamsOrdermeetStartAtEnum];

export const apiMeetsGetCollectionQueryParamsOrdermeetEndAtEnum = {
    asc: "asc",
    desc: "desc"
} as const;

export type ApiMeetsGetCollectionQueryParamsOrdermeetEndAtEnumKey = (typeof apiMeetsGetCollectionQueryParamsOrdermeetEndAtEnum)[keyof typeof apiMeetsGetCollectionQueryParamsOrdermeetEndAtEnum];

export const apiMeetsGetCollectionQueryParamsOrderdateCreateEnum = {
    asc: "asc",
    desc: "desc"
} as const;

export type ApiMeetsGetCollectionQueryParamsOrderdateCreateEnumKey = (typeof apiMeetsGetCollectionQueryParamsOrderdateCreateEnum)[keyof typeof apiMeetsGetCollectionQueryParamsOrderdateCreateEnum];

export type ApiMeetsGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 100
     * @default 10
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[name]"?: ApiMeetsGetCollectionQueryParamsOrdernameEnumKey;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[status]"?: ApiMeetsGetCollectionQueryParamsOrderstatusEnumKey;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[meetStartAt]"?: ApiMeetsGetCollectionQueryParamsOrdermeetStartAtEnumKey;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[meetEndAt]"?: ApiMeetsGetCollectionQueryParamsOrdermeetEndAtEnumKey;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[dateCreate]"?: ApiMeetsGetCollectionQueryParamsOrderdateCreateEnumKey;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined
    */
    "meetStartAt[before]"?: string;
    /**
     * @type string | undefined
    */
    "meetStartAt[strictly_before]"?: string;
    /**
     * @type string | undefined
    */
    "meetStartAt[after]"?: string;
    /**
     * @type string | undefined
    */
    "meetStartAt[strictly_after]"?: string;
    /**
     * @type string | undefined
    */
    "meetEndAt[before]"?: string;
    /**
     * @type string | undefined
    */
    "meetEndAt[strictly_before]"?: string;
    /**
     * @type string | undefined
    */
    "meetEndAt[after]"?: string;
    /**
     * @type string | undefined
    */
    "meetEndAt[strictly_after]"?: string;
};

/**
 * @description Meet collection
*/
export type ApiMeetsGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: MeetJsonldMeetReadCollection[];
});

/**
 * @description Forbidden
*/
export type ApiMeetsGetCollection403 = ErrorJsonld;

export type ApiMeetsGetCollectionQueryResponse = ApiMeetsGetCollection200;

export type ApiMeetsGetCollectionQuery = {
    Response: ApiMeetsGetCollection200;
    QueryParams: ApiMeetsGetCollectionQueryParams;
    Errors: ApiMeetsGetCollection403;
};