/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "../constraint-violation/jsonld";
import type { ErrorJsonld } from "../error/jsonld";
import type { MeetMeetUpdateJsonMergePatch } from "../meet-meet-update/json-merge-patch";
import type { MeetJsonldMeetUpdateRead } from "./jsonld-meet-update-read";

export type ApiMeetsIdPatchPathParams = {
    /**
     * @description Meet identifier
     * @type string
    */
    id: string;
};

/**
 * @description Meet resource updated
*/
export type ApiMeetsIdPatch200 = MeetJsonldMeetUpdateRead;

/**
 * @description Invalid input
*/
export type ApiMeetsIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiMeetsIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiMeetsIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiMeetsIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated Meet resource
*/
export type ApiMeetsIdPatchMutationRequest = MeetMeetUpdateJsonMergePatch;

export type ApiMeetsIdPatchMutationResponse = ApiMeetsIdPatch200;

export type ApiMeetsIdPatchMutation = {
    Response: ApiMeetsIdPatch200;
    Request: ApiMeetsIdPatchMutationRequest;
    PathParams: ApiMeetsIdPatchPathParams;
    Errors: ApiMeetsIdPatch400 | ApiMeetsIdPatch403 | ApiMeetsIdPatch404 | ApiMeetsIdPatch422;
};