/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "../constraint-violation/jsonld";
import type { ErrorJsonld } from "../error/jsonld";
import type { MeetConsumeTokenDtoReportIntegrationErrorRequestJsonMergePatch } from "./consume-token-dto-report-integration-error-request/json-merge-patch";
import type { MeetConsumeTokenDtoJsonldReportIntegrationErrorResponse } from "./consume-token-dto/jsonld-report-integration-error-response";

/**
 * @description Meet resource updated
*/
export type ApiTokensConsumePatch200 = MeetConsumeTokenDtoJsonldReportIntegrationErrorResponse;

/**
 * @description Invalid input
*/
export type ApiTokensConsumePatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiTokensConsumePatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTokensConsumePatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiTokensConsumePatch422 = ConstraintViolationJsonld;

/**
 * @description The updated Meet resource
*/
export type ApiTokensConsumePatchMutationRequest = MeetConsumeTokenDtoReportIntegrationErrorRequestJsonMergePatch;

export type ApiTokensConsumePatchMutationResponse = ApiTokensConsumePatch200;

export type ApiTokensConsumePatchMutation = {
    Response: ApiTokensConsumePatch200;
    Request: ApiTokensConsumePatchMutationRequest;
    Errors: ApiTokensConsumePatch400 | ApiTokensConsumePatch403 | ApiTokensConsumePatch404 | ApiTokensConsumePatch422;
};