/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { MeetJsonldMeetReadItem } from "./jsonld-meet-read-item";

export type ApiMeetsIdGetPathParams = {
    /**
     * @description Meet identifier
     * @type string
    */
    id: string;
};

/**
 * @description Meet resource
*/
export type ApiMeetsIdGet200 = MeetJsonldMeetReadItem;

/**
 * @description Forbidden
*/
export type ApiMeetsIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiMeetsIdGet404 = ErrorJsonld;

export type ApiMeetsIdGetQueryResponse = ApiMeetsIdGet200;

export type ApiMeetsIdGetQuery = {
    Response: ApiMeetsIdGet200;
    PathParams: ApiMeetsIdGetPathParams;
    Errors: ApiMeetsIdGet403 | ApiMeetsIdGet404;
};