/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "../constraint-violation/jsonld";
import type { ErrorJsonld } from "../error/jsonld";
import type { MeetJsonld } from "./jsonld";
import type { MeetMeetRequestDtoJsonMergePatch } from "./meet-request-dto/json-merge-patch";

export type ApiMeetsIdtranscribePatchPathParams = {
    /**
     * @description Meet identifier
     * @type string
    */
    id: string;
};

/**
 * @description Meet resource updated
*/
export type ApiMeetsIdtranscribePatch200 = MeetJsonld;

/**
 * @description Invalid input
*/
export type ApiMeetsIdtranscribePatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiMeetsIdtranscribePatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiMeetsIdtranscribePatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiMeetsIdtranscribePatch422 = ConstraintViolationJsonld;

/**
 * @description The updated Meet resource
*/
export type ApiMeetsIdtranscribePatchMutationRequest = MeetMeetRequestDtoJsonMergePatch;

export type ApiMeetsIdtranscribePatchMutationResponse = ApiMeetsIdtranscribePatch200;

export type ApiMeetsIdtranscribePatchMutation = {
    Response: ApiMeetsIdtranscribePatch200;
    Request: ApiMeetsIdtranscribePatchMutationRequest;
    PathParams: ApiMeetsIdtranscribePatchPathParams;
    Errors: ApiMeetsIdtranscribePatch400 | ApiMeetsIdtranscribePatch403 | ApiMeetsIdtranscribePatch404 | ApiMeetsIdtranscribePatch422;
};