/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "../constraint-violation/jsonld";
import type { ErrorJsonld } from "../error/jsonld";
import type { MeetJsonld } from "./jsonld";
import type { MeetMeetRequestDtoJsonMergePatch } from "./meet-request-dto/json-merge-patch";

export type ApiMeetsIdsummaryPatchPathParams = {
    /**
     * @description Meet identifier
     * @type string
    */
    id: string;
};

/**
 * @description Meet resource updated
*/
export type ApiMeetsIdsummaryPatch200 = MeetJsonld;

/**
 * @description Invalid input
*/
export type ApiMeetsIdsummaryPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiMeetsIdsummaryPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiMeetsIdsummaryPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiMeetsIdsummaryPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated Meet resource
*/
export type ApiMeetsIdsummaryPatchMutationRequest = MeetMeetRequestDtoJsonMergePatch;

export type ApiMeetsIdsummaryPatchMutationResponse = ApiMeetsIdsummaryPatch200;

export type ApiMeetsIdsummaryPatchMutation = {
    Response: ApiMeetsIdsummaryPatch200;
    Request: ApiMeetsIdsummaryPatchMutationRequest;
    PathParams: ApiMeetsIdsummaryPatchPathParams;
    Errors: ApiMeetsIdsummaryPatch400 | ApiMeetsIdsummaryPatch403 | ApiMeetsIdsummaryPatch404 | ApiMeetsIdsummaryPatch422;
};