/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const meetFormDataStatusEnum = {
    FOUND: "FOUND",
    PREPARING: "PREPARING",
    TIME_CHANGED: "TIME_CHANGED",
    RECORDING: "RECORDING",
    RECORDING_PAUSED: "RECORDING_PAUSED",
    RECORDING_COMPLETED: "RECORDING_COMPLETED",
    UPLOADING: "UPLOADING",
    POSTPROCESSING: "POSTPROCESSING",
    EXTERNAL_UPLOAD: "EXTERNAL_UPLOAD",
    COMPLETED: "COMPLETED",
    ERROR: "ERROR",
    TRANSCRIBE: "TRANSCRIBE",
    TRANSCRIBE_COMPLETED: "TRANSCRIBE_COMPLETED",
    TRANSCRIBE_ERROR: "TRANSCRIBE_ERROR",
    SUMMARY: "SUMMARY",
    SUMMARY_COMPLETED: "SUMMARY_COMPLETED",
    SUMMARY_ERROR: "SUMMARY_ERROR"
} as const;

export type MeetFormDataStatusEnumKey = (typeof meetFormDataStatusEnum)[keyof typeof meetFormDataStatusEnum];

export type MeetFormData = {
    /**
     * @type string,null, iri-reference
    */
    integration?: string | null;
    /**
     * @type string | undefined
    */
    url?: string;
    /**
     * @type string,null
    */
    resultUrl?: string | null;
    /**
     * @type string,null
    */
    archiveUrl?: string | null;
    /**
     * @type string,null
    */
    name?: string | null;
    /**
     * @type string,null, iri-reference
    */
    recorder?: string | null;
    /**
     * @type string,null, date-time
    */
    meetStartAt?: string | null;
    /**
     * @type string,null, date-time
    */
    meetEndAt?: string | null;
    /**
     * @type string,null
    */
    icalUid?: string | null;
    /**
     * @type string,null
    */
    traceId?: string | null;
    /**
     * @type array,null
    */
    participants?: string[] | null;
    /**
     * @type array | undefined
    */
    statuses?: string[];
    /**
     * @default "FOUND"
     * @type string,null
    */
    status?: MeetFormDataStatusEnumKey | null;
    /**
     * @type string,null, iri-reference
    */
    user?: string | null;
    /**
     * @type string,null
    */
    token?: string | null;
    /**
     * @type string,null
    */
    videoLinkResult?: string | null;
    /**
     * @type string,null
    */
    transcriptionResult?: string | null;
    /**
     * @type string,null
    */
    summaryResult?: string | null;
    /**
     * @type string,null, iri-reference
    */
    providerConfig?: string | null;
    /**
     * @type string,null, iri-reference
    */
    storageConfig?: string | null;
    /**
     * @type string,null, iri-reference
    */
    recorderConfig?: string | null;
    /**
     * @type boolean,null
    */
    transcription?: boolean | null;
    /**
     * @type boolean,null
    */
    summarization?: boolean | null;
    /**
     * @default 0
     * @type integer | undefined
    */
    duration?: number;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined, date-time
    */
    readonly dateCreate?: string;
    /**
     * @type string,null, date-time
    */
    readonly dateUpdate?: string | null;
    /**
     * @type string,null, iri-reference
    */
    readonly owner?: string | null;
    /**
     * @type array | undefined
    */
    readonly roles?: string[];
    /**
     * @type string | undefined
    */
    readonly userIdentifier?: string;
};