/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { IntegrationHtmlMeetUpdateRead } from "../integration/html-meet-update-read";
import type { ProviderConfigHtmlMeetUpdateRead } from "../provider-config/html-meet-update-read";
import type { RecorderConfigHtmlMeetUpdateRead } from "../recorder-config/html-meet-update-read";
import type { StorageConfigHtmlMeetUpdateRead } from "../storage-config/html-meet-update-read";
import type { UserHtmlMeetUpdateRead } from "../user/html-meet-update-read";

export const meetHtmlMeetUpdateReadStatusEnum = {
    FOUND: "FOUND",
    PREPARING: "PREPARING",
    TIME_CHANGED: "TIME_CHANGED",
    RECORDING: "RECORDING",
    RECORDING_PAUSED: "RECORDING_PAUSED",
    RECORDING_COMPLETED: "RECORDING_COMPLETED",
    UPLOADING: "UPLOADING",
    POSTPROCESSING: "POSTPROCESSING",
    EXTERNAL_UPLOAD: "EXTERNAL_UPLOAD",
    COMPLETED: "COMPLETED",
    ERROR: "ERROR",
    TRANSCRIBE: "TRANSCRIBE",
    TRANSCRIBE_COMPLETED: "TRANSCRIBE_COMPLETED",
    TRANSCRIBE_ERROR: "TRANSCRIBE_ERROR",
    SUMMARY: "SUMMARY",
    SUMMARY_COMPLETED: "SUMMARY_COMPLETED",
    SUMMARY_ERROR: "SUMMARY_ERROR"
} as const;

export type MeetHtmlMeetUpdateReadStatusEnumKey = (typeof meetHtmlMeetUpdateReadStatusEnum)[keyof typeof meetHtmlMeetUpdateReadStatusEnum];

export type MeetHtmlMeetUpdateRead = {
    integration?: (IntegrationHtmlMeetUpdateRead | null);
    /**
     * @type string | undefined
    */
    url?: string;
    /**
     * @type string,null
    */
    resultUrl?: string | null;
    /**
     * @type string,null
    */
    archiveUrl?: string | null;
    /**
     * @type string,null
    */
    name?: string | null;
    /**
     * @type string,null, iri-reference
    */
    recorder?: string | null;
    /**
     * @type string,null, date-time
    */
    meetStartAt?: string | null;
    /**
     * @type string,null, date-time
    */
    meetEndAt?: string | null;
    /**
     * @type string,null
    */
    icalUid?: string | null;
    /**
     * @type string,null
    */
    traceId?: string | null;
    /**
     * @type array,null
    */
    participants?: string[] | null;
    /**
     * @default "FOUND"
     * @type string,null
    */
    status?: MeetHtmlMeetUpdateReadStatusEnumKey | null;
    user?: (UserHtmlMeetUpdateRead | null);
    /**
     * @type string,null
    */
    videoLinkResult?: string | null;
    /**
     * @type string,null
    */
    transcriptionResult?: string | null;
    /**
     * @type string,null
    */
    summaryResult?: string | null;
    providerConfig?: (ProviderConfigHtmlMeetUpdateRead | null);
    storageConfig?: (StorageConfigHtmlMeetUpdateRead | null);
    recorderConfig?: (RecorderConfigHtmlMeetUpdateRead | null);
    /**
     * @type boolean,null
    */
    transcription?: boolean | null;
    /**
     * @type boolean,null
    */
    summarization?: boolean | null;
    /**
     * @default 0
     * @type integer | undefined
    */
    duration?: number;
};