/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";
import type { IntegrationJsonldMeetCreateRead } from "../integration/jsonld-meet-create-read";
import type { ProviderConfigJsonldMeetCreateRead } from "../provider-config/jsonld-meet-create-read";
import type { RecorderConfigJsonldMeetCreateRead } from "../recorder-config/jsonld-meet-create-read";
import type { RecorderJsonldMeetCreateRead } from "../recorder/jsonld-meet-create-read";
import type { StorageConfigJsonldMeetCreateRead } from "../storage-config/jsonld-meet-create-read";
import type { UserJsonldMeetCreateRead } from "../user/jsonld-meet-create-read";

export const meetJsonldMeetCreateReadStatusEnum = {
    FOUND: "FOUND",
    PREPARING: "PREPARING",
    TIME_CHANGED: "TIME_CHANGED",
    RECORDING: "RECORDING",
    RECORDING_PAUSED: "RECORDING_PAUSED",
    RECORDING_COMPLETED: "RECORDING_COMPLETED",
    UPLOADING: "UPLOADING",
    POSTPROCESSING: "POSTPROCESSING",
    EXTERNAL_UPLOAD: "EXTERNAL_UPLOAD",
    COMPLETED: "COMPLETED",
    ERROR: "ERROR",
    TRANSCRIBE: "TRANSCRIBE",
    TRANSCRIBE_COMPLETED: "TRANSCRIBE_COMPLETED",
    TRANSCRIBE_ERROR: "TRANSCRIBE_ERROR",
    SUMMARY: "SUMMARY",
    SUMMARY_COMPLETED: "SUMMARY_COMPLETED",
    SUMMARY_ERROR: "SUMMARY_ERROR"
} as const;

export type MeetJsonldMeetCreateReadStatusEnumKey = (typeof meetJsonldMeetCreateReadStatusEnum)[keyof typeof meetJsonldMeetCreateReadStatusEnum];

export type MeetJsonldMeetCreateRead = (HydraItemBaseSchema & {
    integration?: (IntegrationJsonldMeetCreateRead | null);
    /**
     * @type string | undefined
    */
    url?: string;
    /**
     * @type string,null
    */
    resultUrl?: string | null;
    /**
     * @type string,null
    */
    archiveUrl?: string | null;
    /**
     * @type string,null
    */
    name?: string | null;
    recorder?: (RecorderJsonldMeetCreateRead | null);
    /**
     * @type string,null, date-time
    */
    meetStartAt?: string | null;
    /**
     * @type string,null, date-time
    */
    meetEndAt?: string | null;
    /**
     * @type string,null
    */
    icalUid?: string | null;
    /**
     * @type string,null
    */
    traceId?: string | null;
    /**
     * @type array,null
    */
    participants?: string[] | null;
    /**
     * @default "FOUND"
     * @type string,null
    */
    status?: MeetJsonldMeetCreateReadStatusEnumKey | null;
    user?: (UserJsonldMeetCreateRead | null);
    /**
     * @type string,null
    */
    token?: string | null;
    /**
     * @type string,null
    */
    videoLinkResult?: string | null;
    /**
     * @type string,null
    */
    transcriptionResult?: string | null;
    /**
     * @type string,null
    */
    summaryResult?: string | null;
    providerConfig?: (ProviderConfigJsonldMeetCreateRead | null);
    storageConfig?: (StorageConfigJsonldMeetCreateRead | null);
    recorderConfig?: (RecorderConfigJsonldMeetCreateRead | null);
    /**
     * @type boolean,null
    */
    transcription?: boolean | null;
    /**
     * @type boolean,null
    */
    summarization?: boolean | null;
    /**
     * @default 0
     * @type integer | undefined
    */
    duration?: number;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});