/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyValueFormDataStorageConfigDetailGetId } from "../../property-value/form-data-storage-config/detail-get-id";
import type { StorageFormDataStorageConfigDetailGetId } from "../../storage/form-data-storage-config/detail-get-id";

export type StorageConfigFormDataStorageConfigDetailGetId = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type object
    */
    storage: StorageFormDataStorageConfigDetailGetId;
    /**
     * @type array
    */
    propertyValues: PropertyValueFormDataStorageConfigDetailGetId[];
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};