/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StorageFormDataStorageConfigListGetId } from "../../storage/form-data-storage-config/list-get-id";

export type StorageConfigFormDataStorageConfigListGetId = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type object
    */
    storage: StorageFormDataStorageConfigListGetId;
    /**
     * @default false
     * @type boolean | undefined
    */
    isGlobal?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};