/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "../constraint-violation/jsonld";
import type { ErrorJsonld } from "../error/jsonld";
import type { QuestionQuestionCreate } from "../question-question-create";
import type { QuestionJsonldQuestionPostCreate } from "./jsonld-question-post-create";

export type ApiRecorderConfigsIdquestionPostPathParams = {
    /**
     * @description Question identifier
     * @type string
    */
    id: string;
};

/**
 * @description Question resource created
*/
export type ApiRecorderConfigsIdquestionPost201 = QuestionJsonldQuestionPostCreate;

/**
 * @description Invalid input
*/
export type ApiRecorderConfigsIdquestionPost400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiRecorderConfigsIdquestionPost403 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiRecorderConfigsIdquestionPost422 = ConstraintViolationJsonld;

/**
 * @description The new Question resource
*/
export type ApiRecorderConfigsIdquestionPostMutationRequest = QuestionQuestionCreate;

export type ApiRecorderConfigsIdquestionPostMutationResponse = ApiRecorderConfigsIdquestionPost201;

export type ApiRecorderConfigsIdquestionPostMutation = {
    Response: ApiRecorderConfigsIdquestionPost201;
    Request: ApiRecorderConfigsIdquestionPostMutationRequest;
    PathParams: ApiRecorderConfigsIdquestionPostPathParams;
    Errors: ApiRecorderConfigsIdquestionPost400 | ApiRecorderConfigsIdquestionPost403 | ApiRecorderConfigsIdquestionPost422;
};