/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { QuestionJsonldQuestionReadItem } from "./jsonld-question-read-item";

export type ApiQuestionsIdGetPathParams = {
    /**
     * @description Question identifier
     * @type string
    */
    id: string;
};

/**
 * @description Question resource
*/
export type ApiQuestionsIdGet200 = QuestionJsonldQuestionReadItem;

/**
 * @description Forbidden
*/
export type ApiQuestionsIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiQuestionsIdGet404 = ErrorJsonld;

export type ApiQuestionsIdGetQueryResponse = ApiQuestionsIdGet200;

export type ApiQuestionsIdGetQuery = {
    Response: ApiQuestionsIdGet200;
    PathParams: ApiQuestionsIdGetPathParams;
    Errors: ApiQuestionsIdGet403 | ApiQuestionsIdGet404;
};