/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";

export type QuestionJsonldQuestionReadCollection = (HydraItemBaseSchema & {
    /**
     * @description Текст вопроса
     * @type string
    */
    text: string;
    /**
     * @description Файл
     * @type string,null, iri-reference
    */
    file?: string | null;
    /**
     * @description Текст вопроса
     * @type string,null
    */
    answer?: string | null;
    /**
     * @description Ответ на вопрос
     * @type boolean | undefined
    */
    isRequireAnswer?: boolean;
    /**
     * @description Требует ли вопрос ответа
     * @type string | undefined, iri-reference
    */
    recorderConfig?: string;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});