/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "../constraint-violation/jsonld";
import type { ErrorJsonld } from "../error/jsonld";
import type { RecorderConfigRecorderConfigupdateStatusJsonMergePatch } from "../recorder-config-recorder-configupdate-status/json-merge-patch";
import type { RecorderConfigJsonldRecorderConfigReadItem } from "./jsonld-recorder-config-read-item";

export type ApiRecorderConfigsIdstatusPatchPathParams = {
    /**
     * @description RecorderConfig identifier
     * @type string
    */
    id: string;
};

/**
 * @description RecorderConfig resource updated
*/
export type ApiRecorderConfigsIdstatusPatch200 = RecorderConfigJsonldRecorderConfigReadItem;

/**
 * @description Invalid input
*/
export type ApiRecorderConfigsIdstatusPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiRecorderConfigsIdstatusPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiRecorderConfigsIdstatusPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiRecorderConfigsIdstatusPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated RecorderConfig resource
*/
export type ApiRecorderConfigsIdstatusPatchMutationRequest = RecorderConfigRecorderConfigupdateStatusJsonMergePatch;

export type ApiRecorderConfigsIdstatusPatchMutationResponse = ApiRecorderConfigsIdstatusPatch200;

export type ApiRecorderConfigsIdstatusPatchMutation = {
    Response: ApiRecorderConfigsIdstatusPatch200;
    Request: ApiRecorderConfigsIdstatusPatchMutationRequest;
    PathParams: ApiRecorderConfigsIdstatusPatchPathParams;
    Errors: ApiRecorderConfigsIdstatusPatch400 | ApiRecorderConfigsIdstatusPatch403 | ApiRecorderConfigsIdstatusPatch404 | ApiRecorderConfigsIdstatusPatch422;
};