/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";

export type ApiRecorderConfigsIdDeletePathParams = {
    /**
     * @description RecorderConfig identifier
     * @type string
    */
    id: string;
};

/**
 * @description RecorderConfig resource deleted
*/
export type ApiRecorderConfigsIdDelete204 = any;

/**
 * @description Forbidden
*/
export type ApiRecorderConfigsIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiRecorderConfigsIdDelete404 = ErrorJsonld;

export type ApiRecorderConfigsIdDeleteMutationResponse = ApiRecorderConfigsIdDelete204;

export type ApiRecorderConfigsIdDeleteMutation = {
    Response: ApiRecorderConfigsIdDelete204;
    PathParams: ApiRecorderConfigsIdDeletePathParams;
    Errors: ApiRecorderConfigsIdDelete403 | ApiRecorderConfigsIdDelete404;
};