/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RecorderFormDataGetCollectionIntegration } from "../recorder/form-data-get-collection-integration";

export type RecorderConfigFormDataGetCollectionIntegration = {
    /**
     * @type string
    */
    name: string;
    recorder: (RecorderFormDataGetCollectionIntegration | null);
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};