/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RecorderFormDataMeetReadItem } from "../recorder/form-data-meet-read-item";

export type RecorderConfigFormDataMeetReadItem = {
    /**
     * @type string
    */
    name: string;
    recorder: (RecorderFormDataMeetReadItem | null);
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};