/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RecorderFormDataGetObjIntegration } from "../recorder/form-data-get-obj-integration";

export type RecorderConfigFormDataGetObjIntegration = {
    /**
     * @type string
    */
    name: string;
    recorder: (RecorderFormDataGetObjIntegration | null);
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};