/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type RecorderConfigFormDataMeetUpdateRead = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type string,null, iri-reference
    */
    recorder: string | null;
};