/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RecorderHtmlMeetReadItem } from "../recorder/html-meet-read-item";

export type RecorderConfigHtmlMeetReadItem = {
    /**
     * @type string
    */
    name: string;
    recorder: (RecorderHtmlMeetReadItem | null);
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};