/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RecorderHtmlRecorderConfigCollectionRead } from "../recorder/html-recorder-config-collection-read";

export const recorderConfigHtmlRecorderConfigCollectionReadStatusEnum = {
    NOT_REQUIRE_AUTHORIZATION: "NOT_REQUIRE_AUTHORIZATION",
    WAITING_AUTHORIZATION: "WAITING_AUTHORIZATION",
    RECORDER_PROCESS_AUTHORIZATION: "RECORDER_PROCESS_AUTHORIZATION",
    ERROR_AUTHORIZATION: "ERROR_AUTHORIZATION",
    AUTHORIZED: "AUTHORIZED"
} as const;

export type RecorderConfigHtmlRecorderConfigCollectionReadStatusEnumKey = (typeof recorderConfigHtmlRecorderConfigCollectionReadStatusEnum)[keyof typeof recorderConfigHtmlRecorderConfigCollectionReadStatusEnum];

export type RecorderConfigHtmlRecorderConfigCollectionRead = {
    /**
     * @type string
    */
    name: string;
    /**
     * @default true
     * @type boolean
    */
    isActive: boolean;
    recorder: (RecorderHtmlRecorderConfigCollectionRead | null);
    /**
     * @description Статус
     * @default "NOT_REQUIRE_AUTHORIZATION"
     * @type string | undefined
    */
    status?: RecorderConfigHtmlRecorderConfigCollectionReadStatusEnumKey;
    /**
     * @default false
     * @type boolean | undefined
    */
    isGlobal?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};