/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RecorderHtmlGetObjIntegration } from "../recorder/html-get-obj-integration";

export type RecorderConfigHtmlGetObjIntegration = {
    /**
     * @type string
    */
    name: string;
    recorder: (RecorderHtmlGetObjIntegration | null);
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};