/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyValueHtmlRecorderConfigReadItem } from "../property-value/html-recorder-config-read-item";
import type { RecorderHtmlRecorderConfigReadItem } from "../recorder/html-recorder-config-read-item";

export const recorderConfigHtmlRecorderConfigReadItemStatusEnum = {
    NOT_REQUIRE_AUTHORIZATION: "NOT_REQUIRE_AUTHORIZATION",
    WAITING_AUTHORIZATION: "WAITING_AUTHORIZATION",
    RECORDER_PROCESS_AUTHORIZATION: "RECORDER_PROCESS_AUTHORIZATION",
    ERROR_AUTHORIZATION: "ERROR_AUTHORIZATION",
    AUTHORIZED: "AUTHORIZED"
} as const;

export type RecorderConfigHtmlRecorderConfigReadItemStatusEnumKey = (typeof recorderConfigHtmlRecorderConfigReadItemStatusEnum)[keyof typeof recorderConfigHtmlRecorderConfigReadItemStatusEnum];

export type RecorderConfigHtmlRecorderConfigReadItem = {
    /**
     * @type string
    */
    name: string;
    /**
     * @default true
     * @type boolean
    */
    isActive: boolean;
    recorder: (RecorderHtmlRecorderConfigReadItem | null);
    /**
     * @type array
    */
    propertyValues: PropertyValueHtmlRecorderConfigReadItem[];
    /**
     * @description Статус
     * @default "NOT_REQUIRE_AUTHORIZATION"
     * @type string | undefined
    */
    status?: RecorderConfigHtmlRecorderConfigReadItemStatusEnumKey;
    /**
     * @default false
     * @type boolean | undefined
    */
    isGlobal?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};