/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";
import type { RecorderJsonldGetCollectionIntegration } from "../recorder/jsonld-get-collection-integration";

export type RecorderConfigJsonldGetCollectionIntegration = (HydraItemBaseSchema & {
    /**
     * @type string
    */
    name: string;
    recorder: (RecorderJsonldGetCollectionIntegration | null);
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});