/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";
import type { RecorderJsonldMeetReadItem } from "../recorder/jsonld-meet-read-item";

export type RecorderConfigJsonldMeetReadItem = (HydraItemBaseSchema & {
    /**
     * @type string
    */
    name: string;
    recorder: (RecorderJsonldMeetReadItem | null);
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});