/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";
import type { RecorderJsonldRecorderConfigCollectionRead } from "../recorder/jsonld-recorder-config-collection-read";

export const recorderConfigJsonldRecorderConfigCollectionReadStatusEnum = {
    NOT_REQUIRE_AUTHORIZATION: "NOT_REQUIRE_AUTHORIZATION",
    WAITING_AUTHORIZATION: "WAITING_AUTHORIZATION",
    RECORDER_PROCESS_AUTHORIZATION: "RECORDER_PROCESS_AUTHORIZATION",
    ERROR_AUTHORIZATION: "ERROR_AUTHORIZATION",
    AUTHORIZED: "AUTHORIZED"
} as const;

export type RecorderConfigJsonldRecorderConfigCollectionReadStatusEnumKey = (typeof recorderConfigJsonldRecorderConfigCollectionReadStatusEnum)[keyof typeof recorderConfigJsonldRecorderConfigCollectionReadStatusEnum];

export type RecorderConfigJsonldRecorderConfigCollectionRead = (HydraItemBaseSchema & {
    /**
     * @type string
    */
    name: string;
    /**
     * @default true
     * @type boolean
    */
    isActive: boolean;
    recorder: (RecorderJsonldRecorderConfigCollectionRead | null);
    /**
     * @description Статус
     * @default "NOT_REQUIRE_AUTHORIZATION"
     * @type string | undefined
    */
    status?: RecorderConfigJsonldRecorderConfigCollectionReadStatusEnumKey;
    /**
     * @default false
     * @type boolean | undefined
    */
    isGlobal?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});