/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { HydraCollectionBaseSchema } from "../hydra-collection-base-schema";
import type { MeetStatusHistoryJsonld } from "./jsonld";

export type ApiMeetsIdhistoryStatusesGetCollectionPathParams = {
    /**
     * @description MeetStatusHistory identifier
     * @type string
    */
    id: string;
};

export const apiMeetsIdhistoryStatusesGetCollectionQueryParamsOrderstatusEnum = {
    asc: "asc",
    desc: "desc"
} as const;

export type ApiMeetsIdhistoryStatusesGetCollectionQueryParamsOrderstatusEnumKey = (typeof apiMeetsIdhistoryStatusesGetCollectionQueryParamsOrderstatusEnum)[keyof typeof apiMeetsIdhistoryStatusesGetCollectionQueryParamsOrderstatusEnum];

export const apiMeetsIdhistoryStatusesGetCollectionQueryParamsOrderdateEnum = {
    asc: "asc",
    desc: "desc"
} as const;

export type ApiMeetsIdhistoryStatusesGetCollectionQueryParamsOrderdateEnumKey = (typeof apiMeetsIdhistoryStatusesGetCollectionQueryParamsOrderdateEnum)[keyof typeof apiMeetsIdhistoryStatusesGetCollectionQueryParamsOrderdateEnum];

export type ApiMeetsIdhistoryStatusesGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 100
     * @default 20
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[status]"?: ApiMeetsIdhistoryStatusesGetCollectionQueryParamsOrderstatusEnumKey;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[date]"?: ApiMeetsIdhistoryStatusesGetCollectionQueryParamsOrderdateEnumKey;
};

/**
 * @description MeetStatusHistory collection
*/
export type ApiMeetsIdhistoryStatusesGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: MeetStatusHistoryJsonld[];
});

/**
 * @description Forbidden
*/
export type ApiMeetsIdhistoryStatusesGetCollection403 = ErrorJsonld;

export type ApiMeetsIdhistoryStatusesGetCollectionQueryResponse = ApiMeetsIdhistoryStatusesGetCollection200;

export type ApiMeetsIdhistoryStatusesGetCollectionQuery = {
    Response: ApiMeetsIdhistoryStatusesGetCollection200;
    PathParams: ApiMeetsIdhistoryStatusesGetCollectionPathParams;
    QueryParams: ApiMeetsIdhistoryStatusesGetCollectionQueryParams;
    Errors: ApiMeetsIdhistoryStatusesGetCollection403;
};