/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiPaymentsGetCollectionQueryResponse, ApiPaymentsGetCollectionQueryParams } from "../../models";

function getApiPaymentsGetCollectionUrl() {
  return "/api/v1/payments" as const;
}
/**
 * @summary Retrieves the collection of Payment resources.
 * @description Retrieves the collection of Payment resources.
 * {@link /api/v1/payments}
 */
export const apiPaymentsGetCollection = (
  args: {
    query: ApiPaymentsGetCollectionQueryParams;
  },
  options?: RequestOptions,
): Promise<ApiPaymentsGetCollectionQueryResponse> => {
  return http.get(getApiPaymentsGetCollectionUrl(), {
    ...options,
    searchParams: args.query,
  }).json<ApiPaymentsGetCollectionQueryResponse>();
};