/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../../src/fixtures/http-client";
import type { ListUsersQueryResponse } from "../../models";

function getGetUsersUrl() {
  return "/users" as const;
}
/**
 * @summary List users
 * {@link /users}
 */
export const getUsers = (
  options?: RequestOptions,
): Promise<ListUsersQueryResponse> => {
  return http.get(getGetUsersUrl(), {
    ...options,
  }).json<ListUsersQueryResponse>();
};