/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { SubscriptionPlanSubscriptionPlanRequestDtoJsonMergePatchSchema } from "./subscription-plan-request-dto/json-merge-patch-schema";
import { SubscriptionPlanSubscriptionPlanResponseDtoJsonldSchema } from "./subscription-plan-response-dto/jsonld-schema";

export const ApiSubscriptionPlanIdpricePriceIdbuyPatchPathParamsSchema = z.object({
    "id": z.string().describe("SubscriptionPlan identifier"),
"priceId": z.string().describe("SubscriptionPlan identifier")
    })

/**
 * @description SubscriptionPlan resource updated
 */
export const ApiSubscriptionPlanIdpricePriceIdbuyPatch200Schema = z.lazy(() => SubscriptionPlanSubscriptionPlanResponseDtoJsonldSchema)

/**
 * @description Invalid input
 */
export const ApiSubscriptionPlanIdpricePriceIdbuyPatch400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiSubscriptionPlanIdpricePriceIdbuyPatch403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiSubscriptionPlanIdpricePriceIdbuyPatch404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiSubscriptionPlanIdpricePriceIdbuyPatch422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated SubscriptionPlan resource
 */
export const ApiSubscriptionPlanIdpricePriceIdbuyPatchMutationRequestSchema = z.lazy(() => SubscriptionPlanSubscriptionPlanRequestDtoJsonMergePatchSchema).schema.omit({ 'free': true })

export const ApiSubscriptionPlanIdpricePriceIdbuyPatchMutationResponseSchema = z.lazy(() => ApiSubscriptionPlanIdpricePriceIdbuyPatch200Schema)