/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { PriceFormDataGetCollectionSubscriptionPlanSchema } from "../price/form-data-get-collection-subscription-plan-schema";
import { ProductFormDataGetCollectionSubscriptionPlanSchema } from "../product/form-data-get-collection-subscription-plan-schema";
import { SubscriptionFeatureFormDataGetCollectionSubscriptionPlanSchema } from "../subscription-feature/form-data-get-collection-subscription-plan-schema";

export const SubscriptionPlanFormDataGetCollectionSubscriptionPlanSchema = z.object({
    "features": z.optional(z.array(z.lazy(() => SubscriptionFeatureFormDataGetCollectionSubscriptionPlanSchema))),
"public": z.optional(z.boolean().default(false)),
"name": z.optional(z.string()),
"free": z.optional(z.boolean().default(false)),
"userCount": z.optional(z.number().int().default(1)),
"prices": z.optional(z.array(z.lazy(() => PriceFormDataGetCollectionSubscriptionPlanSchema))),
"product": z.optional(z.union([z.lazy(() => ProductFormDataGetCollectionSubscriptionPlanSchema), z.null()])),
"id": z.optional(z.string())
    })