/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { PriceHtmlGetCollectionSubscriptionPlanSchema } from "../price/html-get-collection-subscription-plan-schema";
import { ProductHtmlGetCollectionSubscriptionPlanSchema } from "../product/html-get-collection-subscription-plan-schema";
import { SubscriptionFeatureHtmlGetCollectionSubscriptionPlanSchema } from "../subscription-feature/html-get-collection-subscription-plan-schema";

export const SubscriptionPlanHtmlGetCollectionSubscriptionPlanSchema = z.object({
    "features": z.optional(z.array(z.lazy(() => SubscriptionFeatureHtmlGetCollectionSubscriptionPlanSchema))),
"public": z.optional(z.boolean().default(false)),
"name": z.optional(z.string()),
"free": z.optional(z.boolean().default(false)),
"userCount": z.optional(z.number().int().default(1)),
"prices": z.optional(z.array(z.lazy(() => PriceHtmlGetCollectionSubscriptionPlanSchema))),
"product": z.optional(z.union([z.lazy(() => ProductHtmlGetCollectionSubscriptionPlanSchema), z.null()])),
"id": z.optional(z.string())
    })