/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiMeetsIdhistoryStatusesGetCollectionQueryResponse, ApiMeetsIdhistoryStatusesGetCollectionPathParams, ApiMeetsIdhistoryStatusesGetCollectionQueryParams } from "../../models";

function getApiMeetsIdhistoryStatusesGetCollectionUrl(params: ApiMeetsIdhistoryStatusesGetCollectionPathParams) {
  return `/api/v1/meets/${encodeURIComponent(String(params.id))}/history_statuses` as const;
}
/**
 * @summary Retrieves the collection of MeetStatusHistory resources.
 * @description Retrieves the collection of MeetStatusHistory resources.
 * {@link /api/v1/meets/{id}/history_statuses}
 */
export const apiMeetsIdhistoryStatusesGetCollection = (
  args: {
    params: ApiMeetsIdhistoryStatusesGetCollectionPathParams;
    query: ApiMeetsIdhistoryStatusesGetCollectionQueryParams;
  },
  options?: RequestOptions,
): Promise<ApiMeetsIdhistoryStatusesGetCollectionQueryResponse> => {
  return http.get(getApiMeetsIdhistoryStatusesGetCollectionUrl(args.params), {
    ...options,
    searchParams: args.query,
  }).json<ApiMeetsIdhistoryStatusesGetCollectionQueryResponse>();
};