/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";

export type ApiIntegrationsIdDeletePathParams = {
    /**
     * @description Integration identifier
     * @type string
    */
    id: string;
};

/**
 * @description Integration resource deleted
*/
export type ApiIntegrationsIdDelete204 = any;

/**
 * @description Forbidden
*/
export type ApiIntegrationsIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiIntegrationsIdDelete404 = ErrorJsonld;

export type ApiIntegrationsIdDeleteMutationResponse = ApiIntegrationsIdDelete204;

export type ApiIntegrationsIdDeleteMutation = {
    Response: ApiIntegrationsIdDelete204;
    PathParams: ApiIntegrationsIdDeletePathParams;
    Errors: ApiIntegrationsIdDelete403 | ApiIntegrationsIdDelete404;
};