/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type IntegrationFormDataMeetCreateRead = {
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined
    */
    readonly name?: string;
};