/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProviderConfigHtmlMeetReadItem } from "../provider-config/html-meet-read-item";
import type { RecorderConfigHtmlMeetReadItem } from "../recorder-config/html-meet-read-item";
import type { StorageConfigHtmlMeetReadItem } from "../storage-config/html-meet-read-item";

export type IntegrationHtmlMeetReadItem = {
    /**
     * @type object
    */
    providerConfig: ProviderConfigHtmlMeetReadItem;
    /**
     * @type object
    */
    recorderConfig: RecorderConfigHtmlMeetReadItem;
    /**
     * @type object
    */
    storageConfig: StorageConfigHtmlMeetReadItem;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined
    */
    readonly name?: string;
};