/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProviderConfigHtmlGetObjIntegration } from "../provider-config/html-get-obj-integration";
import type { RecorderConfigHtmlGetObjIntegration } from "../recorder-config/html-get-obj-integration";
import type { StorageConfigHtmlGetObjIntegration } from "../storage-config/html-get-obj-integration";

export type IntegrationHtmlGetObjIntegration = {
    /**
     * @type object
    */
    providerConfig: ProviderConfigHtmlGetObjIntegration;
    /**
     * @type object
    */
    recorderConfig: RecorderConfigHtmlGetObjIntegration;
    /**
     * @type object
    */
    storageConfig: StorageConfigHtmlGetObjIntegration;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};