/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";
import type { ProviderConfigJsonldGetCollectionIntegration } from "../provider-config/jsonld-get-collection-integration";
import type { RecorderConfigJsonldGetCollectionIntegration } from "../recorder-config/jsonld-get-collection-integration";
import type { StorageConfigJsonldGetCollectionIntegration } from "../storage-config/jsonld-get-collection-integration";

export type IntegrationJsonldGetCollectionIntegration = (HydraItemBaseSchema & {
    providerConfig: ProviderConfigJsonldGetCollectionIntegration;
    recorderConfig: RecorderConfigJsonldGetCollectionIntegration;
    storageConfig: StorageConfigJsonldGetCollectionIntegration;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});