/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";

export type IntegrationJsonldMeetUpdateRead = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    readonly name?: string;
});