/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../../hydra-item-base-schema";

export type AuthTokenDtoJsonld = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    accessToken?: string;
    /**
     * @type string | undefined
    */
    refreshToken?: string;
});