/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { TenantJsonldGetCurrentTenantSchema } from "./jsonld-get-current-tenant-schema";

/**
 * @description Tenant resource
 */
export const ApiCurrentTenantGet200Schema = z.lazy(() => TenantJsonldGetCurrentTenantSchema)

/**
 * @description Forbidden
 */
export const ApiCurrentTenantGet403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiCurrentTenantGet404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiCurrentTenantGetQueryResponseSchema = z.lazy(() => ApiCurrentTenantGet200Schema)