/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { AddressFormDataGetCurrentTenantSchema } from "../address/form-data-get-current-tenant-schema";

export const TenantFormDataGetCurrentTenantSchema = z.object({
    "id": z.optional(z.string()),
"name": z.string().nullish(),
"subdomain": z.optional(z.string()),
"tenantType": z.optional(z.enum(["company", "person"])),
"billingAddress": z.optional(z.lazy(() => AddressFormDataGetCurrentTenantSchema))
    })