/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { AddressJsonldGetCurrentTenantSchema } from "../address/jsonld-get-current-tenant-schema";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";

export const TenantJsonldGetCurrentTenantSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "id": z.optional(z.string()),
"name": z.string().nullish(),
"subdomain": z.optional(z.string()),
"tenantType": z.optional(z.enum(["company", "person"])),
"billingAddress": z.optional(z.lazy(() => AddressJsonldGetCurrentTenantSchema))
    }))