/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";

export const TenantJsonldGetItemPaymentSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "billingEmail": z.string().email()
    }))