/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const StorageConfigStorageConfigUpdateJsonMergePatchSchema = z.object({
    "name": z.optional(z.string()),
"storage": z.optional(z.string())
    })