/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiProvidersIdpropertiesGetCollectionQueryResponse, ApiProvidersIdpropertiesGetCollection403 } from "../../models/property/api-providers-idproperties-get-collection";
import { http } from "msw";

export function ApiProvidersIdpropertiesGetCollectionHandlerResponse200(data: ApiProvidersIdpropertiesGetCollectionQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiProvidersIdpropertiesGetCollectionHandlerResponse403(data: ApiProvidersIdpropertiesGetCollection403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiProvidersIdpropertiesGetCollectionHandler(data?: ApiProvidersIdpropertiesGetCollectionQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/v1/providers/:id/properties`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}