/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiPropertiesGetCollectionQueryResponse } from "../../models/property/api-properties-get-collection";
import { http } from "msw";

export function ApiPropertiesGetCollectionHandlerResponse200(data: ApiPropertiesGetCollectionQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiPropertiesGetCollectionHandler(data?: ApiPropertiesGetCollectionQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/v1/properties`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}