/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { PropertyHtmlProviderConfigItemReadSchema } from "../property/html-provider-config-item-read-schema";

export const PropertyValueHtmlProviderConfigItemReadSchema = z.object({
    "value": z.string().nullish(),
"property": z.lazy(() => PropertyHtmlProviderConfigItemReadSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })