/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { PropertyHtmlRecorderConfigReadItemSchema } from "../property/html-recorder-config-read-item-schema";

export const PropertyValueHtmlRecorderConfigReadItemSchema = z.object({
    "value": z.string().nullish(),
"property": z.lazy(() => PropertyHtmlRecorderConfigReadItemSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })