/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";
import { PropertyJsonldProviderConfigItemReadSchema } from "../property/jsonld-provider-config-item-read-schema";

export const PropertyValueJsonldProviderConfigItemReadSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "value": z.string().nullish(),
"property": z.lazy(() => PropertyJsonldProviderConfigItemReadSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    }))