/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { TokenApiTokenResponseDtoJsonldSchema } from "./api-token-response-dto/jsonld-schema";

/**
 * @description Token resource
 */
export const ApiApiTokenGet200Schema = z.lazy(() => TokenApiTokenResponseDtoJsonldSchema)

/**
 * @description Forbidden
 */
export const ApiApiTokenGet403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiApiTokenGet404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiApiTokenGetQueryResponseSchema = z.lazy(() => ApiApiTokenGet200Schema)