/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { TokenTokenCurrentResponseDtoJsonldTokenCurrentResponseSchema } from "./token-current-response-dto/jsonld-token-current-response-schema";

/**
 * @description Token resource
 */
export const ApiCurrentTokenGet200Schema = z.lazy(() => TokenTokenCurrentResponseDtoJsonldTokenCurrentResponseSchema).describe("Возвращает текущие access и refresh токены пользователя")

/**
 * @description Forbidden
 */
export const ApiCurrentTokenGet403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiCurrentTokenGet404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiCurrentTokenGetQueryResponseSchema = z.lazy(() => ApiCurrentTokenGet200Schema)