/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiPricesIdGetQueryResponse, ApiPricesIdGet403, ApiPricesIdGet404 } from "../../models/price/api-prices-id-get";
import { http } from "msw";

export function ApiPricesIdGetHandlerResponse200(data: ApiPricesIdGetQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiPricesIdGetHandlerResponse403(data: ApiPricesIdGet403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiPricesIdGetHandlerResponse404(data: ApiPricesIdGet404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiPricesIdGetHandler(data?: ApiPricesIdGetQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/v1/prices/:id`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}