/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { PropertyValueStorageConfigCreateJsonMergePatchSchema } from "../property-value-storage-config/create/json-merge-patch-schema";

export const StorageConfigStorageConfigCreateSchema = z.object({
    "name": z.string(),
"storage": z.string(),
"propertyValues": z.array(z.lazy(() => PropertyValueStorageConfigCreateJsonMergePatchSchema))
    })