/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { StorageStorageConfigListGetIdSchema } from "../storage-storage-config/list-get-id-schema";

export const StorageConfigStorageConfigListGetIdSchema = z.object({
    "name": z.string(),
"storage": z.lazy(() => StorageStorageConfigListGetIdSchema),
"isGlobal": z.optional(z.boolean().default(false)),
"id": z.optional(z.union([z.string(), z.string()]))
    })