/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyFormDataStorageItemReadGetIdPropertyRead } from "../../../../property/form-data-storage/item/read-get-id-property/read";

export type StorageFormDataStorageItemReadGetIdPropertyRead = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @type array | undefined
    */
    properties?: PropertyFormDataStorageItemReadGetIdPropertyRead[];
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};