/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiCorereportErrorPostMutationResponse, ApiCorereportErrorPost400, ApiCorereportErrorPost422 } from "../../models/core/api-corereport-error-post";
import { http } from "msw";

export function ApiCorereportErrorPostHandlerResponse201(data: ApiCorereportErrorPostMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiCorereportErrorPostHandlerResponse400(data: ApiCorereportErrorPost400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiCorereportErrorPostHandlerResponse422(data: ApiCorereportErrorPost422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiCorereportErrorPostHandler(data?: ApiCorereportErrorPostMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.post(`/api/v1/core/report-error`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}