/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../../../../hydra-item-base-schema-schema";
import { PropertyJsonldStorageItemReadGetIdPropertyReadSchema } from "../../../../property/jsonld-storage/item/read-get-id-property/read-schema";

export const StorageJsonldStorageItemReadGetIdPropertyReadSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "name": z.optional(z.string()),
"slug": z.string().nullish(),
"properties": z.optional(z.array(z.lazy(() => PropertyJsonldStorageItemReadGetIdPropertyReadSchema))),
"id": z.optional(z.union([z.string(), z.string()]))
    }))