/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiProductsGetCollectionQueryResponse, ApiProductsGetCollection403 } from "../../models/product/api-products-get-collection";
import { http } from "msw";

export function ApiProductsGetCollectionHandlerResponse200(data: ApiProductsGetCollectionQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiProductsGetCollectionHandlerResponse403(data: ApiProductsGetCollection403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiProductsGetCollectionHandler(data?: ApiProductsGetCollectionQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/v1/products`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}