/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const coreIntegrationErrorDtoReportIntegrationErrorRequestSourceEnum = {
    provider: "provider",
    recorder: "recorder",
    storage: "storage"
} as const;

export type CoreIntegrationErrorDtoReportIntegrationErrorRequestSourceEnumKey = (typeof coreIntegrationErrorDtoReportIntegrationErrorRequestSourceEnum)[keyof typeof coreIntegrationErrorDtoReportIntegrationErrorRequestSourceEnum];

export type CoreIntegrationErrorDtoReportIntegrationErrorRequest = {
    /**
     * @type string
    */
    source: CoreIntegrationErrorDtoReportIntegrationErrorRequestSourceEnumKey;
    /**
     * @type string
    */
    message: string;
    /**
     * @type array,null
    */
    payload?: string[] | null;
    /**
     * @type string,null, iri-reference
    */
    recorderConfig?: string | null;
};