/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CoreReportIntegrationErrorResponseDtoReportIntegrationErrorResponse = {
    /**
     * @type string | undefined
    */
    status?: string;
    /**
     * @type string | undefined, ulid
    */
    errorId?: string;
};