/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type SubscriptionPlanSubscriptionPlanResponseDtoFormData = {
    /**
     * @type string | undefined
    */
    paymentUrl?: string;
};