/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiSubscriptionPlansGetCollectionQueryResponse, ApiSubscriptionPlansGetCollectionQueryParams } from "../../models";

function getApiSubscriptionPlansGetCollectionUrl() {
  return "/api/v1/subscription_plans" as const;
}
/**
 * @summary Retrieves the collection of SubscriptionPlan resources.
 * @description Retrieves the collection of SubscriptionPlan resources.
 * {@link /api/v1/subscription_plans}
 */
export const apiSubscriptionPlansGetCollection = (
  args: {
    query: ApiSubscriptionPlansGetCollectionQueryParams;
  },
  options?: RequestOptions,
): Promise<ApiSubscriptionPlansGetCollectionQueryResponse> => {
  return http.get(getApiSubscriptionPlansGetCollectionUrl(), {
    ...options,
    searchParams: args.query,
  }).json<ApiSubscriptionPlansGetCollectionQueryResponse>();
};