/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiSubscriptionPlanIdpricePriceIdbuyPatchMutationResponse, ApiSubscriptionPlanIdpricePriceIdbuyPatchPathParams, ApiSubscriptionPlanIdpricePriceIdbuyPatchMutationRequest } from "../../models";

function getApiSubscriptionPlanIdpricePriceIdbuyPatchUrl(params: ApiSubscriptionPlanIdpricePriceIdbuyPatchPathParams) {
  return `/api/v1/subscription_plan/${encodeURIComponent(String(params.id))}/price/${encodeURIComponent(String(params.priceId))}/buy` as const;
}
/**
 * @summary Updates the SubscriptionPlan resource.
 * @description Updates the SubscriptionPlan resource.
 * {@link /api/v1/subscription_plan/{id}/price/{priceId}/buy}
 */
export const apiSubscriptionPlanIdpricePriceIdbuyPatch = (
  args: {
    params: ApiSubscriptionPlanIdpricePriceIdbuyPatchPathParams;
    body: ApiSubscriptionPlanIdpricePriceIdbuyPatchMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiSubscriptionPlanIdpricePriceIdbuyPatchMutationResponse> => {
  return http.patch(getApiSubscriptionPlanIdpricePriceIdbuyPatchUrl(args.params), {
    ...options,
    json: args.body,
  }).json<ApiSubscriptionPlanIdpricePriceIdbuyPatchMutationResponse>();
};