/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../../hydra-item-base-schema";

/**
 * @description Возвращает текущие access и refresh токены пользователя
*/
export type TokenTokenCurrentResponseDtoJsonldTokenCurrentResponse = (HydraItemBaseSchema & {
    /**
     * @type string,null
    */
    accessToken?: string | null;
    /**
     * @type string,null
    */
    refreshToken?: string | null;
});