/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiMediaTasksIdGetQueryResponse, ApiMediaTasksIdGetPathParams } from "../../models";

function getApiMediaTasksIdGetUrl(params: ApiMediaTasksIdGetPathParams) {
  return `/api/v1/media_tasks/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Retrieves a MediaTask resource.
 * @description Retrieves a MediaTask resource.
 * {@link /api/v1/media_tasks/{id}}
 */
export const apiMediaTasksIdGet = (
  args: {
    params: ApiMediaTasksIdGetPathParams;
  },
  options?: RequestOptions,
): Promise<ApiMediaTasksIdGetQueryResponse> => {
  return http.get(getApiMediaTasksIdGetUrl(args.params), {
    ...options,
  }).json<ApiMediaTasksIdGetQueryResponse>();
};