/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiMediaTasksIdsummaryPatchMutationResponse, ApiMediaTasksIdsummaryPatchPathParams, ApiMediaTasksIdsummaryPatchMutationRequest } from "../../models";

function getApiMediaTasksIdsummaryPatchUrl(params: ApiMediaTasksIdsummaryPatchPathParams) {
  return `/api/v1/media_tasks/${encodeURIComponent(String(params.id))}/summary` as const;
}
/**
 * @summary Updates the MediaTask resource.
 * @description Updates the MediaTask resource.
 * {@link /api/v1/media_tasks/{id}/summary}
 */
export const apiMediaTasksIdsummaryPatch = (
  args: {
    params: ApiMediaTasksIdsummaryPatchPathParams;
    body: ApiMediaTasksIdsummaryPatchMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiMediaTasksIdsummaryPatchMutationResponse> => {
  return http.patch(getApiMediaTasksIdsummaryPatchUrl(args.params), {
    ...options,
    json: args.body,
  }).json<ApiMediaTasksIdsummaryPatchMutationResponse>();
};