/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiMediaTasksIdtranscribePatchMutationResponse, ApiMediaTasksIdtranscribePatchPathParams, ApiMediaTasksIdtranscribePatchMutationRequest } from "../../models";

function getApiMediaTasksIdtranscribePatchUrl(params: ApiMediaTasksIdtranscribePatchPathParams) {
  return `/api/v1/media_tasks/${encodeURIComponent(String(params.id))}/transcribe` as const;
}
/**
 * @summary Updates the MediaTask resource.
 * @description Updates the MediaTask resource.
 * {@link /api/v1/media_tasks/{id}/transcribe}
 */
export const apiMediaTasksIdtranscribePatch = (
  args: {
    params: ApiMediaTasksIdtranscribePatchPathParams;
    body: ApiMediaTasksIdtranscribePatchMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiMediaTasksIdtranscribePatchMutationResponse> => {
  return http.patch(getApiMediaTasksIdtranscribePatchUrl(args.params), {
    ...options,
    json: args.body,
  }).json<ApiMediaTasksIdtranscribePatchMutationResponse>();
};