/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiMediaTasksIddownloadtranscribePatchMutationResponse, ApiMediaTasksIddownloadtranscribePatchPathParams, ApiMediaTasksIddownloadtranscribePatchMutationRequest } from "../../models";

function getApiMediaTasksIddownloadtranscribePatchUrl(params: ApiMediaTasksIddownloadtranscribePatchPathParams) {
  return `/api/v1/media_tasks/${encodeURIComponent(String(params.id))}/download/transcribe` as const;
}
/**
 * @summary Updates the MediaTask resource.
 * @description Updates the MediaTask resource.
 * {@link /api/v1/media_tasks/{id}/download/transcribe}
 */
export const apiMediaTasksIddownloadtranscribePatch = (
  args: {
    params: ApiMediaTasksIddownloadtranscribePatchPathParams;
    body: ApiMediaTasksIddownloadtranscribePatchMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiMediaTasksIddownloadtranscribePatchMutationResponse> => {
  return http.patch(getApiMediaTasksIddownloadtranscribePatchUrl(args.params), {
    ...options,
    json: args.body,
  }).json<ApiMediaTasksIddownloadtranscribePatchMutationResponse>();
};