/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";

export type ApiTokenConsummationsIdDeletePathParams = {
    /**
     * @description TokenConsummation identifier
     * @type string
    */
    id: string;
};

/**
 * @description TokenConsummation resource deleted
*/
export type ApiTokenConsummationsIdDelete204 = any;

/**
 * @description Not found
*/
export type ApiTokenConsummationsIdDelete404 = ErrorJsonld;

export type ApiTokenConsummationsIdDeleteMutationResponse = ApiTokenConsummationsIdDelete204;

export type ApiTokenConsummationsIdDeleteMutation = {
    Response: ApiTokenConsummationsIdDelete204;
    PathParams: ApiTokenConsummationsIdDeletePathParams;
    Errors: ApiTokenConsummationsIdDelete404;
};