/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProductHtmlGetCollectionPayment } from "../product/html-get-collection-payment";
import type { SubscriptionHtmlGetCollectionPayment } from "../subscription/html-get-collection-payment";
import type { TenantHtmlGetCollectionPayment } from "../tenant/html-get-collection-payment";

export const paymentHtmlGetCollectionPaymentStatusEnum = {
    pending: "pending",
    completed: "completed",
    disputed: "disputed",
    partially_refunded: "partially_refunded",
    fully_refunded: "fully_refunded",
    failed: "failed",
    overdue: "overdue"
} as const;

export type PaymentHtmlGetCollectionPaymentStatusEnumKey = (typeof paymentHtmlGetCollectionPaymentStatusEnum)[keyof typeof paymentHtmlGetCollectionPaymentStatusEnum];

export type PaymentHtmlGetCollectionPayment = {
    customer?: (TenantHtmlGetCollectionPayment | null);
    /**
     * @type string
    */
    status: PaymentHtmlGetCollectionPaymentStatusEnumKey;
    /**
     * @minLength 1
     * @maxLength 100000000
     * @type integer
    */
    amount: number;
    /**
     * @minLength 3
     * @maxLength 3
     * @type string
    */
    currency: string;
    subscription?: (SubscriptionHtmlGetCollectionPayment | null);
    product?: (ProductHtmlGetCollectionPayment | null);
    /**
     * @type string | undefined, ulid
    */
    id?: string;
    /**
     * @type string | undefined, date-time
    */
    createdAt?: string;
};