/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiRecordersGetCollectionQueryResponse, ApiRecordersGetCollectionQueryParams } from "../../models";

function getApiRecordersGetCollectionUrl() {
  return "/api/v1/recorders" as const;
}
/**
 * @summary Получение списка рекордеров
 * @description Retrieves the collection of Recorder resources.
 * {@link /api/v1/recorders}
 */
export const apiRecordersGetCollection = (
  args: {
    query: ApiRecordersGetCollectionQueryParams;
  },
  options?: RequestOptions,
): Promise<ApiRecordersGetCollectionQueryResponse> => {
  return http.get(getApiRecordersGetCollectionUrl(), {
    ...options,
    searchParams: args.query,
  }).json<ApiRecordersGetCollectionQueryResponse>();
};