/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiMultipartchunkPostMutationResponse, ApiMultipartchunkPostMutationRequest } from "../../models";

function getApiMultipartchunkPostUrl() {
  return "/api/v1/multipart/chunk" as const;
}
/**
 * @summary Creates a MultipartChunk resource.
 * @description Creates a MultipartChunk resource.
 * {@link /api/v1/multipart/chunk}
 */
export const apiMultipartchunkPost = (
  args: {
    body: ApiMultipartchunkPostMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiMultipartchunkPostMutationResponse> => {
  return http.post(getApiMultipartchunkPostUrl(), {
    ...options,
    json: args.body,
  }).json<ApiMultipartchunkPostMutationResponse>();
};