/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../../hydra-item-base-schema-schema";

export const CoreReportIntegrationErrorResponseDtoJsonldReportIntegrationErrorResponseSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "status": z.optional(z.string()),
"errorId": z.optional(z.string())
    }))