/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const PropertyFormDataStorageConfigDetailGetIdSchema = z.object({
    "name": z.optional(z.string()),
"slug": z.string().nullish(),
"type": z.enum(["string", "number", "bool"]).default("string").nullish(),
"isRequired": z.optional(z.boolean()),
"id": z.optional(z.union([z.string(), z.string()]))
    })