/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const recorderConfigRecorderConfigupdateStatusJsonMergePatchStatusEnum = {
    NOT_REQUIRE_AUTHORIZATION: "NOT_REQUIRE_AUTHORIZATION",
    WAITING_AUTHORIZATION: "WAITING_AUTHORIZATION",
    RECORDER_PROCESS_AUTHORIZATION: "RECORDER_PROCESS_AUTHORIZATION",
    ERROR_AUTHORIZATION: "ERROR_AUTHORIZATION",
    AUTHORIZED: "AUTHORIZED"
} as const;

export type RecorderConfigRecorderConfigupdateStatusJsonMergePatchStatusEnumKey = (typeof recorderConfigRecorderConfigupdateStatusJsonMergePatchStatusEnum)[keyof typeof recorderConfigRecorderConfigupdateStatusJsonMergePatchStatusEnum];

export type RecorderConfigRecorderConfigupdateStatusJsonMergePatch = {
    /**
     * @description Статус
     * @default "NOT_REQUIRE_AUTHORIZATION"
     * @type string | undefined
    */
    status?: RecorderConfigRecorderConfigupdateStatusJsonMergePatchStatusEnumKey;
};