/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { MeetJsonldSchema } from "./jsonld-schema";
import { MeetMeetBulkRequestDtoSchema } from "./meet-bulk-request-dto-schema";

/**
 * @description Meet resource created
 */
export const ApiMeetsmassDeletePost201Schema = z.lazy(() => MeetJsonldSchema)

/**
 * @description Invalid input
 */
export const ApiMeetsmassDeletePost400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiMeetsmassDeletePost403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiMeetsmassDeletePost422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new Meet resource
 */
export const ApiMeetsmassDeletePostMutationRequestSchema = z.lazy(() => MeetMeetBulkRequestDtoSchema)

export const ApiMeetsmassDeletePostMutationResponseSchema = z.lazy(() => ApiMeetsmassDeletePost201Schema)