/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { MeetJsonldSchema } from "./jsonld-schema";
import { MeetMeetRequestDtoJsonMergePatchSchema } from "./meet-request-dto/json-merge-patch-schema";

export const ApiMeetsIdtranscribePatchPathParamsSchema = z.object({
    "id": z.string().describe("Meet identifier")
    })

/**
 * @description Meet resource updated
 */
export const ApiMeetsIdtranscribePatch200Schema = z.lazy(() => MeetJsonldSchema)

/**
 * @description Invalid input
 */
export const ApiMeetsIdtranscribePatch400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiMeetsIdtranscribePatch403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiMeetsIdtranscribePatch404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiMeetsIdtranscribePatch422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated Meet resource
 */
export const ApiMeetsIdtranscribePatchMutationRequestSchema = z.lazy(() => MeetMeetRequestDtoJsonMergePatchSchema)

export const ApiMeetsIdtranscribePatchMutationResponseSchema = z.lazy(() => ApiMeetsIdtranscribePatch200Schema)