/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { MeetJsonldMeetUpdateSchema } from "./jsonld-meet-update-schema";
import { MeetMeetRequestDtoJsonMergePatchSchema } from "./meet-request-dto/json-merge-patch-schema";

export const ApiMeetsIddownloadsummaryPatchPathParamsSchema = z.object({
    "id": z.string().describe("Meet identifier")
    })

/**
 * @description Meet resource updated
 */
export const ApiMeetsIddownloadsummaryPatch200Schema = z.lazy(() => MeetJsonldMeetUpdateSchema)

/**
 * @description Invalid input
 */
export const ApiMeetsIddownloadsummaryPatch400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiMeetsIddownloadsummaryPatch403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiMeetsIddownloadsummaryPatch404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiMeetsIddownloadsummaryPatch422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated Meet resource
 */
export const ApiMeetsIddownloadsummaryPatchMutationRequestSchema = z.lazy(() => MeetMeetRequestDtoJsonMergePatchSchema)

export const ApiMeetsIddownloadsummaryPatchMutationResponseSchema = z.lazy(() => ApiMeetsIddownloadsummaryPatch200Schema)