/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { MeetMeetCreateSchema } from "../meet-meet-create-schema";
import { MeetJsonldMeetCreateReadSchema } from "./jsonld-meet-create-read-schema";

/**
 * @description Meet resource created
 */
export const ApiMeetsPost201Schema = z.lazy(() => MeetJsonldMeetCreateReadSchema)

/**
 * @description Invalid input
 */
export const ApiMeetsPost400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiMeetsPost403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiMeetsPost422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new Meet resource
 */
export const ApiMeetsPostMutationRequestSchema = z.lazy(() => MeetMeetCreateSchema)

export const ApiMeetsPostMutationResponseSchema = z.lazy(() => ApiMeetsPost201Schema)