/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { MeetJsonldMeetReadItemSchema } from "./jsonld-meet-read-item-schema";

export const ApiMeetsIdGetPathParamsSchema = z.object({
    "id": z.string().describe("Meet identifier")
    })

/**
 * @description Meet resource
 */
export const ApiMeetsIdGet200Schema = z.lazy(() => MeetJsonldMeetReadItemSchema)

/**
 * @description Forbidden
 */
export const ApiMeetsIdGet403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiMeetsIdGet404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiMeetsIdGetQueryResponseSchema = z.lazy(() => ApiMeetsIdGet200Schema)