/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const MeetConsumeTokenDtoReportIntegrationErrorResponseSchema = z.object({
    "availableBalance": z.optional(z.number().default(0))
    })