/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { IntegrationFormDataMeetReadItemSchema } from "../integration/form-data-meet-read-item-schema";
import { ProviderConfigFormDataMeetReadItemSchema } from "../provider-config/form-data-meet-read-item-schema";
import { RecorderConfigFormDataMeetReadItemSchema } from "../recorder-config/form-data-meet-read-item-schema";
import { RecorderFormDataMeetReadItemSchema } from "../recorder/form-data-meet-read-item-schema";
import { StorageConfigFormDataMeetReadItemSchema } from "../storage-config/form-data-meet-read-item-schema";
import { UserFormDataMeetReadItemSchema } from "../user/form-data-meet-read-item-schema";

export const MeetFormDataMeetReadItemSchema = z.object({
    "integration": z.optional(z.union([z.lazy(() => IntegrationFormDataMeetReadItemSchema), z.null()])),
"url": z.optional(z.string()),
"resultUrl": z.string().nullish(),
"archiveUrl": z.string().nullish(),
"name": z.string().nullish(),
"recorder": z.optional(z.union([z.lazy(() => RecorderFormDataMeetReadItemSchema), z.null()])),
"meetStartAt": z.string().datetime().nullish(),
"meetEndAt": z.string().datetime().nullish(),
"icalUid": z.string().nullish(),
"traceId": z.string().nullish(),
"participants": z.array(z.string().nullable()).nullish(),
"status": z.enum(["FOUND", "PREPARING", "TIME_CHANGED", "RECORDING", "RECORDING_PAUSED", "RECORDING_COMPLETED", "UPLOADING", "POSTPROCESSING", "EXTERNAL_UPLOAD", "COMPLETED", "ERROR", "TRANSCRIBE", "TRANSCRIBE_COMPLETED", "TRANSCRIBE_ERROR", "SUMMARY", "SUMMARY_COMPLETED", "SUMMARY_ERROR"]).default("FOUND").nullish(),
"user": z.optional(z.union([z.lazy(() => UserFormDataMeetReadItemSchema), z.null()])),
"videoLinkResult": z.string().nullish(),
"transcriptionResult": z.string().nullish(),
"summaryResult": z.string().nullish(),
"providerConfig": z.optional(z.union([z.lazy(() => ProviderConfigFormDataMeetReadItemSchema), z.null()])),
"storageConfig": z.optional(z.union([z.lazy(() => StorageConfigFormDataMeetReadItemSchema), z.null()])),
"recorderConfig": z.optional(z.union([z.lazy(() => RecorderConfigFormDataMeetReadItemSchema), z.null()])),
"transcription": z.boolean().nullish(),
"summarization": z.boolean().nullish(),
"duration": z.optional(z.number().int().default(0)),
"id": z.optional(z.union([z.string(), z.string()]))
    })