/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { IntegrationHtmlMeetCreateReadSchema } from "../integration/html-meet-create-read-schema";
import { ProviderConfigHtmlMeetCreateReadSchema } from "../provider-config/html-meet-create-read-schema";
import { RecorderConfigHtmlMeetCreateReadSchema } from "../recorder-config/html-meet-create-read-schema";
import { RecorderHtmlMeetCreateReadSchema } from "../recorder/html-meet-create-read-schema";
import { StorageConfigHtmlMeetCreateReadSchema } from "../storage-config/html-meet-create-read-schema";
import { UserHtmlMeetCreateReadSchema } from "../user/html-meet-create-read-schema";

export const MeetHtmlMeetCreateReadSchema = z.object({
    "integration": z.optional(z.union([z.lazy(() => IntegrationHtmlMeetCreateReadSchema), z.null()])),
"url": z.optional(z.string()),
"resultUrl": z.string().nullish(),
"archiveUrl": z.string().nullish(),
"name": z.string().nullish(),
"recorder": z.optional(z.union([z.lazy(() => RecorderHtmlMeetCreateReadSchema), z.null()])),
"meetStartAt": z.string().datetime().nullish(),
"meetEndAt": z.string().datetime().nullish(),
"icalUid": z.string().nullish(),
"traceId": z.string().nullish(),
"participants": z.array(z.string().nullable()).nullish(),
"status": z.enum(["FOUND", "PREPARING", "TIME_CHANGED", "RECORDING", "RECORDING_PAUSED", "RECORDING_COMPLETED", "UPLOADING", "POSTPROCESSING", "EXTERNAL_UPLOAD", "COMPLETED", "ERROR", "TRANSCRIBE", "TRANSCRIBE_COMPLETED", "TRANSCRIBE_ERROR", "SUMMARY", "SUMMARY_COMPLETED", "SUMMARY_ERROR"]).default("FOUND").nullish(),
"user": z.optional(z.union([z.lazy(() => UserHtmlMeetCreateReadSchema), z.null()])),
"token": z.string().nullish(),
"videoLinkResult": z.string().nullish(),
"transcriptionResult": z.string().nullish(),
"summaryResult": z.string().nullish(),
"providerConfig": z.optional(z.union([z.lazy(() => ProviderConfigHtmlMeetCreateReadSchema), z.null()])),
"storageConfig": z.optional(z.union([z.lazy(() => StorageConfigHtmlMeetCreateReadSchema), z.null()])),
"recorderConfig": z.optional(z.union([z.lazy(() => RecorderConfigHtmlMeetCreateReadSchema), z.null()])),
"transcription": z.boolean().nullish(),
"summarization": z.boolean().nullish(),
"duration": z.optional(z.number().int().default(0)),
"id": z.optional(z.union([z.string(), z.string()]))
    })