/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { IntegrationHtmlMeetUpdateReadSchema } from "../integration/html-meet-update-read-schema";
import { ProviderConfigHtmlMeetUpdateReadSchema } from "../provider-config/html-meet-update-read-schema";
import { RecorderConfigHtmlMeetUpdateReadSchema } from "../recorder-config/html-meet-update-read-schema";
import { StorageConfigHtmlMeetUpdateReadSchema } from "../storage-config/html-meet-update-read-schema";
import { UserHtmlMeetUpdateReadSchema } from "../user/html-meet-update-read-schema";

export const MeetHtmlMeetUpdateReadSchema = z.object({
    "integration": z.optional(z.union([z.lazy(() => IntegrationHtmlMeetUpdateReadSchema), z.null()])),
"url": z.optional(z.string()),
"resultUrl": z.string().nullish(),
"archiveUrl": z.string().nullish(),
"name": z.string().nullish(),
"recorder": z.string().nullish(),
"meetStartAt": z.string().datetime().nullish(),
"meetEndAt": z.string().datetime().nullish(),
"icalUid": z.string().nullish(),
"traceId": z.string().nullish(),
"participants": z.array(z.string().nullable()).nullish(),
"status": z.enum(["FOUND", "PREPARING", "TIME_CHANGED", "RECORDING", "RECORDING_PAUSED", "RECORDING_COMPLETED", "UPLOADING", "POSTPROCESSING", "EXTERNAL_UPLOAD", "COMPLETED", "ERROR", "TRANSCRIBE", "TRANSCRIBE_COMPLETED", "TRANSCRIBE_ERROR", "SUMMARY", "SUMMARY_COMPLETED", "SUMMARY_ERROR"]).default("FOUND").nullish(),
"user": z.optional(z.union([z.lazy(() => UserHtmlMeetUpdateReadSchema), z.null()])),
"videoLinkResult": z.string().nullish(),
"transcriptionResult": z.string().nullish(),
"summaryResult": z.string().nullish(),
"providerConfig": z.optional(z.union([z.lazy(() => ProviderConfigHtmlMeetUpdateReadSchema), z.null()])),
"storageConfig": z.optional(z.union([z.lazy(() => StorageConfigHtmlMeetUpdateReadSchema), z.null()])),
"recorderConfig": z.optional(z.union([z.lazy(() => RecorderConfigHtmlMeetUpdateReadSchema), z.null()])),
"transcription": z.boolean().nullish(),
"summarization": z.boolean().nullish(),
"duration": z.optional(z.number().int().default(0))
    })