/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { IntegrationHtmlMeetReadItemSchema } from "../integration/html-meet-read-item-schema";
import { ProviderConfigHtmlMeetReadItemSchema } from "../provider-config/html-meet-read-item-schema";
import { RecorderConfigHtmlMeetReadItemSchema } from "../recorder-config/html-meet-read-item-schema";
import { RecorderHtmlMeetReadItemSchema } from "../recorder/html-meet-read-item-schema";
import { StorageConfigHtmlMeetReadItemSchema } from "../storage-config/html-meet-read-item-schema";
import { UserHtmlMeetReadItemSchema } from "../user/html-meet-read-item-schema";

export const MeetHtmlMeetReadItemSchema = z.object({
    "integration": z.optional(z.union([z.lazy(() => IntegrationHtmlMeetReadItemSchema), z.null()])),
"url": z.optional(z.string()),
"resultUrl": z.string().nullish(),
"archiveUrl": z.string().nullish(),
"name": z.string().nullish(),
"recorder": z.optional(z.union([z.lazy(() => RecorderHtmlMeetReadItemSchema), z.null()])),
"meetStartAt": z.string().datetime().nullish(),
"meetEndAt": z.string().datetime().nullish(),
"icalUid": z.string().nullish(),
"traceId": z.string().nullish(),
"participants": z.array(z.string().nullable()).nullish(),
"status": z.enum(["FOUND", "PREPARING", "TIME_CHANGED", "RECORDING", "RECORDING_PAUSED", "RECORDING_COMPLETED", "UPLOADING", "POSTPROCESSING", "EXTERNAL_UPLOAD", "COMPLETED", "ERROR", "TRANSCRIBE", "TRANSCRIBE_COMPLETED", "TRANSCRIBE_ERROR", "SUMMARY", "SUMMARY_COMPLETED", "SUMMARY_ERROR"]).default("FOUND").nullish(),
"user": z.optional(z.union([z.lazy(() => UserHtmlMeetReadItemSchema), z.null()])),
"videoLinkResult": z.string().nullish(),
"transcriptionResult": z.string().nullish(),
"summaryResult": z.string().nullish(),
"providerConfig": z.optional(z.union([z.lazy(() => ProviderConfigHtmlMeetReadItemSchema), z.null()])),
"storageConfig": z.optional(z.union([z.lazy(() => StorageConfigHtmlMeetReadItemSchema), z.null()])),
"recorderConfig": z.optional(z.union([z.lazy(() => RecorderConfigHtmlMeetReadItemSchema), z.null()])),
"transcription": z.boolean().nullish(),
"summarization": z.boolean().nullish(),
"duration": z.optional(z.number().int().default(0)),
"id": z.optional(z.union([z.string(), z.string()]))
    })