/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";
import { IntegrationJsonldMeetReadItemSchema } from "../integration/jsonld-meet-read-item-schema";
import { ProviderConfigJsonldMeetReadItemSchema } from "../provider-config/jsonld-meet-read-item-schema";
import { RecorderConfigJsonldMeetReadItemSchema } from "../recorder-config/jsonld-meet-read-item-schema";
import { RecorderJsonldMeetReadItemSchema } from "../recorder/jsonld-meet-read-item-schema";
import { StorageConfigJsonldMeetReadItemSchema } from "../storage-config/jsonld-meet-read-item-schema";
import { UserJsonldMeetReadItemSchema } from "../user/jsonld-meet-read-item-schema";

export const MeetJsonldMeetReadItemSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "integration": z.optional(z.union([z.lazy(() => IntegrationJsonldMeetReadItemSchema), z.null()])),
"url": z.optional(z.string()),
"resultUrl": z.string().nullish(),
"archiveUrl": z.string().nullish(),
"name": z.string().nullish(),
"recorder": z.optional(z.union([z.lazy(() => RecorderJsonldMeetReadItemSchema), z.null()])),
"meetStartAt": z.string().datetime().nullish(),
"meetEndAt": z.string().datetime().nullish(),
"icalUid": z.string().nullish(),
"traceId": z.string().nullish(),
"participants": z.array(z.string().nullable()).nullish(),
"status": z.enum(["FOUND", "PREPARING", "TIME_CHANGED", "RECORDING", "RECORDING_PAUSED", "RECORDING_COMPLETED", "UPLOADING", "POSTPROCESSING", "EXTERNAL_UPLOAD", "COMPLETED", "ERROR", "TRANSCRIBE", "TRANSCRIBE_COMPLETED", "TRANSCRIBE_ERROR", "SUMMARY", "SUMMARY_COMPLETED", "SUMMARY_ERROR"]).default("FOUND").nullish(),
"user": z.optional(z.union([z.lazy(() => UserJsonldMeetReadItemSchema), z.null()])),
"videoLinkResult": z.string().nullish(),
"transcriptionResult": z.string().nullish(),
"summaryResult": z.string().nullish(),
"providerConfig": z.optional(z.union([z.lazy(() => ProviderConfigJsonldMeetReadItemSchema), z.null()])),
"storageConfig": z.optional(z.union([z.lazy(() => StorageConfigJsonldMeetReadItemSchema), z.null()])),
"recorderConfig": z.optional(z.union([z.lazy(() => RecorderConfigJsonldMeetReadItemSchema), z.null()])),
"transcription": z.boolean().nullish(),
"summarization": z.boolean().nullish(),
"duration": z.optional(z.number().int().default(0)),
"id": z.optional(z.union([z.string(), z.string()]))
    }))