/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";
import { IntegrationJsonldMeetUpdateReadSchema } from "../integration/jsonld-meet-update-read-schema";
import { ProviderConfigJsonldMeetUpdateReadSchema } from "../provider-config/jsonld-meet-update-read-schema";
import { RecorderConfigJsonldMeetUpdateReadSchema } from "../recorder-config/jsonld-meet-update-read-schema";
import { StorageConfigJsonldMeetUpdateReadSchema } from "../storage-config/jsonld-meet-update-read-schema";
import { UserJsonldMeetUpdateReadSchema } from "../user/jsonld-meet-update-read-schema";

export const MeetJsonldMeetUpdateReadSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "integration": z.optional(z.union([z.lazy(() => IntegrationJsonldMeetUpdateReadSchema), z.null()])),
"url": z.optional(z.string()),
"resultUrl": z.string().nullish(),
"archiveUrl": z.string().nullish(),
"name": z.string().nullish(),
"recorder": z.string().nullish(),
"meetStartAt": z.string().datetime().nullish(),
"meetEndAt": z.string().datetime().nullish(),
"icalUid": z.string().nullish(),
"traceId": z.string().nullish(),
"participants": z.array(z.string().nullable()).nullish(),
"status": z.enum(["FOUND", "PREPARING", "TIME_CHANGED", "RECORDING", "RECORDING_PAUSED", "RECORDING_COMPLETED", "UPLOADING", "POSTPROCESSING", "EXTERNAL_UPLOAD", "COMPLETED", "ERROR", "TRANSCRIBE", "TRANSCRIBE_COMPLETED", "TRANSCRIBE_ERROR", "SUMMARY", "SUMMARY_COMPLETED", "SUMMARY_ERROR"]).default("FOUND").nullish(),
"user": z.optional(z.union([z.lazy(() => UserJsonldMeetUpdateReadSchema), z.null()])),
"videoLinkResult": z.string().nullish(),
"transcriptionResult": z.string().nullish(),
"summaryResult": z.string().nullish(),
"providerConfig": z.optional(z.union([z.lazy(() => ProviderConfigJsonldMeetUpdateReadSchema), z.null()])),
"storageConfig": z.optional(z.union([z.lazy(() => StorageConfigJsonldMeetUpdateReadSchema), z.null()])),
"recorderConfig": z.optional(z.union([z.lazy(() => RecorderConfigJsonldMeetUpdateReadSchema), z.null()])),
"transcription": z.boolean().nullish(),
"summarization": z.boolean().nullish(),
"duration": z.optional(z.number().int().default(0))
    }))