/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";

export const MeetJsonldMeetUpdateSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "resultUrl": z.string().nullish(),
"archiveUrl": z.string().nullish(),
"name": z.string().nullish(),
"meetStartAt": z.string().datetime().nullish(),
"meetEndAt": z.string().datetime().nullish(),
"traceId": z.string().nullish(),
"status": z.enum(["FOUND", "PREPARING", "TIME_CHANGED", "RECORDING", "RECORDING_PAUSED", "RECORDING_COMPLETED", "UPLOADING", "POSTPROCESSING", "EXTERNAL_UPLOAD", "COMPLETED", "ERROR", "TRANSCRIBE", "TRANSCRIBE_COMPLETED", "TRANSCRIBE_ERROR", "SUMMARY", "SUMMARY_COMPLETED", "SUMMARY_ERROR"]).default("FOUND").nullish(),
"videoLinkResult": z.string().nullish(),
"transcriptionResult": z.string().nullish(),
"summaryResult": z.string().nullish(),
"duration": z.optional(z.number().int().default(0))
    }))