/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const MeetMeetBulkRequestDtoSchema = z.object({
    "meetIds": z.optional(z.array(z.string().nullable()))
    })