/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ProviderProviderConfigItemUpdateSchema } from "../provider-provider-config-item-update-schema";

export const ProviderConfigProviderConfigItemUpdateJsonMergePatchSchema = z.object({
    "name": z.optional(z.string()),
"provider": z.optional(z.lazy(() => ProviderProviderConfigItemUpdateSchema)),
"id": z.optional(z.union([z.string(), z.string()]))
    })