/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { HydraCollectionBaseSchema } from "../hydra-collection-base-schema";
import type { SubscriptionFeatureTokenPriceJsonldSubscriptionFeatureTokenPriceGetCollection } from "./jsonld-subscription-feature-token-price-get-collection";

export type ApiSubscriptionFeatureTokenPricesGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 100
     * @default 10
     * @type integer | undefined
    */
    itemsPerPage?: number;
};

/**
 * @description SubscriptionFeatureTokenPrice collection
*/
export type ApiSubscriptionFeatureTokenPricesGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: SubscriptionFeatureTokenPriceJsonldSubscriptionFeatureTokenPriceGetCollection[];
});

/**
 * @description Forbidden
*/
export type ApiSubscriptionFeatureTokenPricesGetCollection403 = ErrorJsonld;

export type ApiSubscriptionFeatureTokenPricesGetCollectionQueryResponse = ApiSubscriptionFeatureTokenPricesGetCollection200;

export type ApiSubscriptionFeatureTokenPricesGetCollectionQuery = {
    Response: ApiSubscriptionFeatureTokenPricesGetCollection200;
    QueryParams: ApiSubscriptionFeatureTokenPricesGetCollectionQueryParams;
    Errors: ApiSubscriptionFeatureTokenPricesGetCollection403;
};