/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const subscriptionFeatureTokenPriceHtmlSubscriptionFeatureTokenPriceGetCollectionUnitPriceEnum = {
    PCS: "PCS",
    PER_MINUTE: "PER_MINUTE",
    PER_MB: "PER_MB"
} as const;

export type SubscriptionFeatureTokenPriceHtmlSubscriptionFeatureTokenPriceGetCollectionUnitPriceEnumKey = (typeof subscriptionFeatureTokenPriceHtmlSubscriptionFeatureTokenPriceGetCollectionUnitPriceEnum)[keyof typeof subscriptionFeatureTokenPriceHtmlSubscriptionFeatureTokenPriceGetCollectionUnitPriceEnum];

export type SubscriptionFeatureTokenPriceHtmlSubscriptionFeatureTokenPriceGetCollection = {
    /**
     * @minLength 1
     * @maxLength 32
     * @type string | undefined
    */
    featureCode?: string;
    /**
     * @minLength 0
     * @default 0
     * @type number | undefined
    */
    itemTokenPrice?: number;
    /**
     * @default "PCS"
     * @type string | undefined
    */
    unitPrice?: SubscriptionFeatureTokenPriceHtmlSubscriptionFeatureTokenPriceGetCollectionUnitPriceEnumKey;
};