/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type SubscriptionFeatureFormDataGetCollectionSubscriptionPlan = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    description?: string | null;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};