/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";

export type MeetRequestDtoJsonld = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type string | undefined
    */
    meetId?: string;
});