/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiStoragesIdGetQueryResponse, ApiStoragesIdGetPathParams } from "../../models";

function getApiStoragesIdGetUrl(params: ApiStoragesIdGetPathParams) {
  return `/api/v1/storages/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Получение информации о хранилище
 * @description Retrieves a Storage resource.
 * {@link /api/v1/storages/{id}}
 */
export const apiStoragesIdGet = (
  args: {
    params: ApiStoragesIdGetPathParams;
  },
  options?: RequestOptions,
): Promise<ApiStoragesIdGetQueryResponse> => {
  return http.get(getApiStoragesIdGetUrl(args.params), {
    ...options,
  }).json<ApiStoragesIdGetQueryResponse>();
};