/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiAuthtokenPostMutationResponse, ApiAuthtokenPost400, ApiAuthtokenPost422 } from "../../models/auth/api-authtoken-post";
import { http } from "msw";

export function ApiAuthtokenPostHandlerResponse201(data: ApiAuthtokenPostMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiAuthtokenPostHandlerResponse400(data: ApiAuthtokenPost400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiAuthtokenPostHandlerResponse422(data: ApiAuthtokenPost422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiAuthtokenPostHandler(data?: ApiAuthtokenPostMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.post(`/api/v1/auth/token`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}