/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiTeamsIdGetQueryResponse, ApiTeamsIdGetPathParams } from "../../models";

function getApiTeamsIdGetUrl(params: ApiTeamsIdGetPathParams) {
  return `/api/v1/teams/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Retrieves a Team resource.
 * @description Retrieves a Team resource.
 * {@link /api/v1/teams/{id}}
 */
export const apiTeamsIdGet = (
  args: {
    params: ApiTeamsIdGetPathParams;
  },
  options?: RequestOptions,
): Promise<ApiTeamsIdGetQueryResponse> => {
  return http.get(getApiTeamsIdGetUrl(args.params), {
    ...options,
  }).json<ApiTeamsIdGetQueryResponse>();
};