/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type SubscriptionFormDataGetItemPayment = {
    /**
     * @type string,null
    */
    planName?: string | null;
    readonly id?: any;
    /**
     * @type string,null, date-time
    */
    endedAt?: string | null;
    /**
     * @type string,null, date-time
    */
    createdAt?: string | null;
};