/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthBaseRegistrationDto } from "./base-registration-dto";
import type { ConstraintViolationJsonld } from "../constraint-violation/jsonld";
import type { ErrorJsonld } from "../error/jsonld";

/**
 * @description Auth resource created
*/
export type ApiAuthregistrationPost204 = any;

/**
 * @description Invalid input
*/
export type ApiAuthregistrationPost400 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiAuthregistrationPost422 = ConstraintViolationJsonld;

/**
 * @description The new Auth resource
*/
export type ApiAuthregistrationPostMutationRequest = AuthBaseRegistrationDto;

export type ApiAuthregistrationPostMutationResponse = ApiAuthregistrationPost204;

export type ApiAuthregistrationPostMutation = {
    Response: ApiAuthregistrationPost204;
    Request: ApiAuthregistrationPostMutationRequest;
    Errors: ApiAuthregistrationPost400 | ApiAuthregistrationPost422;
};