/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthLogoutDto } from "./logout-dto";
import type { ConstraintViolationJsonld } from "../constraint-violation/jsonld";
import type { ErrorJsonld } from "../error/jsonld";

/**
 * @description Auth resource created
*/
export type ApiAuthlogoutPost204 = any;

/**
 * @description Invalid input
*/
export type ApiAuthlogoutPost400 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiAuthlogoutPost422 = ConstraintViolationJsonld;

/**
 * @description The new Auth resource
*/
export type ApiAuthlogoutPostMutationRequest = AuthLogoutDto;

export type ApiAuthlogoutPostMutationResponse = ApiAuthlogoutPost204;

export type ApiAuthlogoutPostMutation = {
    Response: ApiAuthlogoutPost204;
    Request: ApiAuthlogoutPostMutationRequest;
    Errors: ApiAuthlogoutPost400 | ApiAuthlogoutPost422;
};