/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AuthTokenDto = {
    /**
     * @type string | undefined
    */
    accessToken?: string;
    /**
     * @type string | undefined
    */
    refreshToken?: string;
};