/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiIntegrationsPostMutationResponse, ApiIntegrationsPost400, ApiIntegrationsPost422 } from "../../models/integration/api-integrations-post";
import { http } from "msw";

export function ApiIntegrationsPostHandlerResponse201(data: ApiIntegrationsPostMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiIntegrationsPostHandlerResponse400(data: ApiIntegrationsPost400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiIntegrationsPostHandlerResponse422(data: ApiIntegrationsPost422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiIntegrationsPostHandler(data?: ApiIntegrationsPostMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.post(`/api/v1/integrations`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}