/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../../hydra-item-base-schema";

/**
 * @description Инициирует отправку письма для смены пароля через Keycloak.
*/
export type UserPasswordResetResponseDtoJsonld = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    message?: string;
});