/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiTokenConsummationsIdGetQueryResponse, ApiTokenConsummationsIdGet404 } from "../../models/token-consummation/api-token-consummations-id-get";
import { http } from "msw";

export function ApiTokenConsummationsIdGetHandlerResponse200(data: ApiTokenConsummationsIdGetQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiTokenConsummationsIdGetHandlerResponse404(data: ApiTokenConsummationsIdGet404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiTokenConsummationsIdGetHandler(data?: ApiTokenConsummationsIdGetQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/v1/token_consummations/:id`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}