/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiTokenConsummationsGetCollectionQueryResponse } from "../../models/token-consummation/api-token-consummations-get-collection";
import { http } from "msw";

export function ApiTokenConsummationsGetCollectionHandlerResponse200(data: ApiTokenConsummationsGetCollectionQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiTokenConsummationsGetCollectionHandler(data?: ApiTokenConsummationsGetCollectionQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/v1/token_consummations`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}