/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiTokenConsummationsPostMutationResponse, ApiTokenConsummationsPost400, ApiTokenConsummationsPost422 } from "../../models/token-consummation/api-token-consummations-post";
import { http } from "msw";

export function ApiTokenConsummationsPostHandlerResponse201(data: ApiTokenConsummationsPostMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiTokenConsummationsPostHandlerResponse400(data: ApiTokenConsummationsPost400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiTokenConsummationsPostHandlerResponse422(data: ApiTokenConsummationsPost422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiTokenConsummationsPostHandler(data?: ApiTokenConsummationsPostMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.post(`/api/v1/token_consummations`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}