/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiStorageConfigsIdPatchMutationResponse, ApiStorageConfigsIdPatch400, ApiStorageConfigsIdPatch403, ApiStorageConfigsIdPatch404, ApiStorageConfigsIdPatch422 } from "../../models/storage-config/api-storage-configs-id-patch";
import { http } from "msw";

export function ApiStorageConfigsIdPatchHandlerResponse200(data: ApiStorageConfigsIdPatchMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiStorageConfigsIdPatchHandlerResponse400(data: ApiStorageConfigsIdPatch400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiStorageConfigsIdPatchHandlerResponse403(data: ApiStorageConfigsIdPatch403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiStorageConfigsIdPatchHandlerResponse404(data: ApiStorageConfigsIdPatch404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiStorageConfigsIdPatchHandlerResponse422(data: ApiStorageConfigsIdPatch422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiStorageConfigsIdPatchHandler(data?: ApiStorageConfigsIdPatchMutationResponse | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.patch(`/api/v1/storage_configs/:id`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}