/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiStorageConfigsIdGetQueryResponse, ApiStorageConfigsIdGet403, ApiStorageConfigsIdGet404 } from "../../models/storage-config/api-storage-configs-id-get";
import { http } from "msw";

export function ApiStorageConfigsIdGetHandlerResponse200(data: ApiStorageConfigsIdGetQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiStorageConfigsIdGetHandlerResponse403(data: ApiStorageConfigsIdGet403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiStorageConfigsIdGetHandlerResponse404(data: ApiStorageConfigsIdGet404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiStorageConfigsIdGetHandler(data?: ApiStorageConfigsIdGetQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/v1/storage_configs/:id`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}