/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";

export const SubscriptionPlanRequestDtoJsonldSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "id": z.optional(z.string()),
"priceId": z.optional(z.string()),
"free": z.optional(z.boolean().default(false))
    }))