/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../../hydra-item-base-schema";

export type StorageJsonldStorageConfigDetailGetId = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});