/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MeetConsumeTokenDtoReportIntegrationErrorRequestJsonMergePatch = {
    /**
     * @type string,null, ulid
    */
    meet?: string | null;
    /**
     * @type string,null
    */
    featureCode?: string | null;
    /**
     * @minLength 0
     * @default 0
     * @type number | undefined
    */
    count?: number;
};