/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { CreateUserHandler } from "./users/create-user-handler";
import { DeleteUserHandler } from "./users/delete-user-handler";
import { GetUserHandler } from "./users/get-user-handler";
import { ListUsersHandler } from "./users/list-users-handler";

export const handlers = [ListUsersHandler(),CreateUserHandler(),GetUserHandler(),DeleteUserHandler()] as const