/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiMultipartIdstatusGetQueryResponse, ApiMultipartIdstatusGetPathParams } from "../../models";

function getApiMultipartIdstatusGetUrl(params: ApiMultipartIdstatusGetPathParams) {
  return `/api/v1/multipart/${encodeURIComponent(String(params.id))}/status` as const;
}
/**
 * @summary Retrieves a MultipartUpload resource.
 * @description Retrieves a MultipartUpload resource.
 * {@link /api/v1/multipart/{id}/status}
 */
export const apiMultipartIdstatusGet = (
  args: {
    params: ApiMultipartIdstatusGetPathParams;
  },
  options?: RequestOptions,
): Promise<ApiMultipartIdstatusGetQueryResponse> => {
  return http.get(getApiMultipartIdstatusGetUrl(args.params), {
    ...options,
  }).json<ApiMultipartIdstatusGetQueryResponse>();
};