/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiMultipartIdcompletePostMutationResponse, ApiMultipartIdcompletePostPathParams } from "../../models";

function getApiMultipartIdcompletePostUrl(params: ApiMultipartIdcompletePostPathParams) {
  return `/api/v1/multipart/${encodeURIComponent(String(params.id))}/complete` as const;
}
/**
 * @summary Creates a MultipartUpload resource.
 * @description Creates a MultipartUpload resource.
 * {@link /api/v1/multipart/{id}/complete}
 */
export const apiMultipartIdcompletePost = (
  args: {
    params: ApiMultipartIdcompletePostPathParams;
  },
  options?: RequestOptions,
): Promise<ApiMultipartIdcompletePostMutationResponse> => {
  return http.post(getApiMultipartIdcompletePostUrl(args.params), {
    ...options,
  }).json<ApiMultipartIdcompletePostMutationResponse>();
};