/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyValueHtmlStorageConfigDetailGetId } from "../../property-value/html-storage-config/detail-get-id";
import type { StorageHtmlStorageConfigDetailGetId } from "../../storage/html-storage-config/detail-get-id";

export type StorageConfigHtmlStorageConfigDetailGetId = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type object
    */
    storage: StorageHtmlStorageConfigDetailGetId;
    /**
     * @type array
    */
    propertyValues: PropertyValueHtmlStorageConfigDetailGetId[];
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};