/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StorageHtmlStorageConfigListGetId } from "../../storage/html-storage-config/list-get-id";

export type StorageConfigHtmlStorageConfigListGetId = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type object
    */
    storage: StorageHtmlStorageConfigListGetId;
    /**
     * @default false
     * @type boolean | undefined
    */
    isGlobal?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};