/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { HydraCollectionBaseSchemaSchema } from "../hydra-collection-base-schema-schema";
import { UserJsonldTeamUserCollectionReadSchema } from "./jsonld-team-user-collection-read-schema";

export const ApiTeamsIdusersGetCollectionPathParamsSchema = z.object({
    "id": z.string().describe("User identifier")
    })

export const ApiTeamsIdusersGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(100).default(10).describe("The number of items per page"),
"order[firstName]": z.enum(["asc", "desc"]).default("asc"),
"order[lastName]": z.enum(["asc", "desc"]).default("asc"),
"order[email]": z.enum(["asc", "desc"]).default("asc"),
"order[personalTokenLimitUsed]": z.enum(["asc", "desc"]).default("asc"),
"order[personalTokenLimit]": z.enum(["asc", "desc"]).default("asc"),
"order[createdAt]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description User collection
 */
export const ApiTeamsIdusersGetCollection200Schema = z.lazy(() => HydraCollectionBaseSchemaSchema).and(z.object({
    "member": z.array(z.lazy(() => UserJsonldTeamUserCollectionReadSchema))
    })).describe("User.jsonld-TeamUserCollectionRead collection.")

/**
 * @description Forbidden
 */
export const ApiTeamsIdusersGetCollection403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiTeamsIdusersGetCollectionQueryResponseSchema = z.lazy(() => ApiTeamsIdusersGetCollection200Schema)