/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const UserFormDataSchema = z.object({
    "password": z.string().nullish(),
"name": z.string().nullish(),
"confirmationCode": z.string().nullish(),
"createdAt": z.optional(z.string().datetime()),
"activatedAt": z.string().datetime().nullish(),
"deletedAt": z.string().datetime().nullish(),
"isConfirmed": z.optional(z.boolean().default(false)),
"isDeleted": z.optional(z.boolean().default(false)),
"team": z.string().nullish(),
"tenantExternalId": z.string().nullish(),
"id": z.optional(z.union([z.string(), z.string()])),
"roles": z.optional(z.array(z.string().nullable())),
"username": z.optional(z.string()),
"displayName": z.optional(z.string()),
"firstName": z.optional(z.string()),
"lastName": z.optional(z.string()),
"email": z.optional(z.string()),
"timeZone": z.optional(z.string().default("Europe/Moscow")),
"accessToken": z.string().nullish(),
"refreshToken": z.string().nullish(),
"personalTokenLimit": z.optional(z.number().default(0)),
"personalTokenLimitUsed": z.optional(z.number().default(0)),
"isBlocked": z.optional(z.boolean().default(false)),
"dateCreate": z.optional(z.string().datetime()),
"dateUpdate": z.string().datetime().nullish(),
"confirmed": z.optional(z.boolean()),
"deleted": z.optional(z.boolean()),
"userIdentifier": z.optional(z.string()),
"blockedAt": z.string().datetime().nullish(),
"clientId": z.optional(z.string()),
"emailVerified": z.optional(z.boolean()),
"salt": z.string().nullish()
    })