/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { UserInviteUserDtoJsonMergePatchSchema } from "./invite-user-dto/json-merge-patch-schema";
import { UserJsonldSchema } from "./jsonld-schema";

/**
 * @description User resource updated
 */
export const InviteUser200Schema = z.lazy(() => UserJsonldSchema)

/**
 * @description Invalid input
 */
export const InviteUser400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const InviteUser403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const InviteUser404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const InviteUser422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated User resource
 */
export const InviteUserMutationRequestSchema = z.lazy(() => UserInviteUserDtoJsonMergePatchSchema)

export const InviteUserMutationResponseSchema = z.lazy(() => InviteUser200Schema)