/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";

export const UserJsonldMeetReadItemSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "id": z.optional(z.union([z.string(), z.string()])),
"email": z.optional(z.string())
    }))