/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyHtmlStorageConfigDetailGetId } from "../../property/html-storage-config/detail-get-id";

export type PropertyValueHtmlStorageConfigDetailGetId = {
    /**
     * @type string,null
    */
    value?: string | null;
    /**
     * @type object
    */
    property: PropertyHtmlStorageConfigDetailGetId;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};