/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiFilesPostMutationResponse, ApiFilesPost400, ApiFilesPost403, ApiFilesPost422 } from "../../models/file/api-files-post";
import { http } from "msw";

export function ApiFilesPostHandlerResponse201(data: ApiFilesPostMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiFilesPostHandlerResponse400(data: ApiFilesPost400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiFilesPostHandlerResponse403(data: ApiFilesPost403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiFilesPostHandlerResponse422(data: ApiFilesPost422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiFilesPostHandler(data?: ApiFilesPostMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.post(`/api/v1/files`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}