/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FileGetResourceQueryResponse, FileGetResource404 } from "../../models/file/file-get-resource";
import { http } from "msw";

export function FileGetResourceHandlerResponse204(data?: FileGetResourceQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
}

export function FileGetResourceHandlerResponse404(data: FileGetResource404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function FileGetResourceHandler(data?: string | number | boolean | null | object | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/v1/get_file/:path`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
    })
}