/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const propertyHtmlStorageItemReadGetIdPropertyReadTypeEnum = {
    string: "string",
    number: "number",
    bool: "bool"
} as const;

export type PropertyHtmlStorageItemReadGetIdPropertyReadTypeEnumKey = (typeof propertyHtmlStorageItemReadGetIdPropertyReadTypeEnum)[keyof typeof propertyHtmlStorageItemReadGetIdPropertyReadTypeEnum];

export const propertyHtmlStorageItemReadGetIdPropertyReadForEntityEnum = {
    provider: "provider",
    recorder: "recorder",
    storage: "storage"
} as const;

export type PropertyHtmlStorageItemReadGetIdPropertyReadForEntityEnumKey = (typeof propertyHtmlStorageItemReadGetIdPropertyReadForEntityEnum)[keyof typeof propertyHtmlStorageItemReadGetIdPropertyReadForEntityEnum];

export type PropertyHtmlStorageItemReadGetIdPropertyRead = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @default "string"
     * @type string,null
    */
    type?: PropertyHtmlStorageItemReadGetIdPropertyReadTypeEnumKey | null;
    /**
     * @type string,null
    */
    forEntity?: PropertyHtmlStorageItemReadGetIdPropertyReadForEntityEnumKey | null;
    /**
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};