/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { HydraCollectionBaseSchemaSchema } from "../hydra-collection-base-schema-schema";
import { SubscriptionFeatureTokenPriceJsonldSubscriptionFeatureTokenPriceGetCollectionSchema } from "./jsonld-subscription-feature-token-price-get-collection-schema";

export const ApiSubscriptionFeatureTokenPricesGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(100).default(10).describe("The number of items per page")
    })

/**
 * @description SubscriptionFeatureTokenPrice collection
 */
export const ApiSubscriptionFeatureTokenPricesGetCollection200Schema = z.lazy(() => HydraCollectionBaseSchemaSchema).and(z.object({
    "member": z.array(z.lazy(() => SubscriptionFeatureTokenPriceJsonldSubscriptionFeatureTokenPriceGetCollectionSchema))
    })).describe("SubscriptionFeatureTokenPrice.jsonld-SubscriptionFeatureTokenPriceGetCollection collection.")

/**
 * @description Forbidden
 */
export const ApiSubscriptionFeatureTokenPricesGetCollection403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiSubscriptionFeatureTokenPricesGetCollectionQueryResponseSchema = z.lazy(() => ApiSubscriptionFeatureTokenPricesGetCollection200Schema)