/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const SubscriptionFeatureTokenPriceHtmlSubscriptionFeatureTokenPriceGetObjectSchema = z.object({
    "featureCode": z.optional(z.string().min(1).max(32)),
"itemTokenPrice": z.optional(z.number().min(0).default(0)),
"unitPrice": z.optional(z.enum(["PCS", "PER_MINUTE", "PER_MB"]).default("PCS"))
    })