/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Unprocessable entity
*/
export type ConstraintViolation = {
    /**
     * @default 422
     * @type integer | undefined
    */
    status?: number;
    /**
     * @type array | undefined
    */
    violations?: {
        /**
         * @description The property path of the violation
         * @type string
        */
        propertyPath: string;
        /**
         * @description The message associated with the violation
         * @type string
        */
        message: string;
        /**
         * @description The code of the violation
         * @type string | undefined
        */
        code?: string;
        /**
         * @description An extra hint to understand the violation
         * @type string | undefined
        */
        hint?: string;
        /**
         * @description The serialized payload of the violation
         * @type object | undefined
        */
        payload?: {
            [key: string]: any;
        };
    }[];
    /**
     * @type string | undefined
    */
    readonly detail?: string;
    /**
     * @type string | undefined
    */
    readonly type?: string;
    /**
     * @type string,null
    */
    readonly title?: string | null;
    /**
     * @type string,null
    */
    readonly instance?: string | null;
};