/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type FileGetItemMediaTask = {
    /**
     * @type string | undefined
    */
    originalName?: string;
    /**
     * @type integer,null
    */
    duration?: number | null;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};