/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type FileSet = {
    /**
     * @type string | undefined
    */
    originalName?: string;
    /**
     * @type file | undefined
    */
    file?;
};