/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchemaNoPagination } from "./hydra-collection-base-schema-no-pagination";

export type HydraCollectionBaseSchema = (HydraCollectionBaseSchemaNoPagination & {
    /**
     * @type object | undefined
    */
    view?: {
        /**
         * @type string | undefined, iri-reference
        */
        "@id"?: string;
        /**
         * @type string | undefined
        */
        "@type"?: string;
        /**
         * @type string | undefined, iri-reference
        */
        first?: string;
        /**
         * @type string | undefined, iri-reference
        */
        last?: string;
        /**
         * @type string | undefined, iri-reference
        */
        previous?: string;
        /**
         * @type string | undefined, iri-reference
        */
        next?: string;
    };
});