/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const contextHydraEnum = {
    "http://www.w3.org/ns/hydra/core#": "http://www.w3.org/ns/hydra/core#"
} as const;

export type ContextHydraEnumKey = (typeof contextHydraEnum)[keyof typeof contextHydraEnum];

export type HydraItemBaseSchema = {
    "@context"?: (string | {
        /**
         * @type string
        */
        "@vocab": string;
        /**
         * @type string
        */
        hydra: ContextHydraEnumKey;
        [key: string]: unknown;
    });
    /**
     * @type string
    */
    "@id": string;
    /**
     * @type string
    */
    "@type": string;
};