/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProviderConfigGetObjIntegration } from "./provider-config-get-obj-integration";
import type { RecorderConfigGetObjIntegration } from "./recorder-config-get-obj-integration";
import type { StorageConfigGetObjIntegration } from "./storage-config-get-obj-integration";

export type IntegrationGetObjIntegration = {
    /**
     * @type object
    */
    providerConfig: ProviderConfigGetObjIntegration;
    /**
     * @type object
    */
    recorderConfig: RecorderConfigGetObjIntegration;
    /**
     * @type object
    */
    storageConfig: StorageConfigGetObjIntegration;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};