/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const mediaTaskStatusHistoryStatusEnum = {
    CREATED: "CREATED",
    TRANSCRIBE: "TRANSCRIBE",
    TRANSCRIBE_COMPLETED: "TRANSCRIBE_COMPLETED",
    TRANSCRIBE_ERROR: "TRANSCRIBE_ERROR",
    SUMMARY: "SUMMARY",
    SUMMARY_COMPLETED: "SUMMARY_COMPLETED",
    SUMMARY_ERROR: "SUMMARY_ERROR"
} as const;

export type MediaTaskStatusHistoryStatusEnumKey = (typeof mediaTaskStatusHistoryStatusEnum)[keyof typeof mediaTaskStatusHistoryStatusEnum];

export type MediaTaskStatusHistory = {
    /**
     * @type string | undefined
    */
    status?: MediaTaskStatusHistoryStatusEnumKey;
    /**
     * @type string | undefined, date-time
    */
    date?: string;
    /**
     * @type string | undefined, iri-reference
    */
    mediaTask?: string;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined, date-time
    */
    readonly dateCreate?: string;
    /**
     * @type string,null, date-time
    */
    readonly dateUpdate?: string | null;
};