/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FileGetItemMediaTask } from "./file-get-item-media-task";
import type { UserGetItemMediaTask } from "./user-get-item-media-task";

export const mediaTaskGetItemMediaTaskStatusEnum = {
    CREATED: "CREATED",
    TRANSCRIBE: "TRANSCRIBE",
    TRANSCRIBE_COMPLETED: "TRANSCRIBE_COMPLETED",
    TRANSCRIBE_ERROR: "TRANSCRIBE_ERROR",
    SUMMARY: "SUMMARY",
    SUMMARY_COMPLETED: "SUMMARY_COMPLETED",
    SUMMARY_ERROR: "SUMMARY_ERROR"
} as const;

export type MediaTaskGetItemMediaTaskStatusEnumKey = (typeof mediaTaskGetItemMediaTaskStatusEnum)[keyof typeof mediaTaskGetItemMediaTaskStatusEnum];

export type MediaTaskGetItemMediaTask = {
    file?: (FileGetItemMediaTask | null);
    user?: (UserGetItemMediaTask | null);
    /**
     * @type string,null
    */
    transcriptionResult?: string | null;
    /**
     * @type string,null
    */
    summaryResult?: string | null;
    /**
     * @default "CREATED"
     * @type string | undefined
    */
    status?: MediaTaskGetItemMediaTaskStatusEnumKey;
    /**
     * @type string,null
    */
    traceId?: string | null;
    /**
     * @type integer,null
    */
    duration?: number | null;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined, date-time
    */
    readonly dateCreate?: string;
};