/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MeetRequestDto = {
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type string | undefined
    */
    meetId?: string;
};