/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProductGetItemPayment } from "./product-get-item-payment";
import type { SubscriptionGetItemPayment } from "./subscription-get-item-payment";
import type { TenantGetItemPayment } from "./tenant-get-item-payment";

export const paymentGetItemPaymentStatusEnum = {
    pending: "pending",
    completed: "completed",
    disputed: "disputed",
    partially_refunded: "partially_refunded",
    fully_refunded: "fully_refunded",
    failed: "failed",
    overdue: "overdue"
} as const;

export type PaymentGetItemPaymentStatusEnumKey = (typeof paymentGetItemPaymentStatusEnum)[keyof typeof paymentGetItemPaymentStatusEnum];

export type PaymentGetItemPayment = {
    customer?: (TenantGetItemPayment | null);
    /**
     * @type string
    */
    status: PaymentGetItemPaymentStatusEnumKey;
    /**
     * @minLength 1
     * @maxLength 100000000
     * @type integer
    */
    amount: number;
    /**
     * @minLength 3
     * @maxLength 3
     * @type string
    */
    currency: string;
    /**
     * @maxLength 500
     * @type string,null, uri
    */
    paymentProviderDetailsUrl?: string | null;
    subscription?: (SubscriptionGetItemPayment | null);
    product?: (ProductGetItemPayment | null);
    /**
     * @type string | undefined, ulid
    */
    id?: string;
    /**
     * @type string | undefined, date-time
    */
    createdAt?: string;
};