/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PriceGetCurrentSubscription = {
    readonly id?: any;
    /**
     * @type integer,null
    */
    amount?: number | null;
    /**
     * @type string | undefined
    */
    currency?: string;
};