/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const propertyPropertyCollectionReadTypeEnum = {
    string: "string",
    number: "number",
    bool: "bool"
} as const;

export type PropertyPropertyCollectionReadTypeEnumKey = (typeof propertyPropertyCollectionReadTypeEnum)[keyof typeof propertyPropertyCollectionReadTypeEnum];

export const propertyPropertyCollectionReadForEntityEnum = {
    provider: "provider",
    recorder: "recorder",
    storage: "storage"
} as const;

export type PropertyPropertyCollectionReadForEntityEnumKey = (typeof propertyPropertyCollectionReadForEntityEnum)[keyof typeof propertyPropertyCollectionReadForEntityEnum];

export type PropertyPropertyCollectionRead = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @default "string"
     * @type string,null
    */
    type?: PropertyPropertyCollectionReadTypeEnumKey | null;
    /**
     * @type string,null
    */
    forEntity?: PropertyPropertyCollectionReadForEntityEnumKey | null;
    /**
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};