/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyPropertyValueItemRead } from "./property-property-value-item-read";

export type PropertyValuePropertyValueItemRead = {
    /**
     * @type string,null
    */
    value?: string | null;
    /**
     * @type object
    */
    property: PropertyPropertyValueItemRead;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};