/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const propertyRecorderConfigReadItemTypeEnum = {
    string: "string",
    number: "number",
    bool: "bool"
} as const;

export type PropertyRecorderConfigReadItemTypeEnumKey = (typeof propertyRecorderConfigReadItemTypeEnum)[keyof typeof propertyRecorderConfigReadItemTypeEnum];

export const propertyRecorderConfigReadItemForEntityEnum = {
    provider: "provider",
    recorder: "recorder",
    storage: "storage"
} as const;

export type PropertyRecorderConfigReadItemForEntityEnumKey = (typeof propertyRecorderConfigReadItemForEntityEnum)[keyof typeof propertyRecorderConfigReadItemForEntityEnum];

export type PropertyRecorderConfigReadItem = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @default "string"
     * @type string,null
    */
    type?: PropertyRecorderConfigReadItemTypeEnumKey | null;
    /**
     * @type string,null
    */
    forEntity?: PropertyRecorderConfigReadItemForEntityEnumKey | null;
    /**
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};