/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const propertyProviderConfigItemReadTypeEnum = {
    string: "string",
    number: "number",
    bool: "bool"
} as const;

export type PropertyProviderConfigItemReadTypeEnumKey = (typeof propertyProviderConfigItemReadTypeEnum)[keyof typeof propertyProviderConfigItemReadTypeEnum];

export const propertyProviderConfigItemReadForEntityEnum = {
    provider: "provider",
    recorder: "recorder",
    storage: "storage"
} as const;

export type PropertyProviderConfigItemReadForEntityEnumKey = (typeof propertyProviderConfigItemReadForEntityEnum)[keyof typeof propertyProviderConfigItemReadForEntityEnum];

export type PropertyProviderConfigItemRead = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @default "string"
     * @type string,null
    */
    type?: PropertyProviderConfigItemReadTypeEnumKey | null;
    /**
     * @type string,null
    */
    forEntity?: PropertyProviderConfigItemReadForEntityEnumKey | null;
    /**
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};