/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyValueProviderConfigItemWriteJsonMergePatch } from "./property-value-provider-config-item-write/json-merge-patch";
import type { ProviderProviderConfigItemWrite } from "./provider-provider-config-item-write";

export type ProviderConfigProviderConfigItemWrite = {
    /**
     * @type string
    */
    name: string;
    /**
     * @default true
     * @type boolean | undefined
    */
    isActive?: boolean;
    /**
     * @type object
    */
    provider: ProviderProviderConfigItemWrite;
    /**
     * @type array
    */
    propertyValues: PropertyValueProviderConfigItemWriteJsonMergePatch[];
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};