/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProviderConfigError } from "./provider-config-error";

export type ProviderConfig = {
    /**
     * @type string
    */
    name: string;
    /**
     * @default true
     * @type boolean | undefined
    */
    isActive?: boolean;
    /**
     * @type string, iri-reference
    */
    provider: string;
    /**
     * @type array
    */
    propertyValues: string[];
    /**
     * @type array | undefined
    */
    errors?: ProviderConfigError[];
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined, date-time
    */
    readonly dateCreate?: string;
    /**
     * @type string,null, date-time
    */
    readonly dateUpdate?: string | null;
};