/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RecorderMeetCreateRead } from "./recorder-meet-create-read";

export type RecorderConfigMeetCreateRead = {
    /**
     * @type string
    */
    name: string;
    recorder: (RecorderMeetCreateRead | null);
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};