/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyValueRecorderConfigReadItem } from "./property-value-recorder-config-read-item";
import type { RecorderRecorderConfigReadItem } from "./recorder-recorder-config-read-item";

export const recorderConfigRecorderConfigReadItemStatusEnum = {
    NOT_REQUIRE_AUTHORIZATION: "NOT_REQUIRE_AUTHORIZATION",
    WAITING_AUTHORIZATION: "WAITING_AUTHORIZATION",
    RECORDER_PROCESS_AUTHORIZATION: "RECORDER_PROCESS_AUTHORIZATION",
    ERROR_AUTHORIZATION: "ERROR_AUTHORIZATION",
    AUTHORIZED: "AUTHORIZED"
} as const;

export type RecorderConfigRecorderConfigReadItemStatusEnumKey = (typeof recorderConfigRecorderConfigReadItemStatusEnum)[keyof typeof recorderConfigRecorderConfigReadItemStatusEnum];

export type RecorderConfigRecorderConfigReadItem = {
    /**
     * @type string
    */
    name: string;
    /**
     * @default true
     * @type boolean
    */
    isActive: boolean;
    recorder: (RecorderRecorderConfigReadItem | null);
    /**
     * @type array
    */
    propertyValues: PropertyValueRecorderConfigReadItem[];
    /**
     * @description Статус
     * @default "NOT_REQUIRE_AUTHORIZATION"
     * @type string | undefined
    */
    status?: RecorderConfigRecorderConfigReadItemStatusEnumKey;
    /**
     * @default false
     * @type boolean | undefined
    */
    isGlobal?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};