/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RecorderGetObjIntegration } from "./recorder-get-obj-integration";

export type RecorderConfigGetObjIntegration = {
    /**
     * @type string
    */
    name: string;
    recorder: (RecorderGetObjIntegration | null);
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};