/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StorageGetObjIntegration } from "./storage-get-obj-integration";

export type StorageConfigGetObjIntegration = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type object
    */
    storage: StorageGetObjIntegration;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};