/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StorageMeetReadItem } from "./storage-meet-read-item";

export type StorageConfigMeetReadItem = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type object
    */
    storage: StorageMeetReadItem;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};