/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type SubscriptionPlanRequestDto = {
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type string | undefined
    */
    priceId?: string;
    /**
     * @default false
     * @type boolean | undefined
    */
    readonly free?: boolean;
};