/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AddressGetCurrentTenant } from "./address-get-current-tenant";

export const tenantGetCurrentTenantTenantTypeEnum = {
    company: "company",
    person: "person"
} as const;

export type TenantGetCurrentTenantTenantTypeEnumKey = (typeof tenantGetCurrentTenantTenantTypeEnum)[keyof typeof tenantGetCurrentTenantTenantTypeEnum];

export type TenantGetCurrentTenant = {
    /**
     * @type string | undefined, ulid
    */
    readonly id?: string;
    /**
     * @type string,null
    */
    name?: string | null;
    /**
     * @type string | undefined
    */
    subdomain?: string;
    /**
     * @type string | undefined
    */
    tenantType?: TenantGetCurrentTenantTenantTypeEnumKey;
    /**
     * @type object | undefined
    */
    billingAddress?: AddressGetCurrentTenant;
};