/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";

export const ApiIntegrationsIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("Integration identifier")
    })

/**
 * @description Integration resource deleted
 */
export const ApiIntegrationsIdDelete204Schema = z.any()

/**
 * @description Forbidden
 */
export const ApiIntegrationsIdDelete403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiIntegrationsIdDelete404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiIntegrationsIdDeleteMutationResponseSchema = z.lazy(() => ApiIntegrationsIdDelete204Schema)