/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { IntegrationSetIntegrationSchema } from "../integration-set-integration-schema";
import { IntegrationJsonldGetObjIntegrationSchema } from "./jsonld-get-obj-integration-schema";

/**
 * @description Integration resource created
 */
export const ApiIntegrationsPost201Schema = z.lazy(() => IntegrationJsonldGetObjIntegrationSchema)

/**
 * @description Invalid input
 */
export const ApiIntegrationsPost400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiIntegrationsPost422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new Integration resource
 */
export const ApiIntegrationsPostMutationRequestSchema = z.lazy(() => IntegrationSetIntegrationSchema)

export const ApiIntegrationsPostMutationResponseSchema = z.lazy(() => ApiIntegrationsPost201Schema)