/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ProviderConfigFormDataGetObjIntegrationSchema } from "../provider-config/form-data-get-obj-integration-schema";
import { RecorderConfigFormDataGetObjIntegrationSchema } from "../recorder-config/form-data-get-obj-integration-schema";
import { StorageConfigFormDataGetObjIntegrationSchema } from "../storage-config/form-data-get-obj-integration-schema";

export const IntegrationFormDataGetObjIntegrationSchema = z.object({
    "providerConfig": z.lazy(() => ProviderConfigFormDataGetObjIntegrationSchema),
"recorderConfig": z.lazy(() => RecorderConfigFormDataGetObjIntegrationSchema),
"storageConfig": z.lazy(() => StorageConfigFormDataGetObjIntegrationSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })