/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ProviderConfigHtmlGetCollectionIntegrationSchema } from "../provider-config/html-get-collection-integration-schema";
import { RecorderConfigHtmlGetCollectionIntegrationSchema } from "../recorder-config/html-get-collection-integration-schema";
import { StorageConfigHtmlGetCollectionIntegrationSchema } from "../storage-config/html-get-collection-integration-schema";

export const IntegrationHtmlGetCollectionIntegrationSchema = z.object({
    "providerConfig": z.lazy(() => ProviderConfigHtmlGetCollectionIntegrationSchema),
"recorderConfig": z.lazy(() => RecorderConfigHtmlGetCollectionIntegrationSchema),
"storageConfig": z.lazy(() => StorageConfigHtmlGetCollectionIntegrationSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })