/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ProviderConfigHtmlMeetReadItemSchema } from "../provider-config/html-meet-read-item-schema";
import { RecorderConfigHtmlMeetReadItemSchema } from "../recorder-config/html-meet-read-item-schema";
import { StorageConfigHtmlMeetReadItemSchema } from "../storage-config/html-meet-read-item-schema";

export const IntegrationHtmlMeetReadItemSchema = z.object({
    "providerConfig": z.lazy(() => ProviderConfigHtmlMeetReadItemSchema),
"recorderConfig": z.lazy(() => RecorderConfigHtmlMeetReadItemSchema),
"storageConfig": z.lazy(() => StorageConfigHtmlMeetReadItemSchema),
"id": z.optional(z.union([z.string(), z.string()])),
"name": z.optional(z.string())
    })