/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";
import { ProviderConfigJsonldGetCollectionIntegrationSchema } from "../provider-config/jsonld-get-collection-integration-schema";
import { RecorderConfigJsonldGetCollectionIntegrationSchema } from "../recorder-config/jsonld-get-collection-integration-schema";
import { StorageConfigJsonldGetCollectionIntegrationSchema } from "../storage-config/jsonld-get-collection-integration-schema";

export const IntegrationJsonldGetCollectionIntegrationSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "providerConfig": z.lazy(() => ProviderConfigJsonldGetCollectionIntegrationSchema),
"recorderConfig": z.lazy(() => RecorderConfigJsonldGetCollectionIntegrationSchema),
"storageConfig": z.lazy(() => StorageConfigJsonldGetCollectionIntegrationSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    }))