/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";

export const IntegrationJsonldSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "providerConfig": z.string(),
"recorderConfig": z.string(),
"storageConfig": z.string(),
"meets": z.optional(z.array(z.string())),
"id": z.optional(z.union([z.string(), z.string()])),
"dateCreate": z.optional(z.string().datetime()),
"dateUpdate": z.string().datetime().nullish(),
"name": z.optional(z.string()),
"providerDisplayName": z.optional(z.string()),
"recorderDisplayName": z.optional(z.string()),
"storageDisplayName": z.optional(z.string()),
"roles": z.optional(z.array(z.string().nullable())),
"userIdentifier": z.optional(z.string())
    }))