/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraCollectionBaseSchemaSchema } from "../hydra-collection-base-schema-schema";
import { PropertyJsonldPropertyCollectionReadSchema } from "./jsonld-property-collection-read-schema";

export const ApiPropertiesGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(100).default(10).describe("The number of items per page")
    })

/**
 * @description Property collection
 */
export const ApiPropertiesGetCollection200Schema = z.lazy(() => HydraCollectionBaseSchemaSchema).and(z.object({
    "member": z.array(z.lazy(() => PropertyJsonldPropertyCollectionReadSchema))
    })).describe("Property.jsonld-PropertyCollectionRead collection.")

export const ApiPropertiesGetCollectionQueryResponseSchema = z.lazy(() => ApiPropertiesGetCollection200Schema)