/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const PropertyFormDataPropertyValueItemReadSchema = z.object({
    "id": z.optional(z.union([z.string(), z.string()]))
    })