/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { HydraCollectionBaseSchemaSchema } from "../hydra-collection-base-schema-schema";
import { QuestionJsonldQuestionReadCollectionSchema } from "./jsonld-question-read-collection-schema";

export const ApiRecorderConfigsIdquestionsGetCollectionPathParamsSchema = z.object({
    "id": z.string().describe("Question identifier")
    })

export const ApiRecorderConfigsIdquestionsGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(100).default(10).describe("The number of items per page")
    })

/**
 * @description Question collection
 */
export const ApiRecorderConfigsIdquestionsGetCollection200Schema = z.lazy(() => HydraCollectionBaseSchemaSchema).and(z.object({
    "member": z.array(z.lazy(() => QuestionJsonldQuestionReadCollectionSchema))
    })).describe("Question.jsonld-QuestionReadCollection collection.")

/**
 * @description Forbidden
 */
export const ApiRecorderConfigsIdquestionsGetCollection403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiRecorderConfigsIdquestionsGetCollectionQueryResponseSchema = z.lazy(() => ApiRecorderConfigsIdquestionsGetCollection200Schema)