/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";

export const QuestionJsonldQuestionReadCollectionSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "text": z.string().describe("Текст вопроса"),
"file": z.string().describe("Файл").nullish(),
"answer": z.string().describe("Текст вопроса").nullish(),
"isRequireAnswer": z.optional(z.boolean().describe("Ответ на вопрос")),
"recorderConfig": z.optional(z.string().describe("Требует ли вопрос ответа")),
"id": z.optional(z.union([z.string(), z.string()]))
    }))