/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { MultipartUploadMultipartInitRequestDtoSetSchema } from "./multipart-init-request-dto-set-schema";
import { MultipartUploadMultipartInitResponseDtoJsonldSchema } from "./multipart-init-response-dto/jsonld-schema";

/**
 * @description MultipartUpload resource created
 */
export const ApiMultipartinitPost201Schema = z.lazy(() => MultipartUploadMultipartInitResponseDtoJsonldSchema)

/**
 * @description Invalid input
 */
export const ApiMultipartinitPost400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiMultipartinitPost403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiMultipartinitPost422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new MultipartUpload resource
 */
export const ApiMultipartinitPostMutationRequestSchema = z.lazy(() => MultipartUploadMultipartInitRequestDtoSetSchema)

export const ApiMultipartinitPostMutationResponseSchema = z.lazy(() => ApiMultipartinitPost201Schema)