/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const MultipartUploadMultipartInitResponseDtoSchema = z.object({
    "uploadId": z.optional(z.string()),
"chunkSize": z.optional(z.number().int()),
"totalChunks": z.optional(z.number().int()),
"uploadedChunks": z.optional(z.array(z.string().nullable())),
"progress": z.optional(z.number().int()),
"expiresAt": z.optional(z.string().datetime()),
"resumed": z.optional(z.boolean())
    })