/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";

export type SubscriptionPlanRequestDtoJsonld = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type string | undefined
    */
    priceId?: string;
    /**
     * @default false
     * @type boolean | undefined
    */
    readonly free?: boolean;
});