/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../../hydra-item-base-schema";

export const propertyJsonldStorageConfigDetailGetIdTypeEnum = {
    string: "string",
    number: "number",
    bool: "bool"
} as const;

export type PropertyJsonldStorageConfigDetailGetIdTypeEnumKey = (typeof propertyJsonldStorageConfigDetailGetIdTypeEnum)[keyof typeof propertyJsonldStorageConfigDetailGetIdTypeEnum];

export type PropertyJsonldStorageConfigDetailGetId = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @default "string"
     * @type string,null
    */
    type?: PropertyJsonldStorageConfigDetailGetIdTypeEnumKey | null;
    /**
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});