/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

/**
 * @description Использует refresh_token для получения новой пары токенов от Keycloak
 */
export const TokenTokenRefreshRequestDtoJsonMergePatchSchema = z.object({
    "refreshToken": z.optional(z.string())
    }).describe("Использует refresh_token для получения новой пары токенов от Keycloak")