/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PropertyValueRecorderConfigWriteJsonMergePatch = {
    /**
     * @type string,null
    */
    value?: string | null;
    /**
     * @type string | undefined, iri-reference
    */
    property?: string;
};