/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { PropertyValueFormDataStorageConfigDetailGetIdSchema } from "../../property-value/form-data-storage-config/detail-get-id-schema";
import { StorageFormDataStorageConfigDetailGetIdSchema } from "../../storage/form-data-storage-config/detail-get-id-schema";

export const StorageConfigFormDataStorageConfigDetailGetIdSchema = z.object({
    "name": z.string(),
"storage": z.lazy(() => StorageFormDataStorageConfigDetailGetIdSchema),
"propertyValues": z.array(z.lazy(() => PropertyValueFormDataStorageConfigDetailGetIdSchema)),
"id": z.optional(z.union([z.string(), z.string()]))
    })