/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const FileMediaTaskUpdateReadSchema = z.object({
    "originalName": z.optional(z.string()),
"duration": z.number().int().nullish()
    })