/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const HydraItemBaseSchemaSchema = z.object({
    "@context": z.optional(z.union([z.string(), z.object({
    "@vocab": z.string(),
"hydra": z.enum(["http://www.w3.org/ns/hydra/core#"])
    }).catchall(z.any())])),
"@id": z.string(),
"@type": z.string()
    })