/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ProviderConfigGetObjIntegrationSchema } from "./provider-config-get-obj-integration-schema";
import { RecorderConfigGetObjIntegrationSchema } from "./recorder-config-get-obj-integration-schema";
import { StorageConfigGetObjIntegrationSchema } from "./storage-config-get-obj-integration-schema";

export const IntegrationGetObjIntegrationSchema = z.object({
    "providerConfig": z.lazy(() => ProviderConfigGetObjIntegrationSchema),
"recorderConfig": z.lazy(() => RecorderConfigGetObjIntegrationSchema),
"storageConfig": z.lazy(() => StorageConfigGetObjIntegrationSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })