/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const MediaTaskSchema = z.object({
    "file": z.string().nullish(),
"user": z.string().nullish(),
"transcriptionResult": z.string().nullish(),
"summaryResult": z.string().nullish(),
"statuses": z.optional(z.array(z.string())),
"status": z.optional(z.enum(["CREATED", "TRANSCRIBE", "TRANSCRIBE_COMPLETED", "TRANSCRIBE_ERROR", "SUMMARY", "SUMMARY_COMPLETED", "SUMMARY_ERROR"]).default("CREATED")),
"traceId": z.string().nullish(),
"duration": z.number().int().nullish(),
"id": z.optional(z.union([z.string(), z.string()])),
"dateCreate": z.optional(z.string().datetime()),
"dateUpdate": z.string().datetime().nullish(),
"roles": z.optional(z.array(z.string().nullable())),
"userIdentifier": z.optional(z.string())
    })