/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { IntegrationMeetCreateReadSchema } from "./integration-meet-create-read-schema";
import { ProviderConfigMeetCreateReadSchema } from "./provider-config-meet-create-read-schema";
import { RecorderConfigMeetCreateReadSchema } from "./recorder-config-meet-create-read-schema";
import { RecorderMeetCreateReadSchema } from "./recorder-meet-create-read-schema";
import { StorageConfigMeetCreateReadSchema } from "./storage-config-meet-create-read-schema";
import { UserMeetCreateReadSchema } from "./user-meet-create-read-schema";

export const MeetMeetCreateReadSchema = z.object({
    "integration": z.optional(z.union([z.lazy(() => IntegrationMeetCreateReadSchema), z.null()])),
"url": z.optional(z.string()),
"resultUrl": z.string().nullish(),
"archiveUrl": z.string().nullish(),
"name": z.string().nullish(),
"recorder": z.optional(z.union([z.lazy(() => RecorderMeetCreateReadSchema), z.null()])),
"meetStartAt": z.string().datetime().nullish(),
"meetEndAt": z.string().datetime().nullish(),
"icalUid": z.string().nullish(),
"traceId": z.string().nullish(),
"participants": z.array(z.string().nullable()).nullish(),
"status": z.enum(["FOUND", "PREPARING", "TIME_CHANGED", "RECORDING", "RECORDING_PAUSED", "RECORDING_COMPLETED", "UPLOADING", "POSTPROCESSING", "EXTERNAL_UPLOAD", "COMPLETED", "ERROR", "TRANSCRIBE", "TRANSCRIBE_COMPLETED", "TRANSCRIBE_ERROR", "SUMMARY", "SUMMARY_COMPLETED", "SUMMARY_ERROR"]).default("FOUND").nullish(),
"user": z.optional(z.union([z.lazy(() => UserMeetCreateReadSchema), z.null()])),
"token": z.string().nullish(),
"videoLinkResult": z.string().nullish(),
"transcriptionResult": z.string().nullish(),
"summaryResult": z.string().nullish(),
"providerConfig": z.optional(z.union([z.lazy(() => ProviderConfigMeetCreateReadSchema), z.null()])),
"storageConfig": z.optional(z.union([z.lazy(() => StorageConfigMeetCreateReadSchema), z.null()])),
"recorderConfig": z.optional(z.union([z.lazy(() => RecorderConfigMeetCreateReadSchema), z.null()])),
"transcription": z.boolean().nullish(),
"summarization": z.boolean().nullish(),
"duration": z.optional(z.number().int().default(0)),
"id": z.optional(z.union([z.string(), z.string()]))
    })