/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ProductGetItemPaymentSchema } from "./product-get-item-payment-schema";
import { SubscriptionGetItemPaymentSchema } from "./subscription-get-item-payment-schema";
import { TenantGetItemPaymentSchema } from "./tenant-get-item-payment-schema";

export const PaymentGetItemPaymentSchema = z.object({
    "customer": z.optional(z.union([z.lazy(() => TenantGetItemPaymentSchema), z.null()])),
"status": z.enum(["pending", "completed", "disputed", "partially_refunded", "fully_refunded", "failed", "overdue"]),
"amount": z.number().int().min(1).max(100000000).gt(0),
"currency": z.string().min(3).max(3),
"paymentProviderDetailsUrl": z.string().url().max(500).nullish(),
"subscription": z.optional(z.union([z.lazy(() => SubscriptionGetItemPaymentSchema), z.null()])),
"product": z.optional(z.union([z.lazy(() => ProductGetItemPaymentSchema), z.null()])),
"id": z.optional(z.string()),
"createdAt": z.optional(z.string().datetime())
    })