/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const PriceGetCurrentSubscriptionSchema = z.object({
    "id": z.optional(z.any()),
"amount": z.number().int().nullish(),
"currency": z.optional(z.string())
    })