/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { PropertyProviderConfigItemReadSchema } from "./property-provider-config-item-read-schema";

export const PropertyValueProviderConfigItemReadSchema = z.object({
    "value": z.string().nullish(),
"property": z.lazy(() => PropertyProviderConfigItemReadSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })