/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ProviderGetObjIntegrationSchema } from "./provider-get-obj-integration-schema";

export const ProviderConfigGetObjIntegrationSchema = z.object({
    "name": z.string(),
"provider": z.lazy(() => ProviderGetObjIntegrationSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })