/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { PropertyValueProviderConfigItemWriteJsonMergePatchSchema } from "./property-value-provider-config-item-write/json-merge-patch-schema";
import { ProviderProviderConfigItemWriteSchema } from "./provider-provider-config-item-write-schema";

export const ProviderConfigProviderConfigItemWriteSchema = z.object({
    "name": z.string(),
"isActive": z.optional(z.boolean().default(true)),
"provider": z.lazy(() => ProviderProviderConfigItemWriteSchema),
"propertyValues": z.array(z.lazy(() => PropertyValueProviderConfigItemWriteJsonMergePatchSchema)),
"id": z.optional(z.union([z.string(), z.string()]))
    })