/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { PropertyProviderItemReadSchema } from "./property-provider-item-read-schema";

export const ProviderProviderItemReadSchema = z.object({
    "name": z.optional(z.string()),
"slug": z.string().nullish(),
"templateProperties": z.optional(z.array(z.lazy(() => PropertyProviderItemReadSchema))),
"id": z.optional(z.union([z.string(), z.string()]))
    })