/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ProviderMeetReadItemSchema } from "./provider-meet-read-item-schema";

export const ProviderConfigMeetReadItemSchema = z.object({
    "name": z.string(),
"provider": z.lazy(() => ProviderMeetReadItemSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })