/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const QuestionQuestionPostCreateSchema = z.object({
    "text": z.string().describe("Текст вопроса"),
"file": z.string().describe("Файл").nullish(),
"isRequireAnswer": z.optional(z.boolean().describe("Ответ на вопрос")),
"recorderConfig": z.optional(z.string().describe("Требует ли вопрос ответа")),
"id": z.optional(z.union([z.string(), z.string()]))
    })