/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { PropertyValueRecorderConfigReadItemSchema } from "./property-value-recorder-config-read-item-schema";
import { RecorderRecorderConfigReadItemSchema } from "./recorder-recorder-config-read-item-schema";

export const RecorderConfigRecorderConfigReadItemSchema = z.object({
    "name": z.string(),
"isActive": z.boolean().default(true),
"recorder": z.union([z.lazy(() => RecorderRecorderConfigReadItemSchema), z.null()]),
"propertyValues": z.array(z.lazy(() => PropertyValueRecorderConfigReadItemSchema)),
"status": z.optional(z.enum(["NOT_REQUIRE_AUTHORIZATION", "WAITING_AUTHORIZATION", "RECORDER_PROCESS_AUTHORIZATION", "ERROR_AUTHORIZATION", "AUTHORIZED"]).default("NOT_REQUIRE_AUTHORIZATION").describe("Статус")),
"isGlobal": z.optional(z.boolean().default(false)),
"id": z.optional(z.union([z.string(), z.string()]))
    })