/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { RecorderGetObjIntegrationSchema } from "./recorder-get-obj-integration-schema";

export const RecorderConfigGetObjIntegrationSchema = z.object({
    "name": z.string(),
"recorder": z.union([z.lazy(() => RecorderGetObjIntegrationSchema), z.null()]),
"id": z.optional(z.union([z.string(), z.string()]))
    })