/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { PropertyValueRecorderConfigWriteJsonMergePatchSchema } from "./property-value-recorder-config-write/json-merge-patch-schema";

export const RecorderConfigRecorderConfigWriteSchema = z.object({
    "name": z.string(),
"isActive": z.boolean().default(true),
"recorder": z.nullable(z.string()),
"propertyValues": z.array(z.lazy(() => PropertyValueRecorderConfigWriteJsonMergePatchSchema))
    })