/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { StorageConfigErrorSchema } from "./storage-config-error-schema";

export const StorageConfigSchema = z.object({
    "name": z.string(),
"isActive": z.boolean().default(true),
"storage": z.string(),
"propertyValues": z.array(z.string()),
"errors": z.optional(z.array(z.lazy(() => StorageConfigErrorSchema))),
"isGlobal": z.optional(z.boolean().default(false)),
"id": z.optional(z.union([z.string(), z.string()])),
"dateCreate": z.optional(z.string().datetime()),
"dateUpdate": z.string().datetime().nullish()
    })