/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { StorageMeetCreateReadSchema } from "./storage-meet-create-read-schema";

export const StorageConfigMeetCreateReadSchema = z.object({
    "name": z.string(),
"storage": z.lazy(() => StorageMeetCreateReadSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })