/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { StorageMeetUpdateReadSchema } from "./storage-meet-update-read-schema";

export const StorageConfigMeetUpdateReadSchema = z.object({
    "name": z.string(),
"storage": z.lazy(() => StorageMeetUpdateReadSchema)
    })