/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { StorageGetCollectionIntegrationSchema } from "./storage-get-collection-integration-schema";

export const StorageConfigGetCollectionIntegrationSchema = z.object({
    "name": z.string(),
"storage": z.lazy(() => StorageGetCollectionIntegrationSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })