/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { StorageGetObjIntegrationSchema } from "./storage-get-obj-integration-schema";

export const StorageConfigGetObjIntegrationSchema = z.object({
    "name": z.string(),
"storage": z.lazy(() => StorageGetObjIntegrationSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })