/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { PriceGetCollectionSubscriptionPlanSchema } from "./price-get-collection-subscription-plan-schema";
import { ProductGetCollectionSubscriptionPlanSchema } from "./product-get-collection-subscription-plan-schema";
import { SubscriptionFeatureGetCollectionSubscriptionPlanSchema } from "./subscription-feature-get-collection-subscription-plan-schema";

export const SubscriptionPlanGetCollectionSubscriptionPlanSchema = z.object({
    "features": z.optional(z.array(z.lazy(() => SubscriptionFeatureGetCollectionSubscriptionPlanSchema))),
"public": z.optional(z.boolean().default(false)),
"name": z.optional(z.string()),
"free": z.optional(z.boolean().default(false)),
"userCount": z.optional(z.number().int().default(1)),
"prices": z.optional(z.array(z.lazy(() => PriceGetCollectionSubscriptionPlanSchema))),
"product": z.optional(z.union([z.lazy(() => ProductGetCollectionSubscriptionPlanSchema), z.null()])),
"id": z.optional(z.string())
    })