/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const SubscriptionGetItemPaymentSchema = z.object({
    "planName": z.string().nullish(),
"id": z.optional(z.any()),
"endedAt": z.string().datetime().nullish(),
"createdAt": z.string().datetime().nullish()
    })