/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const TeamGetCurrentTeamSchema = z.object({
    "tokens": z.number().nullish(),
"id": z.optional(z.any()),
"name": z.string().nullish(),
"billingEmail": z.optional(z.string()),
"createdAt": z.optional(z.string().datetime())
    })