/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const UserMeetReadItemSchema = z.object({
    "id": z.optional(z.union([z.string(), z.string()])),
"email": z.string().email()
    })