/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { ProviderJsonldProviderItemRead } from "./jsonld-provider-item-read";

export type ApiProvidersIdGetPathParams = {
    /**
     * @description Provider identifier
     * @type string
    */
    id: string;
};

/**
 * @description Provider resource
*/
export type ApiProvidersIdGet200 = ProviderJsonldProviderItemRead;

/**
 * @description Not found
*/
export type ApiProvidersIdGet404 = ErrorJsonld;

export type ApiProvidersIdGetQueryResponse = ApiProvidersIdGet200;

export type ApiProvidersIdGetQuery = {
    Response: ApiProvidersIdGet200;
    PathParams: ApiProvidersIdGetPathParams;
    Errors: ApiProvidersIdGet404;
};