/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { HydraCollectionBaseSchema } from "../hydra-collection-base-schema";
import type { ProviderJsonldProviderCollectionRead } from "./jsonld-provider-collection-read";

export type ApiProvidersGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 100
     * @default 10
     * @type integer | undefined
    */
    itemsPerPage?: number;
};

/**
 * @description Provider collection
*/
export type ApiProvidersGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: ProviderJsonldProviderCollectionRead[];
});

/**
 * @description Forbidden
*/
export type ApiProvidersGetCollection403 = ErrorJsonld;

export type ApiProvidersGetCollectionQueryResponse = ApiProvidersGetCollection200;

export type ApiProvidersGetCollectionQuery = {
    Response: ApiProvidersGetCollection200;
    QueryParams: ApiProvidersGetCollectionQueryParams;
    Errors: ApiProvidersGetCollection403;
};