/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyFormDataProviderItemRead } from "../property/form-data-provider-item-read";

export type ProviderFormDataProviderItemRead = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @type array | undefined
    */
    templateProperties?: PropertyFormDataProviderItemRead[];
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};