/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";

export type ProviderJsonldMeetReadItem = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});