/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../../hydra-item-base-schema-schema";

export const MultipartUploadMultipartStatusResponseDtoJsonldSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "status": z.optional(z.array(z.string().nullable()))
    }))