/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const MeetRequestDtoHtmlSchema = z.object({
    "id": z.optional(z.string()),
"meetId": z.optional(z.string())
    })