/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiPropertyValuesIdPatchMutationResponse, ApiPropertyValuesIdPatch400, ApiPropertyValuesIdPatch403, ApiPropertyValuesIdPatch404, ApiPropertyValuesIdPatch422 } from "../../models/property-value/api-property-values-id-patch";
import { http } from "msw";

export function ApiPropertyValuesIdPatchHandlerResponse200(data: ApiPropertyValuesIdPatchMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiPropertyValuesIdPatchHandlerResponse400(data: ApiPropertyValuesIdPatch400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiPropertyValuesIdPatchHandlerResponse403(data: ApiPropertyValuesIdPatch403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiPropertyValuesIdPatchHandlerResponse404(data: ApiPropertyValuesIdPatch404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiPropertyValuesIdPatchHandlerResponse422(data: ApiPropertyValuesIdPatch422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiPropertyValuesIdPatchHandler(data?: ApiPropertyValuesIdPatchMutationResponse | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.patch(`/api/v1/property_values/:id`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}