/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiStorageConfigsIdDeleteMutationResponse, ApiStorageConfigsIdDeletePathParams } from "../../models";

function getApiStorageConfigsIdDeleteUrl(params: ApiStorageConfigsIdDeletePathParams) {
  return `/api/v1/storage_configs/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Removes the StorageConfig resource.
 * @description Removes the StorageConfig resource.
 * {@link /api/v1/storage_configs/{id}}
 */
export const apiStorageConfigsIdDelete = (
  args: {
    params: ApiStorageConfigsIdDeletePathParams;
  },
  options?: RequestOptions,
): Promise<ApiStorageConfigsIdDeleteMutationResponse> => {
  return http.delete(getApiStorageConfigsIdDeleteUrl(args.params), {
    ...options,
  }).json<ApiStorageConfigsIdDeleteMutationResponse>();
};