/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiStorageConfigsIdGetQueryResponse, ApiStorageConfigsIdGetPathParams } from "../../models";

function getApiStorageConfigsIdGetUrl(params: ApiStorageConfigsIdGetPathParams) {
  return `/api/v1/storage_configs/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Retrieves a StorageConfig resource.
 * @description Retrieves a StorageConfig resource.
 * {@link /api/v1/storage_configs/{id}}
 */
export const apiStorageConfigsIdGet = (
  args: {
    params: ApiStorageConfigsIdGetPathParams;
  },
  options?: RequestOptions,
): Promise<ApiStorageConfigsIdGetQueryResponse> => {
  return http.get(getApiStorageConfigsIdGetUrl(args.params), {
    ...options,
  }).json<ApiStorageConfigsIdGetQueryResponse>();
};