/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiStorageConfigsIdPatchMutationResponse, ApiStorageConfigsIdPatchPathParams, ApiStorageConfigsIdPatchMutationRequest } from "../../models";

function getApiStorageConfigsIdPatchUrl(params: ApiStorageConfigsIdPatchPathParams) {
  return `/api/v1/storage_configs/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Updates the StorageConfig resource.
 * @description Updates the StorageConfig resource.
 * {@link /api/v1/storage_configs/{id}}
 */
export const apiStorageConfigsIdPatch = (
  args: {
    params: ApiStorageConfigsIdPatchPathParams;
    body: ApiStorageConfigsIdPatchMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiStorageConfigsIdPatchMutationResponse> => {
  return http.patch(getApiStorageConfigsIdPatchUrl(args.params), {
    ...options,
    json: args.body,
  }).json<ApiStorageConfigsIdPatchMutationResponse>();
};