/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "../constraint-violation/jsonld";
import type { ErrorJsonld } from "../error/jsonld";
import type { MediaTaskJsonMergePatch } from "./json-merge-patch";
import type { MediaTaskJsonldGetItemMediaTask } from "./jsonld-get-item-media-task";

export type ApiMediaTasksIdtranscribePatchPathParams = {
    /**
     * @description MediaTask identifier
     * @type string
    */
    id: string;
};

/**
 * @description MediaTask resource updated
*/
export type ApiMediaTasksIdtranscribePatch200 = MediaTaskJsonldGetItemMediaTask;

/**
 * @description Invalid input
*/
export type ApiMediaTasksIdtranscribePatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiMediaTasksIdtranscribePatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiMediaTasksIdtranscribePatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiMediaTasksIdtranscribePatch422 = ConstraintViolationJsonld;

/**
 * @description The updated MediaTask resource
*/
export type ApiMediaTasksIdtranscribePatchMutationRequest = Omit<NonNullable<MediaTaskJsonMergePatch>, "dateCreate" | "dateUpdate" | "roles" | "userIdentifier">;

export type ApiMediaTasksIdtranscribePatchMutationResponse = ApiMediaTasksIdtranscribePatch200;

export type ApiMediaTasksIdtranscribePatchMutation = {
    Response: ApiMediaTasksIdtranscribePatch200;
    Request: ApiMediaTasksIdtranscribePatchMutationRequest;
    PathParams: ApiMediaTasksIdtranscribePatchPathParams;
    Errors: ApiMediaTasksIdtranscribePatch400 | ApiMediaTasksIdtranscribePatch403 | ApiMediaTasksIdtranscribePatch404 | ApiMediaTasksIdtranscribePatch422;
};