/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "../constraint-violation/jsonld";
import type { ErrorJsonld } from "../error/jsonld";
import type { MediaTaskJsonld } from "./jsonld";
import type { MediaTaskMediaTaskBulkRequestDto } from "./media-task-bulk-request-dto";

/**
 * @description MediaTask resource created
*/
export type ApiMediaTasksmassDeletePost201 = MediaTaskJsonld;

/**
 * @description Invalid input
*/
export type ApiMediaTasksmassDeletePost400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiMediaTasksmassDeletePost403 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiMediaTasksmassDeletePost422 = ConstraintViolationJsonld;

/**
 * @description The new MediaTask resource
*/
export type ApiMediaTasksmassDeletePostMutationRequest = MediaTaskMediaTaskBulkRequestDto;

export type ApiMediaTasksmassDeletePostMutationResponse = ApiMediaTasksmassDeletePost201;

export type ApiMediaTasksmassDeletePostMutation = {
    Response: ApiMediaTasksmassDeletePost201;
    Request: ApiMediaTasksmassDeletePostMutationRequest;
    Errors: ApiMediaTasksmassDeletePost400 | ApiMediaTasksmassDeletePost403 | ApiMediaTasksmassDeletePost422;
};