/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "../constraint-violation/jsonld";
import type { ErrorJsonld } from "../error/jsonld";
import type { MediaTaskJsonMergePatch } from "./json-merge-patch";
import type { MediaTaskJsonldMediaTaskUpdate } from "./jsonld-media-task-update";

export type ApiMediaTasksIddownloadtranscribePatchPathParams = {
    /**
     * @description MediaTask identifier
     * @type string
    */
    id: string;
};

/**
 * @description MediaTask resource updated
*/
export type ApiMediaTasksIddownloadtranscribePatch200 = MediaTaskJsonldMediaTaskUpdate;

/**
 * @description Invalid input
*/
export type ApiMediaTasksIddownloadtranscribePatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiMediaTasksIddownloadtranscribePatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiMediaTasksIddownloadtranscribePatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiMediaTasksIddownloadtranscribePatch422 = ConstraintViolationJsonld;

/**
 * @description The updated MediaTask resource
*/
export type ApiMediaTasksIddownloadtranscribePatchMutationRequest = Omit<NonNullable<MediaTaskJsonMergePatch>, "dateCreate" | "dateUpdate" | "roles" | "userIdentifier">;

export type ApiMediaTasksIddownloadtranscribePatchMutationResponse = ApiMediaTasksIddownloadtranscribePatch200;

export type ApiMediaTasksIddownloadtranscribePatchMutation = {
    Response: ApiMediaTasksIddownloadtranscribePatch200;
    Request: ApiMediaTasksIddownloadtranscribePatchMutationRequest;
    PathParams: ApiMediaTasksIddownloadtranscribePatchPathParams;
    Errors: ApiMediaTasksIddownloadtranscribePatch400 | ApiMediaTasksIddownloadtranscribePatch403 | ApiMediaTasksIddownloadtranscribePatch404 | ApiMediaTasksIddownloadtranscribePatch422;
};