/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { MediaTaskJsonldGetItemMediaTask } from "./jsonld-get-item-media-task";

export type ApiMediaTasksIdGetPathParams = {
    /**
     * @description MediaTask identifier
     * @type string
    */
    id: string;
};

/**
 * @description MediaTask resource
*/
export type ApiMediaTasksIdGet200 = MediaTaskJsonldGetItemMediaTask;

/**
 * @description Forbidden
*/
export type ApiMediaTasksIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiMediaTasksIdGet404 = ErrorJsonld;

export type ApiMediaTasksIdGetQueryResponse = ApiMediaTasksIdGet200;

export type ApiMediaTasksIdGetQuery = {
    Response: ApiMediaTasksIdGet200;
    PathParams: ApiMediaTasksIdGetPathParams;
    Errors: ApiMediaTasksIdGet403 | ApiMediaTasksIdGet404;
};