/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "../constraint-violation/jsonld";
import type { ErrorJsonld } from "../error/jsonld";
import type { MediaTaskMediaTaskUpdateJsonMergePatch } from "../media-task-media-task-update/json-merge-patch";
import type { MediaTaskJsonldMediaTaskUpdateRead } from "./jsonld-media-task-update-read";

export type ApiMediaTasksIdPatchPathParams = {
    /**
     * @description MediaTask identifier
     * @type string
    */
    id: string;
};

/**
 * @description MediaTask resource updated
*/
export type ApiMediaTasksIdPatch200 = MediaTaskJsonldMediaTaskUpdateRead;

/**
 * @description Invalid input
*/
export type ApiMediaTasksIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiMediaTasksIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiMediaTasksIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiMediaTasksIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated MediaTask resource
*/
export type ApiMediaTasksIdPatchMutationRequest = MediaTaskMediaTaskUpdateJsonMergePatch;

export type ApiMediaTasksIdPatchMutationResponse = ApiMediaTasksIdPatch200;

export type ApiMediaTasksIdPatchMutation = {
    Response: ApiMediaTasksIdPatch200;
    Request: ApiMediaTasksIdPatchMutationRequest;
    PathParams: ApiMediaTasksIdPatchPathParams;
    Errors: ApiMediaTasksIdPatch400 | ApiMediaTasksIdPatch403 | ApiMediaTasksIdPatch404 | ApiMediaTasksIdPatch422;
};