/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const mediaTaskFormDataMediaTaskUpdateStatusEnum = {
    CREATED: "CREATED",
    TRANSCRIBE: "TRANSCRIBE",
    TRANSCRIBE_COMPLETED: "TRANSCRIBE_COMPLETED",
    TRANSCRIBE_ERROR: "TRANSCRIBE_ERROR",
    SUMMARY: "SUMMARY",
    SUMMARY_COMPLETED: "SUMMARY_COMPLETED",
    SUMMARY_ERROR: "SUMMARY_ERROR"
} as const;

export type MediaTaskFormDataMediaTaskUpdateStatusEnumKey = (typeof mediaTaskFormDataMediaTaskUpdateStatusEnum)[keyof typeof mediaTaskFormDataMediaTaskUpdateStatusEnum];

export type MediaTaskFormDataMediaTaskUpdate = {
    /**
     * @type string,null
    */
    transcriptionResult?: string | null;
    /**
     * @type string,null
    */
    summaryResult?: string | null;
    /**
     * @default "CREATED"
     * @type string | undefined
    */
    status?: MediaTaskFormDataMediaTaskUpdateStatusEnumKey;
};