/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FileFormDataGetCollectionMediaTasks } from "../file/form-data-get-collection-media-tasks";

export const mediaTaskFormDataGetCollectionMediaTasksStatusEnum = {
    CREATED: "CREATED",
    TRANSCRIBE: "TRANSCRIBE",
    TRANSCRIBE_COMPLETED: "TRANSCRIBE_COMPLETED",
    TRANSCRIBE_ERROR: "TRANSCRIBE_ERROR",
    SUMMARY: "SUMMARY",
    SUMMARY_COMPLETED: "SUMMARY_COMPLETED",
    SUMMARY_ERROR: "SUMMARY_ERROR"
} as const;

export type MediaTaskFormDataGetCollectionMediaTasksStatusEnumKey = (typeof mediaTaskFormDataGetCollectionMediaTasksStatusEnum)[keyof typeof mediaTaskFormDataGetCollectionMediaTasksStatusEnum];

export type MediaTaskFormDataGetCollectionMediaTasks = {
    file?: (FileFormDataGetCollectionMediaTasks | null);
    /**
     * @default "CREATED"
     * @type string | undefined
    */
    status?: MediaTaskFormDataGetCollectionMediaTasksStatusEnumKey;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined, date-time
    */
    readonly dateCreate?: string;
};