/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const mediaTaskFormDataStatusEnum = {
    CREATED: "CREATED",
    TRANSCRIBE: "TRANSCRIBE",
    TRANSCRIBE_COMPLETED: "TRANSCRIBE_COMPLETED",
    TRANSCRIBE_ERROR: "TRANSCRIBE_ERROR",
    SUMMARY: "SUMMARY",
    SUMMARY_COMPLETED: "SUMMARY_COMPLETED",
    SUMMARY_ERROR: "SUMMARY_ERROR"
} as const;

export type MediaTaskFormDataStatusEnumKey = (typeof mediaTaskFormDataStatusEnum)[keyof typeof mediaTaskFormDataStatusEnum];

export type MediaTaskFormData = {
    /**
     * @type string,null, iri-reference
    */
    file?: string | null;
    /**
     * @type string,null, iri-reference
    */
    user?: string | null;
    /**
     * @type string,null
    */
    transcriptionResult?: string | null;
    /**
     * @type string,null
    */
    summaryResult?: string | null;
    /**
     * @type array | undefined
    */
    statuses?: string[];
    /**
     * @default "CREATED"
     * @type string | undefined
    */
    status?: MediaTaskFormDataStatusEnumKey;
    /**
     * @type string,null
    */
    traceId?: string | null;
    /**
     * @type integer,null
    */
    duration?: number | null;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined, date-time
    */
    readonly dateCreate?: string;
    /**
     * @type string,null, date-time
    */
    readonly dateUpdate?: string | null;
    /**
     * @type array | undefined
    */
    readonly roles?: string[];
    /**
     * @type string | undefined
    */
    readonly userIdentifier?: string;
};