/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FileHtmlGetCollectionMediaTasks } from "../file/html-get-collection-media-tasks";

export const mediaTaskHtmlGetCollectionMediaTasksStatusEnum = {
    CREATED: "CREATED",
    TRANSCRIBE: "TRANSCRIBE",
    TRANSCRIBE_COMPLETED: "TRANSCRIBE_COMPLETED",
    TRANSCRIBE_ERROR: "TRANSCRIBE_ERROR",
    SUMMARY: "SUMMARY",
    SUMMARY_COMPLETED: "SUMMARY_COMPLETED",
    SUMMARY_ERROR: "SUMMARY_ERROR"
} as const;

export type MediaTaskHtmlGetCollectionMediaTasksStatusEnumKey = (typeof mediaTaskHtmlGetCollectionMediaTasksStatusEnum)[keyof typeof mediaTaskHtmlGetCollectionMediaTasksStatusEnum];

export type MediaTaskHtmlGetCollectionMediaTasks = {
    file?: (FileHtmlGetCollectionMediaTasks | null);
    /**
     * @default "CREATED"
     * @type string | undefined
    */
    status?: MediaTaskHtmlGetCollectionMediaTasksStatusEnumKey;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined, date-time
    */
    readonly dateCreate?: string;
};