/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MediaTaskHtmlMediaTaskCreate = {
    /**
     * @type string,null, iri-reference
    */
    file?: string | null;
};