/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FileHtmlGetItemMediaTask } from "../file/html-get-item-media-task";
import type { UserHtmlGetItemMediaTask } from "../user/html-get-item-media-task";

export const mediaTaskHtmlGetItemMediaTaskStatusEnum = {
    CREATED: "CREATED",
    TRANSCRIBE: "TRANSCRIBE",
    TRANSCRIBE_COMPLETED: "TRANSCRIBE_COMPLETED",
    TRANSCRIBE_ERROR: "TRANSCRIBE_ERROR",
    SUMMARY: "SUMMARY",
    SUMMARY_COMPLETED: "SUMMARY_COMPLETED",
    SUMMARY_ERROR: "SUMMARY_ERROR"
} as const;

export type MediaTaskHtmlGetItemMediaTaskStatusEnumKey = (typeof mediaTaskHtmlGetItemMediaTaskStatusEnum)[keyof typeof mediaTaskHtmlGetItemMediaTaskStatusEnum];

export type MediaTaskHtmlGetItemMediaTask = {
    file?: (FileHtmlGetItemMediaTask | null);
    user?: (UserHtmlGetItemMediaTask | null);
    /**
     * @type string,null
    */
    transcriptionResult?: string | null;
    /**
     * @type string,null
    */
    summaryResult?: string | null;
    /**
     * @default "CREATED"
     * @type string | undefined
    */
    status?: MediaTaskHtmlGetItemMediaTaskStatusEnumKey;
    /**
     * @type string,null
    */
    traceId?: string | null;
    /**
     * @type integer,null
    */
    duration?: number | null;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined, date-time
    */
    readonly dateCreate?: string;
};