/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FileJsonldGetItemMediaTask } from "../file/jsonld-get-item-media-task";
import type { HydraItemBaseSchema } from "../hydra-item-base-schema";
import type { UserJsonldGetItemMediaTask } from "../user/jsonld-get-item-media-task";

export const mediaTaskJsonldGetItemMediaTaskStatusEnum = {
    CREATED: "CREATED",
    TRANSCRIBE: "TRANSCRIBE",
    TRANSCRIBE_COMPLETED: "TRANSCRIBE_COMPLETED",
    TRANSCRIBE_ERROR: "TRANSCRIBE_ERROR",
    SUMMARY: "SUMMARY",
    SUMMARY_COMPLETED: "SUMMARY_COMPLETED",
    SUMMARY_ERROR: "SUMMARY_ERROR"
} as const;

export type MediaTaskJsonldGetItemMediaTaskStatusEnumKey = (typeof mediaTaskJsonldGetItemMediaTaskStatusEnum)[keyof typeof mediaTaskJsonldGetItemMediaTaskStatusEnum];

export type MediaTaskJsonldGetItemMediaTask = (HydraItemBaseSchema & {
    file?: (FileJsonldGetItemMediaTask | null);
    user?: (UserJsonldGetItemMediaTask | null);
    /**
     * @type string,null
    */
    transcriptionResult?: string | null;
    /**
     * @type string,null
    */
    summaryResult?: string | null;
    /**
     * @default "CREATED"
     * @type string | undefined
    */
    status?: MediaTaskJsonldGetItemMediaTaskStatusEnumKey;
    /**
     * @type string,null
    */
    traceId?: string | null;
    /**
     * @type integer,null
    */
    duration?: number | null;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined, date-time
    */
    readonly dateCreate?: string;
});