/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FileJsonldGetCollectionMediaTasks } from "../file/jsonld-get-collection-media-tasks";
import type { HydraItemBaseSchema } from "../hydra-item-base-schema";

export const mediaTaskJsonldGetCollectionMediaTasksStatusEnum = {
    CREATED: "CREATED",
    TRANSCRIBE: "TRANSCRIBE",
    TRANSCRIBE_COMPLETED: "TRANSCRIBE_COMPLETED",
    TRANSCRIBE_ERROR: "TRANSCRIBE_ERROR",
    SUMMARY: "SUMMARY",
    SUMMARY_COMPLETED: "SUMMARY_COMPLETED",
    SUMMARY_ERROR: "SUMMARY_ERROR"
} as const;

export type MediaTaskJsonldGetCollectionMediaTasksStatusEnumKey = (typeof mediaTaskJsonldGetCollectionMediaTasksStatusEnum)[keyof typeof mediaTaskJsonldGetCollectionMediaTasksStatusEnum];

export type MediaTaskJsonldGetCollectionMediaTasks = (HydraItemBaseSchema & {
    file?: (FileJsonldGetCollectionMediaTasks | null);
    /**
     * @default "CREATED"
     * @type string | undefined
    */
    status?: MediaTaskJsonldGetCollectionMediaTasksStatusEnumKey;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined, date-time
    */
    readonly dateCreate?: string;
});