/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiRecordersGetCollectionQueryResponse, ApiRecordersGetCollection403 } from "../../models/recorder/api-recorders-get-collection";
import { http } from "msw";

export function ApiRecordersGetCollectionHandlerResponse200(data: ApiRecordersGetCollectionQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRecordersGetCollectionHandlerResponse403(data: ApiRecordersGetCollection403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRecordersGetCollectionHandler(data?: ApiRecordersGetCollectionQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/v1/recorders`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}