/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiAuthlogoutPostMutationResponse, ApiAuthlogoutPostMutationRequest } from "../../models";

function getApiAuthlogoutPostUrl() {
  return "/api/v1/auth/logout" as const;
}
/**
 * @summary Creates a Auth resource.
 * @description Creates a Auth resource.
 * {@link /api/v1/auth/logout}
 */
export const apiAuthlogoutPost = (
  args: {
    body: ApiAuthlogoutPostMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiAuthlogoutPostMutationResponse> => {
  return http.post(getApiAuthlogoutPostUrl(), {
    ...options,
    json: args.body,
  }).json<ApiAuthlogoutPostMutationResponse>();
};