/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiAuthtokenPostMutationResponse, ApiAuthtokenPostMutationRequest } from "../../models";

function getApiAuthtokenPostUrl() {
  return "/api/v1/auth/token" as const;
}
/**
 * @summary Creates a Auth resource.
 * @description Creates a Auth resource.
 * {@link /api/v1/auth/token}
 */
export const apiAuthtokenPost = (
  args: {
    body: ApiAuthtokenPostMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiAuthtokenPostMutationResponse> => {
  return http.post(getApiAuthtokenPostUrl(), {
    ...options,
    json: args.body,
  }).json<ApiAuthtokenPostMutationResponse>();
};