/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { TeamJsonldGetCurrentTeam } from "./jsonld-get-current-team";

/**
 * @description Team resource
*/
export type ApiCurrentTeamGet200 = TeamJsonldGetCurrentTeam;

/**
 * @description Forbidden
*/
export type ApiCurrentTeamGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiCurrentTeamGet404 = ErrorJsonld;

export type ApiCurrentTeamGetQueryResponse = ApiCurrentTeamGet200;

export type ApiCurrentTeamGetQuery = {
    Response: ApiCurrentTeamGet200;
    Errors: ApiCurrentTeamGet403 | ApiCurrentTeamGet404;
};