/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { TeamJsonldTeamRead } from "./jsonld-team-read";

export type ApiTeamsIdGetPathParams = {
    /**
     * @description Team identifier
     * @type string
    */
    id: string;
};

/**
 * @description Team resource
*/
export type ApiTeamsIdGet200 = TeamJsonldTeamRead;

/**
 * @description Forbidden
*/
export type ApiTeamsIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTeamsIdGet404 = ErrorJsonld;

export type ApiTeamsIdGetQueryResponse = ApiTeamsIdGet200;

export type ApiTeamsIdGetQuery = {
    Response: ApiTeamsIdGet200;
    PathParams: ApiTeamsIdGetPathParams;
    Errors: ApiTeamsIdGet403 | ApiTeamsIdGet404;
};