/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MultipartUploadMultipartStatusResponseDtoHtml = {
    /**
     * @type array | undefined
    */
    status?: string[];
};