/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { HydraCollectionBaseSchemaSchema } from "../hydra-collection-base-schema-schema";
import { ProviderJsonldProviderCollectionReadSchema } from "./jsonld-provider-collection-read-schema";

export const ApiProvidersGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(100).default(10).describe("The number of items per page")
    })

/**
 * @description Provider collection
 */
export const ApiProvidersGetCollection200Schema = z.lazy(() => HydraCollectionBaseSchemaSchema).and(z.object({
    "member": z.array(z.lazy(() => ProviderJsonldProviderCollectionReadSchema))
    })).describe("Provider.jsonld-ProviderCollectionRead collection.")

/**
 * @description Forbidden
 */
export const ApiProvidersGetCollection403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiProvidersGetCollectionQueryResponseSchema = z.lazy(() => ApiProvidersGetCollection200Schema)