/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { PropertyFormDataStorageItemReadGetIdPropertyReadSchema } from "../../../../property/form-data-storage/item/read-get-id-property/read-schema";

export const StorageFormDataStorageItemReadGetIdPropertyReadSchema = z.object({
    "name": z.optional(z.string()),
"slug": z.string().nullish(),
"properties": z.optional(z.array(z.lazy(() => PropertyFormDataStorageItemReadGetIdPropertyReadSchema))),
"id": z.optional(z.union([z.string(), z.string()]))
    })