/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiSubscriptionFeaturesIdGetQueryResponse, ApiSubscriptionFeaturesIdGetPathParams } from "../../models";

function getApiSubscriptionFeaturesIdGetUrl(params: ApiSubscriptionFeaturesIdGetPathParams) {
  return `/api/v1/subscription_features/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Retrieves a SubscriptionFeature resource.
 * @description Retrieves a SubscriptionFeature resource.
 * {@link /api/v1/subscription_features/{id}}
 */
export const apiSubscriptionFeaturesIdGet = (
  args: {
    params: ApiSubscriptionFeaturesIdGetPathParams;
  },
  options?: RequestOptions,
): Promise<ApiSubscriptionFeaturesIdGetQueryResponse> => {
  return http.get(getApiSubscriptionFeaturesIdGetUrl(args.params), {
    ...options,
  }).json<ApiSubscriptionFeaturesIdGetQueryResponse>();
};