/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";

export type FileGetResourcePathParams = {
    /**
     * @description Путь до файла на сервере
     * @type string | undefined
    */
    path?: string;
};

/**
 * @description File resource
*/
export type FileGetResource204 = any;

/**
 * @description Not found
*/
export type FileGetResource404 = ErrorJsonld;

export type FileGetResourceQueryResponse = FileGetResource204;

export type FileGetResourceQuery = {
    Response: FileGetResource204;
    PathParams: FileGetResourcePathParams;
    Errors: FileGetResource404;
};