/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type FileFormDataMediaTaskUpdateRead = {
    /**
     * @type string | undefined
    */
    originalName?: string;
    /**
     * @type integer,null
    */
    duration?: number | null;
};