/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type FileHtmlGet = {
    /**
     * @type string | undefined
    */
    originalName?: string;
    /**
     * @type string | undefined
    */
    path?: string;
    /**
     * @type string | undefined
    */
    fullPath?: string;
    /**
     * @type string | undefined
    */
    mimeType?: string;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};