/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";

export type FileJsonldMediaTaskUpdateRead = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    originalName?: string;
    /**
     * @type integer,null
    */
    duration?: number | null;
});