/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiMeetsGetCollectionQueryResponse, ApiMeetsGetCollectionQueryParams } from "../../models";

function getApiMeetsGetCollectionUrl() {
  return "/api/v1/meets" as const;
}
/**
 * @summary Retrieves the collection of Meet resources.
 * @description Retrieves the collection of Meet resources.
 * {@link /api/v1/meets}
 */
export const apiMeetsGetCollection = (
  args: {
    query: ApiMeetsGetCollectionQueryParams;
  },
  options?: RequestOptions,
): Promise<ApiMeetsGetCollectionQueryResponse> => {
  return http.get(getApiMeetsGetCollectionUrl(), {
    ...options,
    searchParams: args.query,
  }).json<ApiMeetsGetCollectionQueryResponse>();
};