/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiMeetsIdPatchMutationResponse, ApiMeetsIdPatchPathParams, ApiMeetsIdPatchMutationRequest } from "../../models";

function getApiMeetsIdPatchUrl(params: ApiMeetsIdPatchPathParams) {
  return `/api/v1/meets/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Updates the Meet resource.
 * @description Updates the Meet resource.
 * {@link /api/v1/meets/{id}}
 */
export const apiMeetsIdPatch = (
  args: {
    params: ApiMeetsIdPatchPathParams;
    body: ApiMeetsIdPatchMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiMeetsIdPatchMutationResponse> => {
  return http.patch(getApiMeetsIdPatchUrl(args.params), {
    ...options,
    json: args.body,
  }).json<ApiMeetsIdPatchMutationResponse>();
};