/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";
import { ProductJsonldGetCollectionPaymentSchema } from "../product/jsonld-get-collection-payment-schema";
import { SubscriptionJsonldGetCollectionPaymentSchema } from "../subscription/jsonld-get-collection-payment-schema";
import { TenantJsonldGetCollectionPaymentSchema } from "../tenant/jsonld-get-collection-payment-schema";

export const PaymentJsonldGetCollectionPaymentSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "customer": z.optional(z.union([z.lazy(() => TenantJsonldGetCollectionPaymentSchema), z.null()])),
"status": z.enum(["pending", "completed", "disputed", "partially_refunded", "fully_refunded", "failed", "overdue"]),
"amount": z.number().int().min(1).max(100000000).gt(0),
"currency": z.string().min(3).max(3),
"subscription": z.optional(z.union([z.lazy(() => SubscriptionJsonldGetCollectionPaymentSchema), z.null()])),
"product": z.optional(z.union([z.lazy(() => ProductJsonldGetCollectionPaymentSchema), z.null()])),
"id": z.optional(z.string()),
"createdAt": z.optional(z.string().datetime())
    }))