/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiApiTokenGetQueryResponse, ApiApiTokenGet403, ApiApiTokenGet404 } from "../../models/token/api-api-token-get";
import { http } from "msw";

export function ApiApiTokenGetHandlerResponse200(data: ApiApiTokenGetQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiApiTokenGetHandlerResponse403(data: ApiApiTokenGet403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiApiTokenGetHandlerResponse404(data: ApiApiTokenGet404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiApiTokenGetHandler(data?: ApiApiTokenGetQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/v1/api_token`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}