/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiRefreshTokenPatchMutationResponse, ApiRefreshTokenPatch400, ApiRefreshTokenPatch404, ApiRefreshTokenPatch422 } from "../../models/token/api-refresh-token-patch";
import { http } from "msw";

export function ApiRefreshTokenPatchHandlerResponse200(data: ApiRefreshTokenPatchMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRefreshTokenPatchHandlerResponse400(data: ApiRefreshTokenPatch400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRefreshTokenPatchHandlerResponse404(data: ApiRefreshTokenPatch404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRefreshTokenPatchHandlerResponse422(data: ApiRefreshTokenPatch422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRefreshTokenPatchHandler(data?: ApiRefreshTokenPatchMutationResponse | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.patch(`/api/v1/refresh_token`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}