/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../../hydra-item-base-schema";

export type MultipartUploadMultipartInitResponseDtoJsonld = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    uploadId?: string;
    /**
     * @type integer | undefined
    */
    chunkSize?: number;
    /**
     * @type integer | undefined
    */
    totalChunks?: number;
    /**
     * @type array | undefined
    */
    uploadedChunks?: string[];
    /**
     * @type integer | undefined
    */
    progress?: number;
    /**
     * @type string | undefined, date-time
    */
    expiresAt?: string;
    /**
     * @type boolean | undefined
    */
    resumed?: boolean;
});