/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiQuestionsIdGetQueryResponse, ApiQuestionsIdGetPathParams } from "../../models";

function getApiQuestionsIdGetUrl(params: ApiQuestionsIdGetPathParams) {
  return `/api/v1/questions/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Retrieves a Question resource.
 * @description Retrieves a Question resource.
 * {@link /api/v1/questions/{id}}
 */
export const apiQuestionsIdGet = (
  args: {
    params: ApiQuestionsIdGetPathParams;
  },
  options?: RequestOptions,
): Promise<ApiQuestionsIdGetQueryResponse> => {
  return http.get(getApiQuestionsIdGetUrl(args.params), {
    ...options,
  }).json<ApiQuestionsIdGetQueryResponse>();
};