/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiQuestionsIdanswerPatchMutationResponse, ApiQuestionsIdanswerPatchPathParams, ApiQuestionsIdanswerPatchMutationRequest } from "../../models";

function getApiQuestionsIdanswerPatchUrl(params: ApiQuestionsIdanswerPatchPathParams) {
  return `/api/v1/questions/${encodeURIComponent(String(params.id))}/answer` as const;
}
/**
 * @summary Updates the Question resource.
 * @description Updates the Question resource.
 * {@link /api/v1/questions/{id}/answer}
 */
export const apiQuestionsIdanswerPatch = (
  args: {
    params: ApiQuestionsIdanswerPatchPathParams;
    body: ApiQuestionsIdanswerPatchMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiQuestionsIdanswerPatchMutationResponse> => {
  return http.patch(getApiQuestionsIdanswerPatchUrl(args.params), {
    ...options,
    json: args.body,
  }).json<ApiQuestionsIdanswerPatchMutationResponse>();
};