/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { PriceJsonldGetCollectionTokenConsummationSchema } from "./jsonld-get-collection-token-consummation-schema";

export const ApiPricesIdGetPathParamsSchema = z.object({
    "id": z.string().describe("Price identifier")
    })

/**
 * @description Price resource
 */
export const ApiPricesIdGet200Schema = z.lazy(() => PriceJsonldGetCollectionTokenConsummationSchema)

/**
 * @description Forbidden
 */
export const ApiPricesIdGet403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiPricesIdGet404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiPricesIdGetQueryResponseSchema = z.lazy(() => ApiPricesIdGet200Schema)