/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const PriceFormDataGetCollectionSubscriptionPlanSchema = z.object({
    "period": z.optional(z.number().int().default(0)),
"id": z.optional(z.any()),
"amount": z.number().int().nullish(),
"schedule": z.string().nullish()
    })