/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const PriceFormDataGetCollectionTokenConsummationSchema = z.object({
    "id": z.optional(z.any())
    })