/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";

export const PriceJsonldGetCollectionSubscriptionPlanSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "period": z.optional(z.number().int().default(0)),
"id": z.optional(z.any()),
"amount": z.number().int().nullish(),
"schedule": z.string().nullish()
    }))