/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { TeamJsonldTeamReadSchema } from "./jsonld-team-read-schema";

export const ApiTeamsIdGetPathParamsSchema = z.object({
    "id": z.string().describe("Team identifier")
    })

/**
 * @description Team resource
 */
export const ApiTeamsIdGet200Schema = z.lazy(() => TeamJsonldTeamReadSchema)

/**
 * @description Forbidden
 */
export const ApiTeamsIdGet403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiTeamsIdGet404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiTeamsIdGetQueryResponseSchema = z.lazy(() => ApiTeamsIdGet200Schema)