/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";

export const TeamJsonldTeamReadSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "tokens": z.number().nullish(),
"tenant": z.object({
    
    }).catchall(z.number()).nullish(),
"id": z.optional(z.any()),
"name": z.string().nullish(),
"billingEmail": z.optional(z.string()),
"createdAt": z.optional(z.string().datetime())
    }))