/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const propertyStorageConfigDetailGetIdTypeEnum = {
    string: "string",
    number: "number",
    bool: "bool"
} as const;

export type PropertyStorageConfigDetailGetIdTypeEnumKey = (typeof propertyStorageConfigDetailGetIdTypeEnum)[keyof typeof propertyStorageConfigDetailGetIdTypeEnum];

export type PropertyStorageConfigDetailGetId = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @default "string"
     * @type string,null
    */
    type?: PropertyStorageConfigDetailGetIdTypeEnumKey | null;
    /**
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};