/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { StorageJsonldStorageItemReadGetIdPropertyRead } from "./jsonld-storage/item/read-get-id-property/read";

export type ApiStoragesIdGetPathParams = {
    /**
     * @description Storage identifier
     * @type string
    */
    id: string;
};

/**
 * @description Storage resource
*/
export type ApiStoragesIdGet200 = StorageJsonldStorageItemReadGetIdPropertyRead;

/**
 * @description Not found
*/
export type ApiStoragesIdGet404 = ErrorJsonld;

export type ApiStoragesIdGetQueryResponse = ApiStoragesIdGet200;

export type ApiStoragesIdGetQuery = {
    Response: ApiStoragesIdGet200;
    PathParams: ApiStoragesIdGetPathParams;
    Errors: ApiStoragesIdGet404;
};