/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { HydraCollectionBaseSchema } from "../hydra-collection-base-schema";
import type { StorageJsonldStorageListGetId } from "./jsonld-storage/list-get-id";

export type ApiStoragesGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 100
     * @default 10
     * @type integer | undefined
    */
    itemsPerPage?: number;
};

/**
 * @description Storage collection
*/
export type ApiStoragesGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: StorageJsonldStorageListGetId[];
});

/**
 * @description Forbidden
*/
export type ApiStoragesGetCollection403 = ErrorJsonld;

export type ApiStoragesGetCollectionQueryResponse = ApiStoragesGetCollection200;

export type ApiStoragesGetCollectionQuery = {
    Response: ApiStoragesGetCollection200;
    QueryParams: ApiStoragesGetCollectionQueryParams;
    Errors: ApiStoragesGetCollection403;
};