/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiRefreshTokenPatchMutationResponse, ApiRefreshTokenPatchMutationRequest } from "../../models";

function getApiRefreshTokenPatchUrl() {
  return "/api/v1/refresh_token" as const;
}
/**
 * @summary Updates the Token resource.
 * @description Updates the Token resource.
 * {@link /api/v1/refresh_token}
 */
export const apiRefreshTokenPatch = (
  args: {
    body: ApiRefreshTokenPatchMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiRefreshTokenPatchMutationResponse> => {
  return http.patch(getApiRefreshTokenPatchUrl(), {
    ...options,
    json: args.body,
  }).json<ApiRefreshTokenPatchMutationResponse>();
};