/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiCurrentTokenGetQueryResponse } from "../../models";

function getApiCurrentTokenGetUrl() {
  return "/api/v1/current_token" as const;
}
/**
 * @summary Retrieves a Token resource.
 * @description Retrieves a Token resource.
 * {@link /api/v1/current_token}
 */
export const apiCurrentTokenGet = (
  options?: RequestOptions,
): Promise<ApiCurrentTokenGetQueryResponse> => {
  return http.get(getApiCurrentTokenGetUrl(), {
    ...options,
  }).json<ApiCurrentTokenGetQueryResponse>();
};