/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiMediaTasksIdhistoryStatusesGetCollectionQueryResponse, ApiMediaTasksIdhistoryStatusesGetCollectionPathParams, ApiMediaTasksIdhistoryStatusesGetCollectionQueryParams } from "../../models";

function getApiMediaTasksIdhistoryStatusesGetCollectionUrl(params: ApiMediaTasksIdhistoryStatusesGetCollectionPathParams) {
  return `/api/v1/media_tasks/${encodeURIComponent(String(params.id))}/history_statuses` as const;
}
/**
 * @summary Retrieves the collection of MediaTaskStatusHistory resources.
 * @description Retrieves the collection of MediaTaskStatusHistory resources.
 * {@link /api/v1/media_tasks/{id}/history_statuses}
 */
export const apiMediaTasksIdhistoryStatusesGetCollection = (
  args: {
    params: ApiMediaTasksIdhistoryStatusesGetCollectionPathParams;
    query: ApiMediaTasksIdhistoryStatusesGetCollectionQueryParams;
  },
  options?: RequestOptions,
): Promise<ApiMediaTasksIdhistoryStatusesGetCollectionQueryResponse> => {
  return http.get(getApiMediaTasksIdhistoryStatusesGetCollectionUrl(args.params), {
    ...options,
    searchParams: args.query,
  }).json<ApiMediaTasksIdhistoryStatusesGetCollectionQueryResponse>();
};