/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const propertyFormDataStorageConfigDetailGetIdTypeEnum = {
    string: "string",
    number: "number",
    bool: "bool"
} as const;

export type PropertyFormDataStorageConfigDetailGetIdTypeEnumKey = (typeof propertyFormDataStorageConfigDetailGetIdTypeEnum)[keyof typeof propertyFormDataStorageConfigDetailGetIdTypeEnum];

export type PropertyFormDataStorageConfigDetailGetId = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @default "string"
     * @type string,null
    */
    type?: PropertyFormDataStorageConfigDetailGetIdTypeEnumKey | null;
    /**
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};