/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const MediaTaskStatusHistoryHtmlSchema = z.object({
    "status": z.optional(z.enum(["CREATED", "TRANSCRIBE", "TRANSCRIBE_COMPLETED", "TRANSCRIBE_ERROR", "SUMMARY", "SUMMARY_COMPLETED", "SUMMARY_ERROR"])),
"date": z.optional(z.string().datetime()),
"mediaTask": z.optional(z.string()),
"id": z.optional(z.union([z.string(), z.string()])),
"dateCreate": z.optional(z.string().datetime()),
"dateUpdate": z.string().datetime().nullish()
    })