/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";

export type MultipartJobStatusResponseDtoJsonld = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    jobId?: string;
    /**
     * @type string | undefined
    */
    status?: string;
    /**
     * @type array,null
    */
    result?: string[] | null;
    /**
     * @type array,null
    */
    error?: string[] | null;
    /**
     * @type integer,null
    */
    progress?: number | null;
    /**
     * @type string,null
    */
    currentOperation?: string | null;
    /**
     * @type integer,null
    */
    processedChunks?: number | null;
    /**
     * @type integer,null
    */
    totalChunks?: number | null;
    /**
     * @type string,null, date-time
    */
    startedAt?: string | null;
    /**
     * @type string,null, date-time
    */
    estimatedCompletion?: string | null;
    /**
     * @type integer,null
    */
    processingTime?: number | null;
    /**
     * @type string,null, date-time
    */
    createdAt?: string | null;
    /**
     * @type string,null, date-time
    */
    updatedAt?: string | null;
    /**
     * @type string,null, date-time
    */
    failedAt?: string | null;
    /**
     * @type boolean | undefined
    */
    notFound?: boolean;
});