/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../../hydra-item-base-schema-schema";

/**
 * @description Инициирует отправку письма для смены пароля через Keycloak.
 */
export const UserPasswordResetResponseDtoJsonldSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "message": z.optional(z.string())
    })).describe("Инициирует отправку письма для смены пароля через Keycloak.")