/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const UserInviteUserDtoJsonMergePatchSchema = z.object({
    "firstName": z.optional(z.string()),
"lastName": z.optional(z.string()),
"email": z.optional(z.string())
    })