/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { StorageJsonldStorageItemReadGetIdPropertyReadSchema } from "./jsonld-storage/item/read-get-id-property/read-schema";

export const ApiStoragesIdGetPathParamsSchema = z.object({
    "id": z.string().describe("Storage identifier")
    })

/**
 * @description Storage resource
 */
export const ApiStoragesIdGet200Schema = z.lazy(() => StorageJsonldStorageItemReadGetIdPropertyReadSchema)

/**
 * @description Not found
 */
export const ApiStoragesIdGet404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiStoragesIdGetQueryResponseSchema = z.lazy(() => ApiStoragesIdGet200Schema)