/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const StorageHtmlMeetCreateReadSchema = z.object({
    "slug": z.string().nullish(),
"id": z.optional(z.union([z.string(), z.string()]))
    })