/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { TokenTokenCurrentResponseDtoJsonldTokenCurrentResponse } from "./token-current-response-dto/jsonld-token-current-response";

/**
 * @description Token resource
*/
export type ApiCurrentTokenGet200 = TokenTokenCurrentResponseDtoJsonldTokenCurrentResponse;

/**
 * @description Forbidden
*/
export type ApiCurrentTokenGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiCurrentTokenGet404 = ErrorJsonld;

export type ApiCurrentTokenGetQueryResponse = ApiCurrentTokenGet200;

export type ApiCurrentTokenGetQuery = {
    Response: ApiCurrentTokenGet200;
    Errors: ApiCurrentTokenGet403 | ApiCurrentTokenGet404;
};