/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Возвращает текущие access и refresh токены пользователя
*/
export type TokenTokenCurrentResponseDtoTokenCurrentResponse = {
    /**
     * @type string,null
    */
    accessToken?: string | null;
    /**
     * @type string,null
    */
    refreshToken?: string | null;
};