/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../../hydra-item-base-schema";
import type { PropertyValueJsonldStorageConfigDetailGetId } from "../../property-value/jsonld-storage-config/detail-get-id";
import type { StorageJsonldStorageConfigDetailGetId } from "../../storage/jsonld-storage-config/detail-get-id";

export type StorageConfigJsonldStorageConfigDetailGetId = (HydraItemBaseSchema & {
    /**
     * @type string
    */
    name: string;
    storage: StorageJsonldStorageConfigDetailGetId;
    /**
     * @type array
    */
    propertyValues: PropertyValueJsonldStorageConfigDetailGetId[];
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});