/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../../hydra-item-base-schema";
import type { StorageJsonldStorageConfigListGetId } from "../../storage/jsonld-storage-config/list-get-id";

export type StorageConfigJsonldStorageConfigListGetId = (HydraItemBaseSchema & {
    /**
     * @type string
    */
    name: string;
    storage: StorageJsonldStorageConfigListGetId;
    /**
     * @default false
     * @type boolean | undefined
    */
    isGlobal?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});