/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";

/**
 * @description A representation of common errors.
*/
export type ErrorJsonld = (HydraItemBaseSchema & {
    /**
     * @description A short, human-readable summary of the problem.
     * @type string,null
    */
    readonly title?: string | null;
    /**
     * @description A human-readable explanation specific to this occurrence of the problem.
     * @type string,null
    */
    readonly detail?: string | null;
    /**
     * @default 400
     * @type number,null
    */
    status?: number | null;
    /**
     * @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
     * @type string,null
    */
    readonly instance?: string | null;
    /**
     * @description A URI reference that identifies the problem type
     * @type string | undefined
    */
    readonly type?: string;
    /**
     * @type string,null
    */
    readonly description?: string | null;
});