/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiCurrentUserGetQueryResponse } from "../../models";

function getApiCurrentUserGetUrl() {
  return "/api/v1/current_user" as const;
}
/**
 * @summary Retrieves a User resource.
 * @description Retrieves a User resource.
 * {@link /api/v1/current_user}
 */
export const apiCurrentUserGet = (
  options?: RequestOptions,
): Promise<ApiCurrentUserGetQueryResponse> => {
  return http.get(getApiCurrentUserGetUrl(), {
    ...options,
  }).json<ApiCurrentUserGetQueryResponse>();
};