/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiUsersIddeleteDeleteMutationResponse, ApiUsersIddeleteDeletePathParams } from "../../models";

function getApiUsersIddeleteDeleteUrl(params: ApiUsersIddeleteDeletePathParams) {
  return `/api/v1/users/${encodeURIComponent(String(params.id))}/delete` as const;
}
/**
 * @summary Removes the User resource.
 * @description Removes the User resource.
 * {@link /api/v1/users/{id}/delete}
 */
export const apiUsersIddeleteDelete = (
  args: {
    params: ApiUsersIddeleteDeletePathParams;
  },
  options?: RequestOptions,
): Promise<ApiUsersIddeleteDeleteMutationResponse> => {
  return http.delete(getApiUsersIddeleteDeleteUrl(args.params), {
    ...options,
  }).json<ApiUsersIddeleteDeleteMutationResponse>();
};