/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiUsersIdblockPatchMutationResponse, ApiUsersIdblockPatchPathParams, ApiUsersIdblockPatchMutationRequest } from "../../models";

function getApiUsersIdblockPatchUrl(params: ApiUsersIdblockPatchPathParams) {
  return `/api/v1/users/${encodeURIComponent(String(params.id))}/block` as const;
}
/**
 * @summary Updates the User resource.
 * @description Updates the User resource.
 * {@link /api/v1/users/{id}/block}
 */
export const apiUsersIdblockPatch = (
  args: {
    params: ApiUsersIdblockPatchPathParams;
    body: ApiUsersIdblockPatchMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiUsersIdblockPatchMutationResponse> => {
  return http.patch(getApiUsersIdblockPatchUrl(args.params), {
    ...options,
    json: args.body,
  }).json<ApiUsersIdblockPatchMutationResponse>();
};