/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../../src/fixtures/http-client";
import type { GetUserQueryResponse, GetUserPathParams } from "../../models";

function getGetUserUrl(params: GetUserPathParams) {
  return `/users/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Get user by id
 * {@link /users/{id}}
 */
export const getUser = (
  args: {
    params: GetUserPathParams;
  },
  options?: RequestOptions,
): Promise<GetUserQueryResponse> => {
  return http.get(getGetUserUrl(args.params), {
    ...options,
  }).json<GetUserQueryResponse>();
};