/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiRecorderConfigsIdPatchMutationResponse, ApiRecorderConfigsIdPatch400, ApiRecorderConfigsIdPatch403, ApiRecorderConfigsIdPatch404, ApiRecorderConfigsIdPatch422 } from "../../models/recorder-config/api-recorder-configs-id-patch";
import { http } from "msw";

export function ApiRecorderConfigsIdPatchHandlerResponse200(data: ApiRecorderConfigsIdPatchMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRecorderConfigsIdPatchHandlerResponse400(data: ApiRecorderConfigsIdPatch400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRecorderConfigsIdPatchHandlerResponse403(data: ApiRecorderConfigsIdPatch403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRecorderConfigsIdPatchHandlerResponse404(data: ApiRecorderConfigsIdPatch404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRecorderConfigsIdPatchHandlerResponse422(data: ApiRecorderConfigsIdPatch422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRecorderConfigsIdPatchHandler(data?: ApiRecorderConfigsIdPatchMutationResponse | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.patch(`/api/v1/recorder_configs/:id`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}