/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiRecorderConfigsIdDeleteMutationResponse, ApiRecorderConfigsIdDelete403, ApiRecorderConfigsIdDelete404 } from "../../models/recorder-config/api-recorder-configs-id-delete";
import { http } from "msw";

export function ApiRecorderConfigsIdDeleteHandlerResponse204(data?: ApiRecorderConfigsIdDeleteMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
}

export function ApiRecorderConfigsIdDeleteHandlerResponse403(data: ApiRecorderConfigsIdDelete403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRecorderConfigsIdDeleteHandlerResponse404(data: ApiRecorderConfigsIdDelete404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRecorderConfigsIdDeleteHandler(data?: string | number | boolean | null | object | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.delete(`/api/v1/recorder_configs/:id`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
    })
}