/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiRecorderConfigsIdstatusPatchMutationResponse, ApiRecorderConfigsIdstatusPatch400, ApiRecorderConfigsIdstatusPatch403, ApiRecorderConfigsIdstatusPatch404, ApiRecorderConfigsIdstatusPatch422 } from "../../models/recorder-config/api-recorder-configs-idstatus-patch";
import { http } from "msw";

export function ApiRecorderConfigsIdstatusPatchHandlerResponse200(data: ApiRecorderConfigsIdstatusPatchMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRecorderConfigsIdstatusPatchHandlerResponse400(data: ApiRecorderConfigsIdstatusPatch400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRecorderConfigsIdstatusPatchHandlerResponse403(data: ApiRecorderConfigsIdstatusPatch403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRecorderConfigsIdstatusPatchHandlerResponse404(data: ApiRecorderConfigsIdstatusPatch404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRecorderConfigsIdstatusPatchHandlerResponse422(data: ApiRecorderConfigsIdstatusPatch422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiRecorderConfigsIdstatusPatchHandler(data?: ApiRecorderConfigsIdstatusPatchMutationResponse | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.patch(`/api/v1/recorder_configs/:id/status`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}