/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiSubscriptionPlanIdpricePriceIdbuyPatchMutationResponse, ApiSubscriptionPlanIdpricePriceIdbuyPatch400, ApiSubscriptionPlanIdpricePriceIdbuyPatch403, ApiSubscriptionPlanIdpricePriceIdbuyPatch404, ApiSubscriptionPlanIdpricePriceIdbuyPatch422 } from "../../models/subscription-plan/api-subscription-plan-idprice-price-idbuy-patch";
import { http } from "msw";

export function ApiSubscriptionPlanIdpricePriceIdbuyPatchHandlerResponse200(data: ApiSubscriptionPlanIdpricePriceIdbuyPatchMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiSubscriptionPlanIdpricePriceIdbuyPatchHandlerResponse400(data: ApiSubscriptionPlanIdpricePriceIdbuyPatch400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiSubscriptionPlanIdpricePriceIdbuyPatchHandlerResponse403(data: ApiSubscriptionPlanIdpricePriceIdbuyPatch403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiSubscriptionPlanIdpricePriceIdbuyPatchHandlerResponse404(data: ApiSubscriptionPlanIdpricePriceIdbuyPatch404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiSubscriptionPlanIdpricePriceIdbuyPatchHandlerResponse422(data: ApiSubscriptionPlanIdpricePriceIdbuyPatch422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiSubscriptionPlanIdpricePriceIdbuyPatchHandler(data?: ApiSubscriptionPlanIdpricePriceIdbuyPatchMutationResponse | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.patch(`/api/v1/subscription_plan/:id/price/:priceId/buy`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}