/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "../constraint-violation/jsonld";
import type { ErrorJsonld } from "../error/jsonld";
import type { ProviderConfigProviderConfigItemWrite } from "../provider-config-provider-config-item-write";
import type { ProviderConfigJsonldProviderConfigItemRead } from "./jsonld-provider-config-item-read";

/**
 * @description ProviderConfig resource created
*/
export type ApiProviderConfigsPost201 = ProviderConfigJsonldProviderConfigItemRead;

/**
 * @description Invalid input
*/
export type ApiProviderConfigsPost400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiProviderConfigsPost403 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiProviderConfigsPost422 = ConstraintViolationJsonld;

/**
 * @description The new ProviderConfig resource
*/
export type ApiProviderConfigsPostMutationRequest = ProviderConfigProviderConfigItemWrite;

export type ApiProviderConfigsPostMutationResponse = ApiProviderConfigsPost201;

export type ApiProviderConfigsPostMutation = {
    Response: ApiProviderConfigsPost201;
    Request: ApiProviderConfigsPostMutationRequest;
    Errors: ApiProviderConfigsPost400 | ApiProviderConfigsPost403 | ApiProviderConfigsPost422;
};