/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";

export type ApiProviderConfigsIdDeletePathParams = {
    /**
     * @description ProviderConfig identifier
     * @type string
    */
    id: string;
};

/**
 * @description ProviderConfig resource deleted
*/
export type ApiProviderConfigsIdDelete204 = any;

/**
 * @description Forbidden
*/
export type ApiProviderConfigsIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiProviderConfigsIdDelete404 = ErrorJsonld;

export type ApiProviderConfigsIdDeleteMutationResponse = ApiProviderConfigsIdDelete204;

export type ApiProviderConfigsIdDeleteMutation = {
    Response: ApiProviderConfigsIdDelete204;
    PathParams: ApiProviderConfigsIdDeletePathParams;
    Errors: ApiProviderConfigsIdDelete403 | ApiProviderConfigsIdDelete404;
};