/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProviderFormDataGetCollectionIntegration } from "../provider/form-data-get-collection-integration";

export type ProviderConfigFormDataGetCollectionIntegration = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type object
    */
    provider: ProviderFormDataGetCollectionIntegration;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};