/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyValueFormDataProviderConfigCollectionRead } from "../property-value/form-data-provider-config-collection-read";
import type { ProviderFormDataProviderConfigCollectionRead } from "../provider/form-data-provider-config-collection-read";

export type ProviderConfigFormDataProviderConfigCollectionRead = {
    /**
     * @type string
    */
    name: string;
    /**
     * @default true
     * @type boolean | undefined
    */
    isActive?: boolean;
    /**
     * @type object
    */
    provider: ProviderFormDataProviderConfigCollectionRead;
    /**
     * @type array
    */
    propertyValues: PropertyValueFormDataProviderConfigCollectionRead[];
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};