/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProviderFormDataGetObjIntegration } from "../provider/form-data-get-obj-integration";

export type ProviderConfigFormDataGetObjIntegration = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type object
    */
    provider: ProviderFormDataGetObjIntegration;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};