/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyValueFormDataProviderConfigItemRead } from "../property-value/form-data-provider-config-item-read";
import type { ProviderFormDataProviderConfigItemRead } from "../provider/form-data-provider-config-item-read";

export type ProviderConfigFormDataProviderConfigItemRead = {
    /**
     * @type string
    */
    name: string;
    /**
     * @default true
     * @type boolean | undefined
    */
    isActive?: boolean;
    /**
     * @type object
    */
    provider: ProviderFormDataProviderConfigItemRead;
    /**
     * @type array
    */
    propertyValues: PropertyValueFormDataProviderConfigItemRead[];
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};