/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyValueHtmlProviderConfigCollectionRead } from "../property-value/html-provider-config-collection-read";
import type { ProviderHtmlProviderConfigCollectionRead } from "../provider/html-provider-config-collection-read";

export type ProviderConfigHtmlProviderConfigCollectionRead = {
    /**
     * @type string
    */
    name: string;
    /**
     * @default true
     * @type boolean | undefined
    */
    isActive?: boolean;
    /**
     * @type object
    */
    provider: ProviderHtmlProviderConfigCollectionRead;
    /**
     * @type array
    */
    propertyValues: PropertyValueHtmlProviderConfigCollectionRead[];
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};