/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProviderHtmlGetObjIntegration } from "../provider/html-get-obj-integration";

export type ProviderConfigHtmlGetObjIntegration = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type object
    */
    provider: ProviderHtmlGetObjIntegration;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};