/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyValueHtmlProviderConfigItemRead } from "../property-value/html-provider-config-item-read";
import type { ProviderHtmlProviderConfigItemRead } from "../provider/html-provider-config-item-read";

export type ProviderConfigHtmlProviderConfigItemRead = {
    /**
     * @type string
    */
    name: string;
    /**
     * @default true
     * @type boolean | undefined
    */
    isActive?: boolean;
    /**
     * @type object
    */
    provider: ProviderHtmlProviderConfigItemRead;
    /**
     * @type array
    */
    propertyValues: PropertyValueHtmlProviderConfigItemRead[];
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};