/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ProviderConfigHtmlMeetCreateRead = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};