/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProviderConfigErrorHtml } from "../provider-config-error/html";

export type ProviderConfigHtml = {
    /**
     * @type string
    */
    name: string;
    /**
     * @default true
     * @type boolean | undefined
    */
    isActive?: boolean;
    /**
     * @type string, iri-reference
    */
    provider: string;
    /**
     * @type array
    */
    propertyValues: string[];
    /**
     * @type array | undefined
    */
    errors?: ProviderConfigErrorHtml[];
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined, date-time
    */
    readonly dateCreate?: string;
    /**
     * @type string,null, date-time
    */
    readonly dateUpdate?: string | null;
};