/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";

export type ProviderConfigJsonldMeetUpdateRead = (HydraItemBaseSchema & {
    /**
     * @type string
    */
    name: string;
});