/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";
import type { ProviderJsonldMeetReadItem } from "../provider/jsonld-meet-read-item";

export type ProviderConfigJsonldMeetReadItem = (HydraItemBaseSchema & {
    /**
     * @type string
    */
    name: string;
    provider: ProviderJsonldMeetReadItem;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});