/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";

export const ApiTokenConsummationsIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("TokenConsummation identifier")
    })

/**
 * @description TokenConsummation resource deleted
 */
export const ApiTokenConsummationsIdDelete204Schema = z.any()

/**
 * @description Not found
 */
export const ApiTokenConsummationsIdDelete404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiTokenConsummationsIdDeleteMutationResponseSchema = z.lazy(() => ApiTokenConsummationsIdDelete204Schema)