/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../../hydra-item-base-schema-schema";

export const MultipartUploadMultipartCompleteResponseDtoJsonldSetSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "message": z.optional(z.string()),
"error": z.string().nullish(),
"jobId": z.optional(z.string())
    }))