/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { RecorderJsonldRecorderItemReadGetIdPropertyRead } from "./jsonld-recorder/item/read-get-id-property/read";

export type ApiRecordersIdGetPathParams = {
    /**
     * @description Recorder identifier
     * @type string
    */
    id: string;
};

/**
 * @description Recorder resource
*/
export type ApiRecordersIdGet200 = RecorderJsonldRecorderItemReadGetIdPropertyRead;

/**
 * @description Not found
*/
export type ApiRecordersIdGet404 = ErrorJsonld;

export type ApiRecordersIdGetQueryResponse = ApiRecordersIdGet200;

export type ApiRecordersIdGetQuery = {
    Response: ApiRecordersIdGet200;
    PathParams: ApiRecordersIdGetPathParams;
    Errors: ApiRecordersIdGet404;
};