/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "../error/jsonld";
import type { HydraCollectionBaseSchema } from "../hydra-collection-base-schema";
import type { RecorderJsonldRecorderCollectionReadGetId } from "./jsonld-recorder/collection/read-get-id";

export type ApiRecordersGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 100
     * @default 10
     * @type integer | undefined
    */
    itemsPerPage?: number;
};

/**
 * @description Recorder collection
*/
export type ApiRecordersGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: RecorderJsonldRecorderCollectionReadGetId[];
});

/**
 * @description Forbidden
*/
export type ApiRecordersGetCollection403 = ErrorJsonld;

export type ApiRecordersGetCollectionQueryResponse = ApiRecordersGetCollection200;

export type ApiRecordersGetCollectionQuery = {
    Response: ApiRecordersGetCollection200;
    QueryParams: ApiRecordersGetCollectionQueryParams;
    Errors: ApiRecordersGetCollection403;
};