/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiCurrentSubscriptionGetQueryResponse } from "../../models";

function getApiCurrentSubscriptionGetUrl() {
  return "/api/v1/current_subscription" as const;
}
/**
 * @summary Retrieves a Subscription resource.
 * @description Retrieves a Subscription resource.
 * {@link /api/v1/current_subscription}
 */
export const apiCurrentSubscriptionGet = (
  options?: RequestOptions,
): Promise<ApiCurrentSubscriptionGetQueryResponse> => {
  return http.get(getApiCurrentSubscriptionGetUrl(), {
    ...options,
  }).json<ApiCurrentSubscriptionGetQueryResponse>();
};