/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

/**
 * @description Использует refresh_token для получения новой пары токенов от Keycloak
 */
export const TokenTokenRefreshResponseDtoFormDataTokenRefreshResponseSchema = z.object({
    "accessToken": z.optional(z.string()),
"refreshToken": z.optional(z.string())
    }).describe("Использует refresh_token для получения новой пары токенов от Keycloak")