/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiPaymentsIdGetQueryResponse, ApiPaymentsIdGet403, ApiPaymentsIdGet404 } from "../../models/payment/api-payments-id-get";
import { http } from "msw";

export function ApiPaymentsIdGetHandlerResponse200(data: ApiPaymentsIdGetQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiPaymentsIdGetHandlerResponse403(data: ApiPaymentsIdGet403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiPaymentsIdGetHandlerResponse404(data: ApiPaymentsIdGet404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiPaymentsIdGetHandler(data?: ApiPaymentsIdGetQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/v1/payments/:id`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}