/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { RecorderJsonldRecorderItemReadGetIdPropertyReadSchema } from "./jsonld-recorder/item/read-get-id-property/read-schema";

export const ApiRecordersIdGetPathParamsSchema = z.object({
    "id": z.string().describe("Recorder identifier")
    })

/**
 * @description Recorder resource
 */
export const ApiRecordersIdGet200Schema = z.lazy(() => RecorderJsonldRecorderItemReadGetIdPropertyReadSchema)

/**
 * @description Not found
 */
export const ApiRecordersIdGet404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiRecordersIdGetQueryResponseSchema = z.lazy(() => ApiRecordersIdGet200Schema)