/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../../src/fixtures/http-client";
import type { DeleteUserMutationResponse, DeleteUserPathParams } from "../../models";
import { buildPath } from "../../runtime/build-path";

export const deleteUser = (
  args: {
    params: DeleteUserPathParams;
  },
  options?: RequestOptions,
): Promise<DeleteUserMutationResponse> => {
  return http.delete(buildPath("/users/{id}", { params: args.params }), {
    ...options,
  }).json<DeleteUserMutationResponse>();
};