/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../../src/fixtures/http-client";
import type { GetUserQueryResponse, GetUserPathParams } from "../../models";
import { buildPath } from "../../runtime/build-path";

export const getUser = (
  args: {
    params: GetUserPathParams;
  },
  options?: RequestOptions,
): Promise<GetUserQueryResponse> => {
  return http.get(buildPath("/users/{id}", { params: args.params }), {
    ...options,
  }).json<GetUserQueryResponse>();
};