/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const mediaTaskStatusHistoryHtmlStatusEnum = {
    CREATED: "CREATED",
    TRANSCRIBE: "TRANSCRIBE",
    TRANSCRIBE_COMPLETED: "TRANSCRIBE_COMPLETED",
    TRANSCRIBE_ERROR: "TRANSCRIBE_ERROR",
    SUMMARY: "SUMMARY",
    SUMMARY_COMPLETED: "SUMMARY_COMPLETED",
    SUMMARY_ERROR: "SUMMARY_ERROR"
} as const;

export type MediaTaskStatusHistoryHtmlStatusEnumKey = (typeof mediaTaskStatusHistoryHtmlStatusEnum)[keyof typeof mediaTaskStatusHistoryHtmlStatusEnum];

export type MediaTaskStatusHistoryHtml = {
    /**
     * @type string | undefined
    */
    status?: MediaTaskStatusHistoryHtmlStatusEnumKey;
    /**
     * @type string | undefined, date-time
    */
    date?: string;
    /**
     * @type string | undefined, iri-reference
    */
    mediaTask?: string;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined, date-time
    */
    readonly dateCreate?: string;
    /**
     * @type string,null, date-time
    */
    readonly dateUpdate?: string | null;
};