/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";

export const mediaTaskStatusHistoryJsonldStatusEnum = {
    CREATED: "CREATED",
    TRANSCRIBE: "TRANSCRIBE",
    TRANSCRIBE_COMPLETED: "TRANSCRIBE_COMPLETED",
    TRANSCRIBE_ERROR: "TRANSCRIBE_ERROR",
    SUMMARY: "SUMMARY",
    SUMMARY_COMPLETED: "SUMMARY_COMPLETED",
    SUMMARY_ERROR: "SUMMARY_ERROR"
} as const;

export type MediaTaskStatusHistoryJsonldStatusEnumKey = (typeof mediaTaskStatusHistoryJsonldStatusEnum)[keyof typeof mediaTaskStatusHistoryJsonldStatusEnum];

export type MediaTaskStatusHistoryJsonld = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    status?: MediaTaskStatusHistoryJsonldStatusEnumKey;
    /**
     * @type string | undefined, date-time
    */
    date?: string;
    /**
     * @type string | undefined, iri-reference
    */
    mediaTask?: string;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
    /**
     * @type string | undefined, date-time
    */
    readonly dateCreate?: string;
    /**
     * @type string,null, date-time
    */
    readonly dateUpdate?: string | null;
});