/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UserUserItemWriteJsonMergePatch = {
    /**
     * @type string | undefined
    */
    firstName?: string;
    /**
     * @type string | undefined
    */
    lastName?: string;
    /**
     * @type string | undefined, email
    */
    email?: string;
    /**
     * @minLength 0
     * @default 0
     * @type number | undefined
    */
    personalTokenLimit?: number;
};