/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AddressHtmlGetCurrentTenant } from "../address/html-get-current-tenant";

export const tenantHtmlGetCurrentTenantTenantTypeEnum = {
    company: "company",
    person: "person"
} as const;

export type TenantHtmlGetCurrentTenantTenantTypeEnumKey = (typeof tenantHtmlGetCurrentTenantTenantTypeEnum)[keyof typeof tenantHtmlGetCurrentTenantTenantTypeEnum];

export type TenantHtmlGetCurrentTenant = {
    /**
     * @type string | undefined, ulid
    */
    readonly id?: string;
    /**
     * @type string,null
    */
    name?: string | null;
    /**
     * @type string | undefined
    */
    subdomain?: string;
    /**
     * @type string | undefined
    */
    tenantType?: TenantHtmlGetCurrentTenantTenantTypeEnumKey;
    /**
     * @type object | undefined
    */
    billingAddress?: AddressHtmlGetCurrentTenant;
};