/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AddressJsonldGetCurrentTenant } from "../address/jsonld-get-current-tenant";
import type { HydraItemBaseSchema } from "../hydra-item-base-schema";

export const tenantJsonldGetCurrentTenantTenantTypeEnum = {
    company: "company",
    person: "person"
} as const;

export type TenantJsonldGetCurrentTenantTenantTypeEnumKey = (typeof tenantJsonldGetCurrentTenantTenantTypeEnum)[keyof typeof tenantJsonldGetCurrentTenantTenantTypeEnum];

export type TenantJsonldGetCurrentTenant = (HydraItemBaseSchema & {
    /**
     * @type string | undefined, ulid
    */
    readonly id?: string;
    /**
     * @type string,null
    */
    name?: string | null;
    /**
     * @type string | undefined
    */
    subdomain?: string;
    /**
     * @type string | undefined
    */
    tenantType?: TenantJsonldGetCurrentTenantTenantTypeEnumKey;
    /**
     * @type object | undefined
    */
    billingAddress?: AddressJsonldGetCurrentTenant;
});