/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const propertyStorageItemReadGetIdPropertyReadTypeEnum = {
    string: "string",
    number: "number",
    bool: "bool"
} as const;

export type PropertyStorageItemReadGetIdPropertyReadTypeEnumKey = (typeof propertyStorageItemReadGetIdPropertyReadTypeEnum)[keyof typeof propertyStorageItemReadGetIdPropertyReadTypeEnum];

export const propertyStorageItemReadGetIdPropertyReadForEntityEnum = {
    provider: "provider",
    recorder: "recorder",
    storage: "storage"
} as const;

export type PropertyStorageItemReadGetIdPropertyReadForEntityEnumKey = (typeof propertyStorageItemReadGetIdPropertyReadForEntityEnum)[keyof typeof propertyStorageItemReadGetIdPropertyReadForEntityEnum];

export type PropertyStorageItemReadGetIdPropertyRead = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @default "string"
     * @type string,null
    */
    type?: PropertyStorageItemReadGetIdPropertyReadTypeEnumKey | null;
    /**
     * @type string,null
    */
    forEntity?: PropertyStorageItemReadGetIdPropertyReadForEntityEnumKey | null;
    /**
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};