import { echoTsupConfig } from "@echojs-ecosystem/oxc-config/tsup";

export default echoTsupConfig({
  entry: {
    index: "src/index.ts",
    "is/index": "src/is/index.ts",
    "sensors/window-size/index": "src/sensors/window-size/index.ts",
    "sensors/media-query/index": "src/sensors/media-query/index.ts",
    "sensors/breakpoints/index": "src/sensors/breakpoints/index.ts",
    "sensors/mouse/index": "src/sensors/mouse/index.ts",
    "sensors/scroll/index": "src/sensors/scroll/index.ts",
    "sensors/network/index": "src/sensors/network/index.ts",
    "sensors/online/index": "src/sensors/online/index.ts",
    "browser/clipboard/index": "src/browser/clipboard/index.ts",
    "browser/document-title/index": "src/browser/document-title/index.ts",
    "browser/favicon/index": "src/browser/favicon/index.ts",
    "browser/color-scheme/index": "src/browser/color-scheme/index.ts",
    "browser/event-listener/index": "src/browser/event-listener/index.ts",
    "timing/timeout/index": "src/timing/timeout/index.ts",
    "timing/interval/index": "src/timing/interval/index.ts",
    "timing/debounce/index": "src/timing/debounce/index.ts",
    "timing/throttle/index": "src/timing/throttle/index.ts",
    "state/toggle/index": "src/state/toggle/index.ts",
    "state/counter/index": "src/state/counter/index.ts",
    "state/boolean/index": "src/state/boolean/index.ts",
    "state/previous/index": "src/state/previous/index.ts",
    "dom/element-size/index": "src/dom/element-size/index.ts",
    "dom/resize-observer/index": "src/dom/resize-observer/index.ts",
    "dom/intersection-observer/index": "src/dom/intersection-observer/index.ts",
    "dom/click-outside/index": "src/dom/click-outside/index.ts",
    "browser/document-visibility/index": "src/browser/document-visibility/index.ts",
    "browser/device-pixel-ratio/index": "src/browser/device-pixel-ratio/index.ts",
    "browser/fullscreen/index": "src/browser/fullscreen/index.ts",
    "browser/active-element/index": "src/browser/active-element/index.ts",
    "browser/permission/index": "src/browser/permission/index.ts",
    "browser/css-var/index": "src/browser/css-var/index.ts",
    "sensors/idle/index": "src/sensors/idle/index.ts",
    "sensors/geolocation/index": "src/sensors/geolocation/index.ts",
    "sensors/hotkeys/index": "src/sensors/hotkeys/index.ts",
    "sensors/page-leave/index": "src/sensors/page-leave/index.ts",
    "sensors/key-press/index": "src/sensors/key-press/index.ts",
    "dom/hover/index": "src/dom/hover/index.ts",
    "dom/focus/index": "src/dom/focus/index.ts",
    "state/local-storage/index": "src/state/local-storage/index.ts",
    "state/hash/index": "src/state/hash/index.ts",
  },
});
