/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { SubscriptionFeatureJsonldGetIdSchema } from "./jsonld-get-id-schema";

export const ApiSubscriptionFeaturesIdGetPathParamsSchema = z.object({
    "id": z.string().describe("SubscriptionFeature identifier")
    })

/**
 * @description SubscriptionFeature resource
 */
export const ApiSubscriptionFeaturesIdGet200Schema = z.lazy(() => SubscriptionFeatureJsonldGetIdSchema)

/**
 * @description Forbidden
 */
export const ApiSubscriptionFeaturesIdGet403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiSubscriptionFeaturesIdGet404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiSubscriptionFeaturesIdGetQueryResponseSchema = z.lazy(() => ApiSubscriptionFeaturesIdGet200Schema)