/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const SubscriptionFeatureFormDataGetCollectionSubscriptionPlanSchema = z.object({
    "name": z.optional(z.string()),
"description": z.string().nullish(),
"id": z.optional(z.union([z.string(), z.string()]))
    })