/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateUserRequest } from "../CreateUserRequest";
import type { User } from "../User";

/**
 * @description Created user
*/
export type CreateUser201 = User;

export type CreateUserMutationRequest = CreateUserRequest;

export type CreateUserMutationResponse = CreateUser201;

export type CreateUserMutation = {
    Response: CreateUser201;
    Request: CreateUserMutationRequest;
    Errors: any;
};