/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { User } from "../User";

/**
 * @description Users list
*/
export type ListUsers200 = User[];

export type ListUsersQueryResponse = ListUsers200;

export type ListUsersQuery = {
    Response: ListUsers200;
    Errors: any;
};