/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiStoragesGetCollectionQueryResponse, ApiStoragesGetCollection403 } from "../../models/storage/api-storages-get-collection";
import { http } from "msw";

export function ApiStoragesGetCollectionHandlerResponse200(data: ApiStoragesGetCollectionQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiStoragesGetCollectionHandlerResponse403(data: ApiStoragesGetCollection403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiStoragesGetCollectionHandler(data?: ApiStoragesGetCollectionQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/v1/storages`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}