/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiStoragesIdGetQueryResponse, ApiStoragesIdGet404 } from "../../models/storage/api-storages-id-get";
import { http } from "msw";

export function ApiStoragesIdGetHandlerResponse200(data: ApiStoragesIdGetQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiStoragesIdGetHandlerResponse404(data: ApiStoragesIdGet404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiStoragesIdGetHandler(data?: ApiStoragesIdGetQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/v1/storages/:id`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}