/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";

/**
 * @description A representation of common errors.
 */
export const ErrorJsonldSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "title": z.string().describe("A short, human-readable summary of the problem.").nullish(),
"detail": z.string().describe("A human-readable explanation specific to this occurrence of the problem.").nullish(),
"status": z.number().default(400).nullish(),
"instance": z.string().describe("A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.").nullish(),
"type": z.optional(z.string().describe("A URI reference that identifies the problem type")),
"description": z.string().nullish()
    })).describe("A representation of common errors.")