/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../../hydra-item-base-schema";
import type { PropertyJsonldStorageConfigDetailGetId } from "../../property/jsonld-storage-config/detail-get-id";

export type PropertyValueJsonldStorageConfigDetailGetId = (HydraItemBaseSchema & {
    /**
     * @type string,null
    */
    value?: string | null;
    property: PropertyJsonldStorageConfigDetailGetId;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});