/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { AuthInputCodeDtoSchema } from "./input-code-dto-schema";
import { AuthTokenDtoJsonldSchema } from "./token-dto/jsonld-schema";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";

/**
 * @description Auth resource created
 */
export const ApiAuthtokenPost201Schema = z.lazy(() => AuthTokenDtoJsonldSchema)

/**
 * @description Invalid input
 */
export const ApiAuthtokenPost400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiAuthtokenPost422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new Auth resource
 */
export const ApiAuthtokenPostMutationRequestSchema = z.lazy(() => AuthInputCodeDtoSchema)

export const ApiAuthtokenPostMutationResponseSchema = z.lazy(() => ApiAuthtokenPost201Schema)