/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { CompanyRegistrationDtoSchema } from "../company-registration-dto-schema";
import { PersonRegistrationDtoSchema } from "../person-registration-dto-schema";

export const AuthBaseRegistrationDtoSchema = z.object({
    "email": z.string().email(),
"tenantType": z.optional(z.enum(["company", "person"])),
"companyRegistrationDto": z.optional(z.union([z.lazy(() => CompanyRegistrationDtoSchema), z.null()])),
"personRegistrationDto": z.optional(z.union([z.lazy(() => PersonRegistrationDtoSchema), z.null()]))
    })