/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const AuthInputCodeDtoSchema = z.object({
    "code": z.optional(z.string()),
"redirectUri": z.optional(z.string())
    })