/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../../hydra-item-base-schema";

export type MultipartUploadMultipartCompleteResponseDtoJsonldSet = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string,null
    */
    error?: string | null;
    /**
     * @type string | undefined
    */
    jobId?: string;
});