/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import { createQuery } from "@echojs-ecosystem/async";
import { getUser } from "../../endpoints/users/get-user";
import type { GetUserQueryResponse, GetUserPathParams } from "../../models";
import { queryDefaults } from "../defaults";

/**
 * @summary Get user by id
 */
export const getUserQuery = createQuery<GetUserQueryResponse, GetUserPathParams>({
  ...queryDefaults,
  name: "get-user",
  queryKey: (params) => ["getUser", params],
  queryFn: ({ params, signal }) => getUser({ params: params }, { signal }),
});