/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiProviderConfigsPostMutationResponse, ApiProviderConfigsPost400, ApiProviderConfigsPost403, ApiProviderConfigsPost422 } from "../../models/provider-config/api-provider-configs-post";
import { http } from "msw";

export function ApiProviderConfigsPostHandlerResponse201(data: ApiProviderConfigsPostMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiProviderConfigsPostHandlerResponse400(data: ApiProviderConfigsPost400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiProviderConfigsPostHandlerResponse403(data: ApiProviderConfigsPost403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiProviderConfigsPostHandlerResponse422(data: ApiProviderConfigsPost422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiProviderConfigsPostHandler(data?: ApiProviderConfigsPostMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.post(`/api/v1/provider_configs`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}