/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiUsersIdresetPasswordPatchMutationResponse, ApiUsersIdresetPasswordPatch400, ApiUsersIdresetPasswordPatch403, ApiUsersIdresetPasswordPatch404, ApiUsersIdresetPasswordPatch422 } from "../../models/user/api-users-idreset-password-patch";
import { http } from "msw";

export function ApiUsersIdresetPasswordPatchHandlerResponse200(data: ApiUsersIdresetPasswordPatchMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiUsersIdresetPasswordPatchHandlerResponse400(data: ApiUsersIdresetPasswordPatch400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiUsersIdresetPasswordPatchHandlerResponse403(data: ApiUsersIdresetPasswordPatch403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiUsersIdresetPasswordPatchHandlerResponse404(data: ApiUsersIdresetPasswordPatch404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiUsersIdresetPasswordPatchHandlerResponse422(data: ApiUsersIdresetPasswordPatch422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiUsersIdresetPasswordPatchHandler(data?: ApiUsersIdresetPasswordPatchMutationResponse | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.patch(`/api/v1/users/:id/reset_password`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
    })
}