/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiUsersIddeleteDeleteMutationResponse, ApiUsersIddeleteDelete403, ApiUsersIddeleteDelete404 } from "../../models/user/api-users-iddelete-delete";
import { http } from "msw";

export function ApiUsersIddeleteDeleteHandlerResponse204(data?: ApiUsersIddeleteDeleteMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
}

export function ApiUsersIddeleteDeleteHandlerResponse403(data: ApiUsersIddeleteDelete403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiUsersIddeleteDeleteHandlerResponse404(data: ApiUsersIddeleteDelete404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/ld+json'
        },
      })
}

export function ApiUsersIddeleteDeleteHandler(data?: string | number | boolean | null | object | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.delete(`/api/v1/users/:id/delete`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
    })
}