/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { SubscriptionJsonldGetCurrentSubscriptionSchema } from "./jsonld-get-current-subscription-schema";

/**
 * @description Subscription resource
 */
export const ApiCurrentSubscriptionGet200Schema = z.lazy(() => SubscriptionJsonldGetCurrentSubscriptionSchema)

/**
 * @description Forbidden
 */
export const ApiCurrentSubscriptionGet403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiCurrentSubscriptionGet404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiCurrentSubscriptionGetQueryResponseSchema = z.lazy(() => ApiCurrentSubscriptionGet200Schema)