/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const SubscriptionHtmlGetCollectionPaymentSchema = z.object({
    "planName": z.string().nullish()
    })