/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { PriceHtmlGetCurrentSubscriptionSchema } from "../price/html-get-current-subscription-schema";
import { SubscriptionPlanHtmlGetCurrentSubscriptionSchema } from "../subscription-plan/html-get-current-subscription-schema";

export const SubscriptionHtmlGetCurrentSubscriptionSchema = z.object({
    "id": z.optional(z.any()),
"price": z.optional(z.union([z.lazy(() => PriceHtmlGetCurrentSubscriptionSchema), z.null()])),
"endedAt": z.string().datetime().nullish(),
"subscriptionPlan": z.optional(z.union([z.lazy(() => SubscriptionPlanHtmlGetCurrentSubscriptionSchema), z.null()])),
"status": z.optional(z.enum(["active", "overdue_payment_open", "pending_cancel", "overdue_payment_disabled", "paused", "cancelled", "blocked", "trial_active", "trial_ended"])),
"paymentSchedule": z.string().nullish(),
"createdAt": z.string().datetime().nullish()
    })