/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";
import { PriceJsonldGetCurrentSubscriptionSchema } from "../price/jsonld-get-current-subscription-schema";
import { SubscriptionPlanJsonldGetCurrentSubscriptionSchema } from "../subscription-plan/jsonld-get-current-subscription-schema";

export const SubscriptionJsonldGetCurrentSubscriptionSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "id": z.optional(z.any()),
"price": z.optional(z.union([z.lazy(() => PriceJsonldGetCurrentSubscriptionSchema), z.null()])),
"endedAt": z.string().datetime().nullish(),
"subscriptionPlan": z.optional(z.union([z.lazy(() => SubscriptionPlanJsonldGetCurrentSubscriptionSchema), z.null()])),
"status": z.optional(z.enum(["active", "overdue_payment_open", "pending_cancel", "overdue_payment_disabled", "paused", "cancelled", "blocked", "trial_active", "trial_ended"])),
"paymentSchedule": z.string().nullish(),
"createdAt": z.string().datetime().nullish()
    }))