/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";

export const SubscriptionJsonldGetItemPaymentSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "planName": z.string().nullish(),
"id": z.optional(z.any()),
"endedAt": z.string().datetime().nullish(),
"createdAt": z.string().datetime().nullish()
    }))