/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const mediaTaskMediaTaskUpdateJsonMergePatchStatusEnum = {
    CREATED: "CREATED",
    TRANSCRIBE: "TRANSCRIBE",
    TRANSCRIBE_COMPLETED: "TRANSCRIBE_COMPLETED",
    TRANSCRIBE_ERROR: "TRANSCRIBE_ERROR",
    SUMMARY: "SUMMARY",
    SUMMARY_COMPLETED: "SUMMARY_COMPLETED",
    SUMMARY_ERROR: "SUMMARY_ERROR"
} as const;

export type MediaTaskMediaTaskUpdateJsonMergePatchStatusEnumKey = (typeof mediaTaskMediaTaskUpdateJsonMergePatchStatusEnum)[keyof typeof mediaTaskMediaTaskUpdateJsonMergePatchStatusEnum];

export type MediaTaskMediaTaskUpdateJsonMergePatch = {
    /**
     * @type string,null
    */
    transcriptionResult?: string | null;
    /**
     * @type string,null
    */
    summaryResult?: string | null;
    /**
     * @default "CREATED"
     * @type string | undefined
    */
    status?: MediaTaskMediaTaskUpdateJsonMergePatchStatusEnumKey;
};