/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../../../../hydra-item-base-schema";
import type { PropertyJsonldStorageItemReadGetIdPropertyRead } from "../../../../property/jsonld-storage/item/read-get-id-property/read";

export type StorageJsonldStorageItemReadGetIdPropertyRead = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    slug?: string | null;
    /**
     * @type array | undefined
    */
    properties?: PropertyJsonldStorageItemReadGetIdPropertyRead[];
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});