/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MeetConsumeTokenDtoFormDataReportIntegrationErrorResponse = {
    /**
     * @default 0
     * @type number | undefined
    */
    availableBalance?: number;
};