/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiIntegrationsGetCollectionQueryResponse, ApiIntegrationsGetCollectionQueryParams } from "../../models";

function getApiIntegrationsGetCollectionUrl() {
  return "/api/v1/integrations" as const;
}
/**
 * @summary Retrieves the collection of Integration resources.
 * @description Retrieves the collection of Integration resources.
 * {@link /api/v1/integrations}
 */
export const apiIntegrationsGetCollection = (
  args: {
    query: ApiIntegrationsGetCollectionQueryParams;
  },
  options?: RequestOptions,
): Promise<ApiIntegrationsGetCollectionQueryResponse> => {
  return http.get(getApiIntegrationsGetCollectionUrl(), {
    ...options,
    searchParams: args.query,
  }).json<ApiIntegrationsGetCollectionQueryResponse>();
};