/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiIntegrationsPostMutationResponse, ApiIntegrationsPostMutationRequest } from "../../models";

function getApiIntegrationsPostUrl() {
  return "/api/v1/integrations" as const;
}
/**
 * @summary Creates a Integration resource.
 * @description Creates a Integration resource.
 * {@link /api/v1/integrations}
 */
export const apiIntegrationsPost = (
  args: {
    body: ApiIntegrationsPostMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiIntegrationsPostMutationResponse> => {
  return http.post(getApiIntegrationsPostUrl(), {
    ...options,
    json: args.body,
  }).json<ApiIntegrationsPostMutationResponse>();
};