/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const RecorderRecorderCollectionReadGetIdSchema = z.object({
    "name": z.optional(z.string()),
"slug": z.string().nullish(),
"isPreAuthorization": z.optional(z.boolean().default(false)),
"id": z.optional(z.union([z.string(), z.string()]))
    })