/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const MultipartChunkChunkWriteSchema = z.object({
    "upload": z.nullable(z.string()),
"chunkIndex": z.optional(z.number().int().min(0)),
"checksum": z.optional(z.string()),
"chunkFile": z.optional(z.instanceof(File))
    })