/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { RecorderConfigRecorderConfigWriteSchema } from "../recorder-config-recorder-config-write-schema";
import { RecorderConfigJsonldRecorderConfigReadItemSchema } from "./jsonld-recorder-config-read-item-schema";

/**
 * @description RecorderConfig resource created
 */
export const ApiRecorderConfigsPost201Schema = z.lazy(() => RecorderConfigJsonldRecorderConfigReadItemSchema)

/**
 * @description Invalid input
 */
export const ApiRecorderConfigsPost400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiRecorderConfigsPost403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiRecorderConfigsPost422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new RecorderConfig resource
 */
export const ApiRecorderConfigsPostMutationRequestSchema = z.lazy(() => RecorderConfigRecorderConfigWriteSchema)

export const ApiRecorderConfigsPostMutationResponseSchema = z.lazy(() => ApiRecorderConfigsPost201Schema)