/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { RecorderConfigJsonldRecorderConfigReadItemSchema } from "./jsonld-recorder-config-read-item-schema";

export const ApiRecorderConfigsIdGetPathParamsSchema = z.object({
    "id": z.string().describe("RecorderConfig identifier")
    })

/**
 * @description RecorderConfig resource
 */
export const ApiRecorderConfigsIdGet200Schema = z.lazy(() => RecorderConfigJsonldRecorderConfigReadItemSchema)

/**
 * @description Forbidden
 */
export const ApiRecorderConfigsIdGet403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiRecorderConfigsIdGet404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiRecorderConfigsIdGetQueryResponseSchema = z.lazy(() => ApiRecorderConfigsIdGet200Schema)