/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { RecorderConfigRecorderConfigWriteJsonMergePatchSchema } from "../recorder-config-recorder-config-write/json-merge-patch-schema";
import { RecorderConfigJsonldRecorderConfigReadItemSchema } from "./jsonld-recorder-config-read-item-schema";

export const ApiRecorderConfigsIdPatchPathParamsSchema = z.object({
    "id": z.string().describe("RecorderConfig identifier")
    })

/**
 * @description RecorderConfig resource updated
 */
export const ApiRecorderConfigsIdPatch200Schema = z.lazy(() => RecorderConfigJsonldRecorderConfigReadItemSchema)

/**
 * @description Invalid input
 */
export const ApiRecorderConfigsIdPatch400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiRecorderConfigsIdPatch403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiRecorderConfigsIdPatch404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiRecorderConfigsIdPatch422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated RecorderConfig resource
 */
export const ApiRecorderConfigsIdPatchMutationRequestSchema = z.lazy(() => RecorderConfigRecorderConfigWriteJsonMergePatchSchema)

export const ApiRecorderConfigsIdPatchMutationResponseSchema = z.lazy(() => ApiRecorderConfigsIdPatch200Schema)