/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { RecorderConfigRecorderConfigupdateStatusJsonMergePatchSchema } from "../recorder-config-recorder-configupdate-status/json-merge-patch-schema";
import { RecorderConfigJsonldRecorderConfigReadItemSchema } from "./jsonld-recorder-config-read-item-schema";

export const ApiRecorderConfigsIdstatusPatchPathParamsSchema = z.object({
    "id": z.string().describe("RecorderConfig identifier")
    })

/**
 * @description RecorderConfig resource updated
 */
export const ApiRecorderConfigsIdstatusPatch200Schema = z.lazy(() => RecorderConfigJsonldRecorderConfigReadItemSchema)

/**
 * @description Invalid input
 */
export const ApiRecorderConfigsIdstatusPatch400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiRecorderConfigsIdstatusPatch403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiRecorderConfigsIdstatusPatch404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiRecorderConfigsIdstatusPatch422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated RecorderConfig resource
 */
export const ApiRecorderConfigsIdstatusPatchMutationRequestSchema = z.lazy(() => RecorderConfigRecorderConfigupdateStatusJsonMergePatchSchema)

export const ApiRecorderConfigsIdstatusPatchMutationResponseSchema = z.lazy(() => ApiRecorderConfigsIdstatusPatch200Schema)