/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { PropertyValueFormDataRecorderConfigReadItemSchema } from "../property-value/form-data-recorder-config-read-item-schema";
import { RecorderFormDataRecorderConfigReadItemSchema } from "../recorder/form-data-recorder-config-read-item-schema";

export const RecorderConfigFormDataRecorderConfigReadItemSchema = z.object({
    "name": z.string(),
"isActive": z.boolean().default(true),
"recorder": z.union([z.lazy(() => RecorderFormDataRecorderConfigReadItemSchema), z.null()]),
"propertyValues": z.array(z.lazy(() => PropertyValueFormDataRecorderConfigReadItemSchema)),
"status": z.optional(z.enum(["NOT_REQUIRE_AUTHORIZATION", "WAITING_AUTHORIZATION", "RECORDER_PROCESS_AUTHORIZATION", "ERROR_AUTHORIZATION", "AUTHORIZED"]).default("NOT_REQUIRE_AUTHORIZATION").describe("Статус")),
"isGlobal": z.optional(z.boolean().default(false)),
"id": z.optional(z.union([z.string(), z.string()]))
    })