/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { RecorderFormDataGetCollectionIntegrationSchema } from "../recorder/form-data-get-collection-integration-schema";

export const RecorderConfigFormDataGetCollectionIntegrationSchema = z.object({
    "name": z.string(),
"recorder": z.union([z.lazy(() => RecorderFormDataGetCollectionIntegrationSchema), z.null()]),
"id": z.optional(z.union([z.string(), z.string()]))
    })