/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { RecorderFormDataMeetReadItemSchema } from "../recorder/form-data-meet-read-item-schema";

export const RecorderConfigFormDataMeetReadItemSchema = z.object({
    "name": z.string(),
"recorder": z.union([z.lazy(() => RecorderFormDataMeetReadItemSchema), z.null()]),
"id": z.optional(z.union([z.string(), z.string()]))
    })