/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const RecorderConfigFormDataMeetUpdateReadSchema = z.object({
    "name": z.string(),
"recorder": z.nullable(z.string())
    })