/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { RecorderHtmlGetObjIntegrationSchema } from "../recorder/html-get-obj-integration-schema";

export const RecorderConfigHtmlGetObjIntegrationSchema = z.object({
    "name": z.string(),
"recorder": z.union([z.lazy(() => RecorderHtmlGetObjIntegrationSchema), z.null()]),
"id": z.optional(z.union([z.string(), z.string()]))
    })