/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { RecorderHtmlMeetReadItemSchema } from "../recorder/html-meet-read-item-schema";

export const RecorderConfigHtmlMeetReadItemSchema = z.object({
    "name": z.string(),
"recorder": z.union([z.lazy(() => RecorderHtmlMeetReadItemSchema), z.null()]),
"id": z.optional(z.union([z.string(), z.string()]))
    })