/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { RecorderHtmlMeetCreateReadSchema } from "../recorder/html-meet-create-read-schema";

export const RecorderConfigHtmlMeetCreateReadSchema = z.object({
    "name": z.string(),
"recorder": z.union([z.lazy(() => RecorderHtmlMeetCreateReadSchema), z.null()]),
"id": z.optional(z.union([z.string(), z.string()]))
    })