/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { RecorderConfigErrorHtmlSchema } from "../recorder-config-error/html-schema";

export const RecorderConfigHtmlSchema = z.object({
    "name": z.string(),
"isActive": z.boolean().default(true),
"recorder": z.nullable(z.string()),
"propertyValues": z.array(z.string()),
"errors": z.optional(z.array(z.lazy(() => RecorderConfigErrorHtmlSchema))),
"status": z.optional(z.enum(["NOT_REQUIRE_AUTHORIZATION", "WAITING_AUTHORIZATION", "RECORDER_PROCESS_AUTHORIZATION", "ERROR_AUTHORIZATION", "AUTHORIZED"]).default("NOT_REQUIRE_AUTHORIZATION").describe("Статус")),
"questions": z.optional(z.array(z.string())),
"isGlobal": z.optional(z.boolean().default(false)),
"id": z.optional(z.union([z.string(), z.string()])),
"dateCreate": z.optional(z.string().datetime()),
"dateUpdate": z.string().datetime().nullish(),
"organizationDomain": z.string().nullish(),
"transcriptionEnabled": z.optional(z.boolean()),
"summarizationEnabled": z.optional(z.boolean())
    })