/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";
import { RecorderJsonldGetObjIntegrationSchema } from "../recorder/jsonld-get-obj-integration-schema";

export const RecorderConfigJsonldGetObjIntegrationSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "name": z.string(),
"recorder": z.union([z.lazy(() => RecorderJsonldGetObjIntegrationSchema), z.null()]),
"id": z.optional(z.union([z.string(), z.string()]))
    }))