/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";
import { PropertyValueJsonldRecorderConfigReadItemSchema } from "../property-value/jsonld-recorder-config-read-item-schema";
import { RecorderJsonldRecorderConfigReadItemSchema } from "../recorder/jsonld-recorder-config-read-item-schema";

export const RecorderConfigJsonldRecorderConfigReadItemSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "name": z.string(),
"isActive": z.boolean().default(true),
"recorder": z.union([z.lazy(() => RecorderJsonldRecorderConfigReadItemSchema), z.null()]),
"propertyValues": z.array(z.lazy(() => PropertyValueJsonldRecorderConfigReadItemSchema)),
"status": z.optional(z.enum(["NOT_REQUIRE_AUTHORIZATION", "WAITING_AUTHORIZATION", "RECORDER_PROCESS_AUTHORIZATION", "ERROR_AUTHORIZATION", "AUTHORIZED"]).default("NOT_REQUIRE_AUTHORIZATION").describe("Статус")),
"isGlobal": z.optional(z.boolean().default(false)),
"id": z.optional(z.union([z.string(), z.string()]))
    }))