/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";
import { RecorderJsonldMeetReadItemSchema } from "../recorder/jsonld-meet-read-item-schema";

export const RecorderConfigJsonldMeetReadItemSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "name": z.string(),
"recorder": z.union([z.lazy(() => RecorderJsonldMeetReadItemSchema), z.null()]),
"id": z.optional(z.union([z.string(), z.string()]))
    }))