/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { StorageConfigJsonldStorageConfigDetailGetIdSchema } from "./jsonld-storage-config/detail-get-id-schema";

export const ApiStorageConfigsIdGetPathParamsSchema = z.object({
    "id": z.string().describe("StorageConfig identifier")
    })

/**
 * @description StorageConfig resource
 */
export const ApiStorageConfigsIdGet200Schema = z.lazy(() => StorageConfigJsonldStorageConfigDetailGetIdSchema)

/**
 * @description Forbidden
 */
export const ApiStorageConfigsIdGet403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const ApiStorageConfigsIdGet404Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

export const ApiStorageConfigsIdGetQueryResponseSchema = z.lazy(() => ApiStorageConfigsIdGet200Schema)