/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { ConstraintViolationJsonldSchema } from "../constraint-violation/jsonld-schema";
import { ErrorJsonldSchema } from "../error/jsonld-schema";
import { StorageConfigStorageConfigCreateSchema } from "../storage-config-storage-config/create-schema";
import { StorageConfigJsonldStorageConfigDetailGetIdSchema } from "./jsonld-storage-config/detail-get-id-schema";

/**
 * @description StorageConfig resource created
 */
export const ApiStorageConfigsPost201Schema = z.lazy(() => StorageConfigJsonldStorageConfigDetailGetIdSchema)

/**
 * @description Invalid input
 */
export const ApiStorageConfigsPost400Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const ApiStorageConfigsPost403Schema = z.lazy(() => ErrorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const ApiStorageConfigsPost422Schema = z.lazy(() => ConstraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new StorageConfig resource
 */
export const ApiStorageConfigsPostMutationRequestSchema = z.lazy(() => StorageConfigStorageConfigCreateSchema)

export const ApiStorageConfigsPostMutationResponseSchema = z.lazy(() => ApiStorageConfigsPost201Schema)