/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { StorageFormDataGetObjIntegrationSchema } from "../storage/form-data-get-obj-integration-schema";

export const StorageConfigFormDataGetObjIntegrationSchema = z.object({
    "name": z.string(),
"storage": z.lazy(() => StorageFormDataGetObjIntegrationSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })