/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { StorageFormDataGetCollectionIntegrationSchema } from "../storage/form-data-get-collection-integration-schema";

export const StorageConfigFormDataGetCollectionIntegrationSchema = z.object({
    "name": z.string(),
"storage": z.lazy(() => StorageFormDataGetCollectionIntegrationSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })