/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { StorageFormDataMeetCreateReadSchema } from "../storage/form-data-meet-create-read-schema";

export const StorageConfigFormDataMeetCreateReadSchema = z.object({
    "name": z.string(),
"storage": z.lazy(() => StorageFormDataMeetCreateReadSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })