/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { StorageHtmlMeetUpdateReadSchema } from "../storage/html-meet-update-read-schema";

export const StorageConfigHtmlMeetUpdateReadSchema = z.object({
    "name": z.string(),
"storage": z.lazy(() => StorageHtmlMeetUpdateReadSchema)
    })