/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { StorageHtmlMeetReadItemSchema } from "../storage/html-meet-read-item-schema";

export const StorageConfigHtmlMeetReadItemSchema = z.object({
    "name": z.string(),
"storage": z.lazy(() => StorageHtmlMeetReadItemSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    })