/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";
import { StorageJsonldMeetReadItemSchema } from "../storage/jsonld-meet-read-item-schema";

export const StorageConfigJsonldMeetReadItemSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "name": z.string(),
"storage": z.lazy(() => StorageJsonldMeetReadItemSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    }))