/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";
import { StorageJsonldMeetCreateReadSchema } from "../storage/jsonld-meet-create-read-schema";

export const StorageConfigJsonldMeetCreateReadSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "name": z.string(),
"storage": z.lazy(() => StorageJsonldMeetCreateReadSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    }))