/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { HydraItemBaseSchemaSchema } from "../hydra-item-base-schema-schema";
import { StorageJsonldGetCollectionIntegrationSchema } from "../storage/jsonld-get-collection-integration-schema";

export const StorageConfigJsonldGetCollectionIntegrationSchema = z.lazy(() => HydraItemBaseSchemaSchema).and(z.object({
    "name": z.string(),
"storage": z.lazy(() => StorageJsonldGetCollectionIntegrationSchema),
"id": z.optional(z.union([z.string(), z.string()]))
    }))