/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiRecorderConfigsIdPatchMutationResponse, ApiRecorderConfigsIdPatchPathParams, ApiRecorderConfigsIdPatchMutationRequest } from "../../models";

function getApiRecorderConfigsIdPatchUrl(params: ApiRecorderConfigsIdPatchPathParams) {
  return `/api/v1/recorder_configs/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Updates the RecorderConfig resource.
 * @description Updates the RecorderConfig resource.
 * {@link /api/v1/recorder_configs/{id}}
 */
export const apiRecorderConfigsIdPatch = (
  args: {
    params: ApiRecorderConfigsIdPatchPathParams;
    body: ApiRecorderConfigsIdPatchMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiRecorderConfigsIdPatchMutationResponse> => {
  return http.patch(getApiRecorderConfigsIdPatchUrl(args.params), {
    ...options,
    json: args.body,
  }).json<ApiRecorderConfigsIdPatchMutationResponse>();
};