/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiRecorderConfigsGetCollectionQueryResponse, ApiRecorderConfigsGetCollectionQueryParams } from "../../models";

function getApiRecorderConfigsGetCollectionUrl() {
  return "/api/v1/recorder_configs" as const;
}
/**
 * @summary Retrieves the collection of RecorderConfig resources.
 * @description Retrieves the collection of RecorderConfig resources.
 * {@link /api/v1/recorder_configs}
 */
export const apiRecorderConfigsGetCollection = (
  args: {
    query: ApiRecorderConfigsGetCollectionQueryParams;
  },
  options?: RequestOptions,
): Promise<ApiRecorderConfigsGetCollectionQueryResponse> => {
  return http.get(getApiRecorderConfigsGetCollectionUrl(), {
    ...options,
    searchParams: args.query,
  }).json<ApiRecorderConfigsGetCollectionQueryResponse>();
};