/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiRecorderConfigsIdDeleteMutationResponse, ApiRecorderConfigsIdDeletePathParams } from "../../models";

function getApiRecorderConfigsIdDeleteUrl(params: ApiRecorderConfigsIdDeletePathParams) {
  return `/api/v1/recorder_configs/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Removes the RecorderConfig resource.
 * @description Removes the RecorderConfig resource.
 * {@link /api/v1/recorder_configs/{id}}
 */
export const apiRecorderConfigsIdDelete = (
  args: {
    params: ApiRecorderConfigsIdDeletePathParams;
  },
  options?: RequestOptions,
): Promise<ApiRecorderConfigsIdDeleteMutationResponse> => {
  return http.delete(getApiRecorderConfigsIdDeleteUrl(args.params), {
    ...options,
  }).json<ApiRecorderConfigsIdDeleteMutationResponse>();
};