/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiTokenConsummationsIdGetQueryResponse, ApiTokenConsummationsIdGetPathParams } from "../../models";

function getApiTokenConsummationsIdGetUrl(params: ApiTokenConsummationsIdGetPathParams) {
  return `/api/v1/token_consummations/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Retrieves a TokenConsummation resource.
 * @description Retrieves a TokenConsummation resource.
 * {@link /api/v1/token_consummations/{id}}
 */
export const apiTokenConsummationsIdGet = (
  args: {
    params: ApiTokenConsummationsIdGetPathParams;
  },
  options?: RequestOptions,
): Promise<ApiTokenConsummationsIdGetQueryResponse> => {
  return http.get(getApiTokenConsummationsIdGetUrl(args.params), {
    ...options,
  }).json<ApiTokenConsummationsIdGetQueryResponse>();
};