/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiTokenConsummationsIdPatchMutationResponse, ApiTokenConsummationsIdPatchPathParams, ApiTokenConsummationsIdPatchMutationRequest } from "../../models";

function getApiTokenConsummationsIdPatchUrl(params: ApiTokenConsummationsIdPatchPathParams) {
  return `/api/v1/token_consummations/${encodeURIComponent(String(params.id))}` as const;
}
/**
 * @summary Updates the TokenConsummation resource.
 * @description Updates the TokenConsummation resource.
 * {@link /api/v1/token_consummations/{id}}
 */
export const apiTokenConsummationsIdPatch = (
  args: {
    params: ApiTokenConsummationsIdPatchPathParams;
    body: ApiTokenConsummationsIdPatchMutationRequest;
  },
  options?: RequestOptions,
): Promise<ApiTokenConsummationsIdPatchMutationResponse> => {
  return http.patch(getApiTokenConsummationsIdPatchUrl(args.params), {
    ...options,
    json: args.body,
  }).json<ApiTokenConsummationsIdPatchMutationResponse>();
};