/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiTokenConsummationsGetCollectionQueryResponse, ApiTokenConsummationsGetCollectionQueryParams } from "../../models";

function getApiTokenConsummationsGetCollectionUrl() {
  return "/api/v1/token_consummations" as const;
}
/**
 * @summary Retrieves the collection of TokenConsummation resources.
 * @description Retrieves the collection of TokenConsummation resources.
 * {@link /api/v1/token_consummations}
 */
export const apiTokenConsummationsGetCollection = (
  args: {
    query: ApiTokenConsummationsGetCollectionQueryParams;
  },
  options?: RequestOptions,
): Promise<ApiTokenConsummationsGetCollectionQueryResponse> => {
  return http.get(getApiTokenConsummationsGetCollectionUrl(), {
    ...options,
    searchParams: args.query,
  }).json<ApiTokenConsummationsGetCollectionQueryResponse>();
};