/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyFormDataPropertyValueItemRead } from "../property/form-data-property-value-item-read";

export type PropertyValueFormDataPropertyValueItemRead = {
    /**
     * @type string,null
    */
    value?: string | null;
    /**
     * @type object
    */
    property: PropertyFormDataPropertyValueItemRead;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};