/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PropertyHtmlProviderConfigItemRead } from "../property/html-provider-config-item-read";

export type PropertyValueHtmlProviderConfigItemRead = {
    /**
     * @type string,null
    */
    value?: string | null;
    /**
     * @type object
    */
    property: PropertyHtmlProviderConfigItemRead;
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
};