/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../hydra-item-base-schema";

export type PropertyValueJsonldProviderConfigCollectionRead = (HydraItemBaseSchema & {
    /**
     * @type unknown | undefined, ulid
    */
    id?: (string | string);
});