/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const MultipartChunkMultipartUploadResponseDtoHtmlSchema = z.object({
    "chunkIndex": z.optional(z.number().int()),
"uploadedChunks": z.optional(z.array(z.string().nullable())),
"progress": z.optional(z.number().int()),
"missingChunks": z.optional(z.array(z.string().nullable())),
"totalBytesUploaded": z.optional(z.number().int()),
"status": z.optional(z.enum(["PENDING", "UPLOADING", "VERIFYING", "COMPLETED", "FAILED", "EXPIRED"])),
"nextChunk": z.number().int().nullish()
    })