/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { UserSchema } from "../user-schema";
import { z } from "zod/v4";

export const GetUserPathParamsSchema = z.object({
    "id": z.string()
    })

/**
 * @description User found
 */
export const GetUser200Schema = z.lazy(() => UserSchema)

export const GetUserQueryResponseSchema = z.lazy(() => GetUser200Schema)