/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


import type { RequestOptions } from "@echojs-ecosystem/network/http";
import { http } from "../../../src/core/http-client";
import type { ApiRecordersIdpropertiesGetCollectionQueryResponse, ApiRecordersIdpropertiesGetCollectionPathParams, ApiRecordersIdpropertiesGetCollectionQueryParams } from "../../models";

function getApiRecordersIdpropertiesGetCollectionUrl(params: ApiRecordersIdpropertiesGetCollectionPathParams) {
  return `/api/v1/recorders/${encodeURIComponent(String(params.id))}/properties` as const;
}
/**
 * @summary Retrieves the collection of Property resources.
 * @description Retrieves the collection of Property resources.
 * {@link /api/v1/recorders/{id}/properties}
 */
export const apiRecordersIdpropertiesGetCollection = (
  args: {
    params: ApiRecordersIdpropertiesGetCollectionPathParams;
    query: ApiRecordersIdpropertiesGetCollectionQueryParams;
  },
  options?: RequestOptions,
): Promise<ApiRecordersIdpropertiesGetCollectionQueryResponse> => {
  return http.get(getApiRecordersIdpropertiesGetCollectionUrl(args.params), {
    ...options,
    searchParams: args.query,
  }).json<ApiRecordersIdpropertiesGetCollectionQueryResponse>();
};